### PR TITLE
fix numpy for python 2.7 builds

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Thanks!

**Comment by kain88-de** [comment]
seems to build python 2.7 again. Yay!

**Comment by orbeckst** [comment]
I'll be happy to approve as soon as the CI is green. Feel free to ping me if I don't notice.

**Comment by kain88-de** [comment]
the osx job has timedout. I'll restart it. if it fails again maybe remove the test case already now?

**Comment by orbeckst** [comment]
Yeah, I think I could live with macOS Python 2.7 being removed and speeding up the tests. 

Still, let's see if the restart makes it pass completely, which would be good to know as this PR is Py 2.7 specific.

**Comment by orbeckst** [comment]
The job exceeded the time limit but was successful up to 91% of the tests.

Let's remove macOSX Python 2.7.

**Comment by orbeckst** [comment]
I commented out the macOS Python 2.7 build.

**Comment by orbeckst** [comment]
Many thanks!!!

**Pull request merged**
