### PR TITLE
Refactor chain reader

### PR DESCRIPTION
**Pull request by orbeckst**
Refactored ChainReader into separate module.

Changes made in this Pull Request:
 - `coordinates.base.ChainReader` --> `coordinates.chain.ChainReader`
 - renamed `ChainReader.get_flname()` --> `ChainReader._get_filename()`
 - split `test_coordinates.py` into `test_chainreader.py` and `test_amber_inputcrd.py`
 - minor cleanups in docs and tests (test_modelling)

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - n/a Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Note that running
```
./mda_nosetests -v coordinates/test_chainreader.py
```
shows many open files.

Does this mean that the ChainReader does not properly close files?

```
(develop)yngvi:MDAnalysisTests oliver$ ./mda_nosetests  coordinates/test_chainreader.py
...............
Cleanup: deleting offset files in /Volumes/Data/oliver/Biop/Library/python/mdanalysis/testsuite/MDAnalysisTests/data


By the end of the tests, there are 40 open handle for 3 files:
* (1) /Volumes/Data/oliver/Biop/Library/python/mdanalysis/testsuite/MDAnalysisTests/data/adk_closed.pdb
* (2) /Volumes/Data/oliver/Biop/Library/python/mdanalysis/testsuite/MDAnalysisTests/data/adk_open.pdb
* (37) /Volumes/Data/oliver/Biop/Library/python/mdanalysis/testsuite/MDAnalysisTests/data/adk_dims.dcd
----------------------------------------------------------------------
Ran 15 tests in 2.736s

OK

```

**Comment by orbeckst** [comment]
I did not create a stub or deprecation for `coordinates.base.ChainReader` because we are only using this internally. (Also, I think I couldn't figure out how to do this without introducing a circular import.)

**Comment by kain88-de** [comment]
btw I noticed that the chainreader can be really slow using xtc files. I have a feeling that is generates the offsets files everytime even though they already exits. I haven't really looked much into yet thats why I haven't created an issue.

**Comment by orbeckst** [comment]
rebased against develop and `git push -f`.

**Comment by orbeckst** [comment]
I think this is ready to be merged then.

It would be good if we could look into the issue of open file handles https://github.com/MDAnalysis/mdanalysis/pull/1079#pullrequestreview-9351389 because that looks like a bug to me – I can open a new issue once this is merged.

Regarding the apparent slowness with XTC https://github.com/MDAnalysis/mdanalysis/pull/1079#issuecomment-261738105 : I haven't benchmarked anything and I also wouldn't understand why it would regenerate the index files – all it does is create as many readers it needs and the switches between them. I don't think that the overhead of finding the correct reader and frame in the reader is that high but if the ChainReader is forced to do access by accessing individual frames instead of being available to iterate then that *might* slow things down. I think `ChainReader._chaine_iterator()` is doing the right thing but it's certainly worth looking at the code again – if I remember correctly, I wrote this on a long bus ride in the middle of the night in Portland, OR.

**Pull request merged**
