### PR TITLE
Logo fixup

### LINKED ISSUE #3121: logos are not suitable with transparent background
## Expected behavior ##

Logo can be used on different color background (e.g. for NumFOCUS promotional material)

## Actual behavior ##

SVG/PDF versions of our logos have white patches on A and D

## Code to reproduce the behavior ##

See logos.

### PR DESCRIPTION
**Pull request by orbeckst**
Fix #3121

Changes made in this Pull Request:
 - updated reference logo files
 - removed non-transparent areas in A and D letters
 - removed stray lines around some letters

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
I did not touch the mdanalysis-logo-thin.png, which is actually used in the docs because it looks as if @lilyminium already cleaned it up and made sure that it has the right dimensions. 

I also did not regenerate the small versions mdanalysis-logo-200x150.png and mdanalysis-logo-127x55.png because they are rendered on white anyway (and the minor line clean up is not noticeable).

**Comment by lilyminium** [comment]
> I also did not regenerate the small versions mdanalysis-logo-200x150.png and mdanalysis-logo-127x55.png because they are rendered on white anyway (and the minor line clean up is not noticeable).

It looks like these png files are transparent anyway. Thank you for doing this!

**Review by lilyminium — COMMENTED** [review]
It looks as though `mdanalysis-logo.png`, `mdanalysis-logo_square.png`, `mdanalysis-logo_square_72dpi.png`, and `mdanalysis-logo_square_45mm.png` still have white backgrounds?

**Comment by orbeckst** [comment]
They originally had white backgrounds so I left those (the only difference is the line clean up).

However, if we want them with transparent background I can make them transparent. What is going to be more useful? Just do a review and say what needs changing ;-).

**Review by lilyminium — APPROVED** [review]
The SVG is nice and transparent so that should do for general promotional purposes, and it's a vector file so it can be resized without issue :-) Thank you!

**Review by IAlibay — APPROVED** [review]
lgtm

**Pull request merged**
