### PR TITLE
updated template asv.conf.json to Python 3.8

### LINKED ISSUE #3430: Move benchmarks to > 3.7
## Expected behavior ##

Since support has been dropped for  2.7 and 3.6  should bump the benchmarks from the current 2.7 python up to whatever version  is appropriate. 

This is  mainly a reminder to change the value in `asv.conf.json`  from:
```
    "pythons": ["2.7"],
```
to whatever version is appropriate once bench environment is setup.

Linked to https://github.com/MDAnalysis/benchmarks/issues/11

## Actual behavior ##

 tests fail to run unless pythons=2.7 is commented out.
## Code to reproduce the behavior ##

running the benchmarks with `asv run` or `asv continuous`

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #3430

Changes made in this Pull Request:
 - updated matrix from 2.7 to 3.8
 - automated benchmarks were updated (see https://github.com/MDAnalysis/benchmarks/issues/11)

PR Checklist
------------
 - n/a Tests?
 - n/a Docs?
 - n/a CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM pending CI :)

**Comment by orbeckst** [comment]
Thanks for the quick review. Could you merge it when ready, please?

Thanks!

**Comment by IAlibay** [comment]
Cancelling CI and restarting - something off with the docs build, seeing if it's intermittent.

**Comment by IAlibay** [comment]
oof something is going wrong with CI... looks like runners are having a field day but gh status is being fine. Hold for re-run in a few hours?

**Comment by hmacdope** [comment]
re-triggered

**Comment by IAlibay** [comment]
Still failing on docs - let me check if there's been a recent update to sphinx related things.

**Comment by IAlibay** [comment]
This seems to be the major difference between the last passing CI run and the current failure:

"intersphinx inventory 'https://docs.scipy.org/doc/numpy/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">')"

looks like an issue with the scipy website (https://docs.scipy.org/ - none of the numpy links resolve)

**Comment by IAlibay** [comment]
Possibly linked to https://github.com/scipy/scipy/issues/15545

@tylerjereddy seems to be dealing with it https://github.com/scipy/scipy/issues/15545#issuecomment-1031909411

**Comment by hmacdope** [comment]
Can we safely say its upstream? Or shall we wait for it to be fixed, re-run then merge.

**Comment by IAlibay** [comment]
> Can we safely say its upstream? Or shall we wait for it to be fixed, re-run then merge.

Is this PR in a rush to make it to develop? If not I'd say hold until upstream fixes, we don't have any other simple PRs hanging around to check if it's still failing.

**Comment by IAlibay** [comment]
> > Can we safely say its upstream? Or shall we wait for it to be fixed, re-run then merge.
> 
> Is this PR in a rush to make it to develop? If not I'd say hold until upstream fixes, we don't have any other simple PRs hanging around to check if it's still failing.

**Comment by IAlibay** [comment]
sorry - hit close instead of comment for some reason...

**Comment by hmacdope** [comment]
Nah no rush

**Comment by IAlibay** [comment]
Let's give it a day or so - if Tyler comes back and says it's a long term issue then we can either fix or ignore.

**Comment by tylerjereddy** [comment]
Well, I tried to help fix it upstream, but the intersphinx stuff is tricky. I got a few suggestions, but if we have solid web server/developer folks see: https://github.com/tylerjereddy/htaccess_backup/pull/1

**Comment by tylerjereddy** [comment]
The root of the problem is that SciPy has a new docs theme, but it was never tested in a release deployment, so for a while we just didn't publish the release docs b/c of the damage to intersphinx links, but at this point we either try to fix it or we'll never fix it..

**Comment by IAlibay** [comment]
_should_ have been fixed with #3522, let's see what CI returns like.

**Pull request merged**
