### PR TITLE
Fix: Picklable_file_io.py file doctest errors

### PR DESCRIPTION
**Pull request by HeetVekariya**
Partially address #3925 

Changes made in this Pull Request:
 - Doctest for **picklable_file_io.py** (```package/MDAnalysis/lib/picklable_file_io.py```) file contains errors for this three functions:
1) ```BZ2Picklable``` 
2) ```FileIOPicklable``` 
3) ```GzipPicklable```

These are the errors in each function:
- Import error: Added import for pickle and respective datafiles 
- Printing output unnecessarily: Added ```_``` for temporarily storing the output
- Unwanted indent in Expected output: Removed indentation for correct chceking

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4371.org.readthedocs.build/en/4371/

### CODE REVIEW

**Comment by HeetVekariya** [comment]
@RMeli can please also review this PR.

**Comment by HeetVekariya** [comment]
I will update the change log when reviewed by maintainers.

**Review by hmacdope — APPROVED** [review]
This looks good to me @HeetVekariya

**Comment by HeetVekariya** [comment]
I have updated the change log.

**Comment by HeetVekariya** [comment]
Thank you for review and merge.

**Pull request merged**
