### PR TITLE
switched from coverall to codecov

### LINKED ISSUE #1445: Coveralls always errors "Source not available"
### Expected behaviour

On clicking a file in the Coveralls' report, I should be able to see the lines which are no longer covered due to changes made in the PR. 

### Actual behaviour
Source not available
`The file "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/MDAnalysis/core/selection.py" isn't available on github. Either it's been removed, or the repo root directory needs to be updated.`

### Potential fix
The error says that coveralls tried to look for the source code files at `/home/travis/miniconda/envs/test/lib/python2.7/site-packages/MDAnalysis/`. I think it should look in the cloned folder instead. We need to change the repo root to make this work.

It would be huge help for me if we could fix this. Comparing multiple coverage reports manually is a pain.

#### EDIT

Related issue on coveralls github at https://github.com/lemurheavy/coveralls-public/issues/263

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #1445 

Changes made in this Pull Request:
 - switch from coveralls to codecov
 - enabled MDAnalysis/mdanalysis in codecov https://codecov.io/gh/MDAnalysis/mdanalysis

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Let's see if this works...

**Comment by orbeckst** [comment]
Seems to work and shows coverage for files at https://codecov.io/gh/MDAnalysis/mdanalysis.

In principle it can also merge coverage reports so I will try coverage for both 2.7 and 3.5.

**Comment by richardjgowers** [comment]
Ok I'm not sure why but the travis <-> github link seems to not be working on this PR.  https://travis-ci.com/MDAnalysis/mdanalysis/builds/78658433 the build seems to have passed on travis

**Comment by orbeckst** [comment]
Thanks @richardjgowers . I hope tabs/spaces was the issue because MDAnalysis/pmda#46 did also not want to properly start on travis.

**Comment by orbeckst** [comment]
Unfortunately, codecov only thinks we are 88% covered. With coveralls it was 90%. 

Admittedly, I don't understand the difference  because they both use the coverage report. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by kain88-de** [comment]
Coveralls coverage was actually around 89%. How much coverage does a run on your machine get us?

**Comment by orbeckst** [comment]
On my macOS (without `hole`) I get 88% and with `hole` I get 90%:
```
---------- coverage: platform darwin, python 3.6.5-final-0 -----------
Name                                                                                           Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------------------------------------------------------------------
package/MDAnalysis/KDTree.py                                                                       7      0      0      0   100%
package/MDAnalysis/__init__.py                                                                    37      3      0      0    92%
package/MDAnalysis/analysis/__init__.py                                                            2      0      0      0   100%
package/MDAnalysis/analysis/align.py                                                             237     26     68     10    87%
package/MDAnalysis/analysis/base.py                                                               97      6     32      1    95%
package/MDAnalysis/analysis/contacts.py                                                           83      1     18      1    98%
package/MDAnalysis/analysis/density.py                                                           249     89     60      5    61%
package/MDAnalysis/analysis/diffusionmap.py                                                       63      4     10      2    92%
package/MDAnalysis/analysis/distances.py                                                          38      0      8      1    98%
package/MDAnalysis/analysis/encore/__init__.py                                                    12      0      0      0   100%
package/MDAnalysis/analysis/encore/bootstrap.py                                                   33      0     10      0   100%
package/MDAnalysis/analysis/encore/clustering/ClusterCollection.py                                62     16     31      7    71%
package/MDAnalysis/analysis/encore/clustering/ClusteringMethod.py                                 69      1      8      1    97%
package/MDAnalysis/analysis/encore/clustering/__init__.py                                          4      0      0      0   100%
package/MDAnalysis/analysis/encore/clustering/cluster.py                                          53      1     40      1    98%
package/MDAnalysis/analysis/encore/confdistmatrix.py                                              90     20     38      9    71%
package/MDAnalysis/analysis/encore/covariance.py                                                  66      8     20      8    81%
package/MDAnalysis/analysis/encore/dimensionality_reduction/DimensionalityReductionMethod.py      34      0      2      0   100%
package/MDAnalysis/analysis/encore/dimensionality_reduction/__init__.py                            3      0      0      0   100%
package/MDAnalysis/analysis/encore/dimensionality_reduction/reduce_dimensionality.py              54      1     40      3    96%
package/MDAnalysis/analysis/encore/similarity.py                                                 325     32    168     20    87%
package/MDAnalysis/analysis/encore/utils.py                                                      139     15     70      8    86%
package/MDAnalysis/analysis/gnm.py                                                               130      4     42      2    97%
package/MDAnalysis/analysis/hbonds/__init__.py                                                     4      0      0      0   100%
package/MDAnalysis/analysis/hbonds/hbond_analysis.py                                             344     50    143     18    83%
package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py                                           157      8     52     11    91%
package/MDAnalysis/analysis/hbonds/wbridge_analysis.py                                           255     15    114     22    90%
package/MDAnalysis/analysis/helanal.py                                                           333     37    146     12    84%
package/MDAnalysis/analysis/hole.py                                                              371     70    110     32    78%
package/MDAnalysis/analysis/leaflet.py                                                            87     21     28      6    73%
package/MDAnalysis/analysis/lineardensity.py                                                     107     39     34      2    58%
package/MDAnalysis/analysis/nuclinfo.py                                                          142      7     20      4    92%
package/MDAnalysis/analysis/pca.py                                                                88      7     22      4    90%
package/MDAnalysis/analysis/polymer.py                                                            62      0     13      1    99%
package/MDAnalysis/analysis/psa.py                                                               515    122    168     27    71%
package/MDAnalysis/analysis/rdf.py                                                                95      0     20      0   100%
package/MDAnalysis/analysis/rms.py                                                               155      9     61      5    94%
package/MDAnalysis/analysis/waterdynamics.py                                                     418     56    108     10    85%
package/MDAnalysis/analysis/x3dna.py                                                               7      0      0      0   100%
package/MDAnalysis/authors.py                                                                      1      0      0      0   100%
package/MDAnalysis/auxiliary/XVG.py                                                              113      9     46      5    91%
package/MDAnalysis/auxiliary/__init__.py                                                           6      0      0      0   100%
package/MDAnalysis/auxiliary/base.py                                                             288     30     90     10    88%
package/MDAnalysis/auxiliary/core.py                                                              23      5      6      2    76%
package/MDAnalysis/coordinates/CRD.py                                                             98     14     24      6    84%
package/MDAnalysis/coordinates/DCD.py                                                            141      0     30      4    98%
package/MDAnalysis/coordinates/DLPoly.py                                                         166      2     58      6    96%
package/MDAnalysis/coordinates/DMS.py                                                             68      3     22      5    91%
package/MDAnalysis/coordinates/GMS.py                                                            144     11     56     10    90%
package/MDAnalysis/coordinates/GRO.py                                                            147      7     44      2    95%
package/MDAnalysis/coordinates/GSD.py                                                             44      5      4      1    88%
package/MDAnalysis/coordinates/INPCRD.py                                                          32      2      8      1    92%
package/MDAnalysis/coordinates/LAMMPS.py                                                         262     18     66     10    91%
package/MDAnalysis/coordinates/MMTF.py                                                            25      0      4      0   100%
package/MDAnalysis/coordinates/MOL2.py                                                           119      3     34      5    95%
package/MDAnalysis/coordinates/PDB.py                                                            324     20    118     16    91%
package/MDAnalysis/coordinates/PDBQT.py                                                           93     11     24      5    85%
package/MDAnalysis/coordinates/PQR.py                                                             88      4     26      4    93%
package/MDAnalysis/coordinates/TRJ.py                                                            330     18     98     13    93%
package/MDAnalysis/coordinates/TRR.py                                                             70      0     36      4    96%
package/MDAnalysis/coordinates/TRZ.py                                                            263     33     50     15    83%
package/MDAnalysis/coordinates/TXYZ.py                                                            78     13     12      2    81%
package/MDAnalysis/coordinates/XDR.py                                                            117      0     22      2    99%
package/MDAnalysis/coordinates/XTC.py                                                             41      0      6      1    98%
package/MDAnalysis/coordinates/XYZ.py                                                            155     13     46      6    89%
package/MDAnalysis/coordinates/__init__.py                                                        30      0      0      0   100%
package/MDAnalysis/coordinates/base.py                                                           648     31    219     15    94%
package/MDAnalysis/coordinates/chain.py                                                          199     17     74      9    90%
package/MDAnalysis/coordinates/core.py                                                            15      0      2      0   100%
package/MDAnalysis/coordinates/dummy.py                                                           15      0      0      0   100%
package/MDAnalysis/coordinates/memory.py                                                         107      2     34      4    96%
package/MDAnalysis/coordinates/null.py                                                            11      0      0      0   100%
package/MDAnalysis/core/AtomGroup.py                                                              19      0      0      0   100%
package/MDAnalysis/core/__init__.py                                                               69     14     16      1    71%
package/MDAnalysis/core/_get_readers.py                                                           66      0     26      0   100%
package/MDAnalysis/core/distances.py                                                               6      0      0      0   100%
package/MDAnalysis/core/groups.py                                                                813     13    234      8    98%
package/MDAnalysis/core/log.py                                                                     6      0      0      0   100%
package/MDAnalysis/core/parallel.py                                                                6      6      0      0     0%
package/MDAnalysis/core/qcprot.py                                                                  6      0      0      0   100%
package/MDAnalysis/core/selection.py                                                             636      2    116      3    99%
package/MDAnalysis/core/topology.py                                                              151      0     62      0   100%
package/MDAnalysis/core/topologyattrs.py                                                         665      9    159     11    98%
package/MDAnalysis/core/topologyobjects.py                                                       251      1     84      4    99%
package/MDAnalysis/core/transformations.py                                                         6      0      0      0   100%
package/MDAnalysis/core/units.py                                                                   6      0      0      0   100%
package/MDAnalysis/core/universe.py                                                              367     14    161     10    95%
package/MDAnalysis/core/util.py                                                                    6      0      0      0   100%
package/MDAnalysis/exceptions.py                                                                  11      0      0      0   100%
package/MDAnalysis/lib/NeighborSearch.py                                                          36      4     18      1    80%
package/MDAnalysis/lib/__init__.py                                                                11      0      0      0   100%
package/MDAnalysis/lib/distances.py                                                              237     18    111     15    91%
package/MDAnalysis/lib/formats/__init__.py                                                         4      0      0      0   100%
package/MDAnalysis/lib/log.py                                                                     96      1     26      1    98%
package/MDAnalysis/lib/mdamath.py                                                                 67      9     16      1    86%
package/MDAnalysis/lib/pkdtree.py                                                                 80      3     30      3    95%
package/MDAnalysis/lib/transformations.py                                                        683    100    192     47    81%
package/MDAnalysis/lib/util.py                                                                   532     70    144     16    87%
package/MDAnalysis/selections/__init__.py                                                         17      0      2      1    95%
package/MDAnalysis/selections/base.py                                                             90     12     30      6    82%
package/MDAnalysis/selections/charmm.py                                                           18      0      0      0   100%
package/MDAnalysis/selections/gromacs.py                                                          11      0      2      0   100%
package/MDAnalysis/selections/jmol.py                                                             16      0      0      0   100%
package/MDAnalysis/selections/pymol.py                                                            16      0      0      0   100%
package/MDAnalysis/selections/vmd.py                                                              15      0      2      0   100%
package/MDAnalysis/topology/CRDParser.py                                                          54      4      8      1    92%
package/MDAnalysis/topology/DLPolyParser.py                                                       89      3     20      1    96%
package/MDAnalysis/topology/DMSParser.py                                                          62      5     14      1    92%
package/MDAnalysis/topology/ExtendedPDBParser.py                                                   5      0      0      0   100%
package/MDAnalysis/topology/GMSParser.py                                                          41      1      6      1    96%
package/MDAnalysis/topology/GROParser.py                                                          46      0     12      1    98%
package/MDAnalysis/topology/GSDParser.py                                                          47      5      8      2    87%
package/MDAnalysis/topology/HoomdXMLParser.py                                                     49      5     17      3    88%
package/MDAnalysis/topology/LAMMPSParser.py                                                      236      8     76      3    96%
package/MDAnalysis/topology/MMTFParser.py                                                         90      2     34      2    97%
package/MDAnalysis/topology/MOL2Parser.py                                                         79      2     22      2    96%
package/MDAnalysis/topology/MinimalParser.py                                                      14      0      0      0   100%
package/MDAnalysis/topology/PDBParser.py                                                         145      0     41      0   100%
package/MDAnalysis/topology/PDBQTParser.py                                                        60      0      6      0   100%
package/MDAnalysis/topology/PQRParser.py                                                          93      0     16      1    99%
package/MDAnalysis/topology/PSFParser.py                                                         115     11     28      6    88%
package/MDAnalysis/topology/TOPParser.py                                                         127     10     46      3    90%
package/MDAnalysis/topology/TPRParser.py                                                          58      4     10      4    88%
package/MDAnalysis/topology/TXYZParser.py                                                         31      0      6      0   100%
package/MDAnalysis/topology/XYZParser.py                                                          24      0      2      0   100%
package/MDAnalysis/topology/__init__.py                                                           24      0      0      0   100%
package/MDAnalysis/topology/_elements.py                                                           1      0      0      0   100%
package/MDAnalysis/topology/base.py                                                               43      1     15      1    97%
package/MDAnalysis/topology/core.py                                                               10      0      0      0   100%
package/MDAnalysis/topology/guessers.py                                                          107      1     61      1    99%
package/MDAnalysis/topology/tables.py                                                             18      0      4      0   100%
package/MDAnalysis/topology/tpr/__init__.py                                                        4      0      0      0   100%
package/MDAnalysis/topology/tpr/obj.py                                                            60      0     22      0   100%
package/MDAnalysis/topology/tpr/setting.py                                                        18      0      0      0   100%
package/MDAnalysis/topology/tpr/utils.py                                                         481     96    204     32    79%
package/MDAnalysis/transformations/__init__.py                                                     4      0      0      0   100%
package/MDAnalysis/transformations/rotate.py                                                      33      0     14      0   100%
package/MDAnalysis/transformations/translate.py                                                   38      0     14      0   100%
package/MDAnalysis/units.py                                                                       32      0      6      0   100%
package/MDAnalysis/version.py                                                                      2      0      0      0   100%
package/MDAnalysis/visualization/__init__.py                                                       4      0      0      0   100%
package/MDAnalysis/visualization/streamlines.py                                                  109      8     32      6    90%
package/MDAnalysis/visualization/streamlines_3D.py                                               186      8     50      3    95%
--------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                          16946   1389   5188    598    90%

```

**Comment by orbeckst** [comment]
I [uploaded the coverage](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) via
```
bash <(curl -s https://codecov.io/bash) -t SECRET_TOKEN
```
Maybe this can work as the basis for future comparisons.

**Comment by kain88-de** [comment]
codecov thinks the hole analysis module isn't covered almost at all. This would explain the difference. I do not know which file it took for the coverage report.

**Pull request merged**
