### PR TITLE
Always use new division

### PR DESCRIPTION
**Pull request by kain88-de**
Changes made in this Pull Request:
 - always use py3 style division

PR Checklist
------------
 - [x] Tests?
 ~~- [ ] Docs?~~
 ~~- [ ] CHANGELOG updated?~~
 ~~- [ ] Issue raised/referenced?~~

### CODE REVIEW

**Comment by jbarnoud** [comment]
I do not see any problem with this PR. If you do not mind, I would be more comfortable merging it after the release, though.

**Comment by kain88-de** [comment]
Have a look at the target milestone ;)

**Comment by jbarnoud** [comment]
ohhh ^^

**Comment by kain88-de** [comment]
@jbarnoud good to merge now?

**Comment by jbarnoud** [comment]
I guess we can break things again :D

**Comment by richardjgowers** [comment]
Oh dear, we just released 16 and we're already busy breaking things anew

**Comment by kain88-de** [comment]
Yeah the lint PR's are funny. They will likely generate merge conflicts for all PR's we have open right now.

**Comment by richardjgowers** [comment]
Probably best to get them done now (at the start of a release cycle) when there's arguably fewer PRs open.

**Pull request merged**
