### PR TITLE
Updated pytests

### LINKED ISSUE #2618: Pytest 5.4.0 requires parametrize arguments to be explicitly declared
## Expected behavior ##

Tests pass regardless of `pytest` version.

## Actual behavior ##

Tests [do not pass with recently released pytest 5.4.0](https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/297586269#L1709-L1721).

```
==================================== ERRORS ====================================
______ ERROR collecting MDAnalysisTests/coordinates/test_timestep_api.py _______
In function "test_frame":
Parameter "topology" should be declared explicitly via indirect or in function itself
_______ ERROR collecting MDAnalysisTests/core/test_group_traj_access.py ________
In function "test_atomgroup_positions_access":
Parameter "pos" should be declared explicitly via indirect or in function itself
__________ ERROR collecting MDAnalysisTests/formats/test_libmdaxdr.py __________
In function "test_seek":
Parameter "fname" should be declared explicitly via indirect or in function itself
__________ ERROR collecting MDAnalysisTests/formats/test_libmdaxdr.py __________
In function "test_set_offsets":
Parameter "xdrfile" should be declared explicitly via indirect or in function itself
```

A [new feature](https://docs.pytest.org/en/latest/changelog.html#features) of 5.4.0:

>  Now all arguments to @pytest.mark.parametrize need to be explicitly declared in the function signature or via indirect. Previously it was possible to omit an argument if a fixture with the same name existed, which was just an accident of implementation and was not meant to be a part of the API.

A quick look at ``test_timestep_api.py`` shows that ``TestBaseTimestepInterface`` (which contains ``test_frame``) has parametrized arguments, but does not declare them in `__init__`, and I expect the other errored functions are similar.

## Solution

I think explicitly declaring these arguments is manageable and a more long-term solution than pinning the pytest version.

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #2618

Changes made in this Pull Request:
 - Explicitly declared fixtures

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by lilyminium** [comment]
Travis doesn't seem to be installing pytest 5.4.0 anymore but I assume at some point environments will move on to it.

**Comment by orbeckst** [comment]
I assume that's ready to me merged but I didn't follow the discussion so please go ahead, I think either @IAlibay or @lilyminium can do it.

**Comment by IAlibay** [comment]
@lilyminium let me know if you want to make any further changes in light of pytest 3.4.1, otherwise I can go ahead with the merge.

**Comment by lilyminium** [comment]
@IAlibay I don't have any further changes -- I think might as well merge because 
* explicitly declaring these can't *hurt*
* as you said, they consider it "an unintended/surprising behavior" so it might just get deprecated and removed more slowly in the future

Thank you!

**Pull request merged**
