### PR TITLE
enabled coverage for cython

### LINKED ISSUE #443: add cython code to coverage report
Cython has recently gained support for coverage our of box [1]. It might be worth to have that code covered as well since we aim to replace all CPython-extensions with Cython in the long run.

[1] http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #443

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by tylerjereddy** [comment]
I think @stefanv and the scikit-image team are quite interested in doing this for their library as well so cc'ing them here.

**Comment by richardjgowers** [comment]
@tylerjereddy I'm just seeing if it's as easy as these two lines... if it is I'll bring them in :)

**Comment by richardjgowers** [comment]
Hmm this is weird.  When I run locally, the ascii table printout doesn't have any .pyx files, but if I look inside the `.coverage` file produced there **are** entries for .pyx files, so it's sort of working...

**Comment by orbeckst** [comment]
@Fenil3510 for your GSoC project proposal "Cythonizing ASCII Readers/Parser", the discussion here should be relevant.

**Comment by Fenil3510** [comment]
I was researching on adding cython coverage, the codecov report here still doesn't track `.pyx` files. I ran the same locally with some minor changes(hacky) and the report covers `.pyx` files 

Here's the HTML output
image

I have opened a separate PR for it as I will be working on this issue for my project.

**Comment by Fenil3510** [comment]
This PR can be closed as #2255 solves it.

**Pull request closed without merging**
