### PR TITLE
Get OSX and different Numpy builds running

### PR DESCRIPTION
**Pull request by kain88-de**
I want to check if I can get the osx and numpy builds running

### CODE REVIEW

**Comment by kain88-de** [comment]
@richardjgowers the coma separation was correct. That is the documented like this in the CI helper scripts from astropy.

https://github.com/astropy/ci-helpers/blob/master/travis/setup_dependencies_common.sh#L20

**Comment by richardjgowers** [comment]
So from the logs:
```WARNING: The remote server could not find the noarch directory for the requested

channel with url: https://conda.anaconda.org/conda-forge,/noarch```
```
It looks like the comma (,) is getting included there which is wrong

**Comment by richardjgowers** [comment]
@kain88-de looks like file handles can't be made - iirc osx has a different open file limit by default, but there's a command line thingy to change this..

https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Comment by richardjgowers** [comment]
Looks like it might be working.  So just to make sure, the osx build is a full build (ie with analysis tests)?

**Comment by kain88-de** [comment]
Yes the osx build has all dependencies. And yeah the careful single process test just passed. Let's see if the 2 process jobs runs smoothly now.

Also should we have tests against the development version or pre release version of numpy?

**Comment by richardjgowers** [comment]
I guess the most recent version of numpy which is considered stable enough for all users, so pre-release?

Should we also set our numpy version to be the oldest we officially support (1.5) to make sure we're remaining compatible with that?

**Comment by kain88-de** [comment]
Let's see what we get for the numpy builds.

**Comment by kain88-de** [comment]
> I guess the most recent version of numpy which is considered stable enough for all users, so pre-release?

This is not about users. Using the development version would allow us to catch possible regressions in numpy before it is released and open an issue about it.

**Comment by kain88-de** [comment]
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/219212229

I think we need to bump up our minimum numpy version.

**Comment by richardjgowers** [comment]
So if it's not a user thing but a dev warning, we should probably add the next numpy build as an allowed failure then.

**Comment by kain88-de** [comment]
Version 1.9.3 seems good so far with respect to errors.  I don't get immediate failures.

**Comment by richardjgowers** [comment]
The differences with 1.9.3 seemed more like regression tests with too high precision failing rather than significant differences.

**Comment by kain88-de** [comment]
Yeah they 1.9.3 failures looks like the encore tests failing. I'm running the 1.8.2 tests again to the end to see how much fails. But this really seems like we have to update our numpy requirement. The 1.5.1 version directly segfaulted.

**Comment by kain88-de** [comment]
Ok 1.8.3 has weird reference errors. I would suggest to remove the numpy tests from this or and do them separate.

**Comment by kain88-de** [comment]
@richardjgowers feel free to squash & merge when it passes. I think it's better to treat the numpy issue in a separate PR.

**Pull request merged**
