### PR TITLE
Fixed NSGrid

### LINKED ISSUE #2919: Wrong results from `capped_distance()` with "nsgrid" search and atom in the center of the box
## Expected behavior ##

`capped_distance()` function should always give the correct result regardless of the employed search method and atomic positions.
In the example below the expected result for cutoff=3.2 is:
* cutoff=3.2
bruteforce: 2497 pairs
pkdtree: 2497 pairs
nsgrid: 2497 pairs

## Actual behavior ##

When one of the atoms of the reference group is positioned exactly in the center of the box, `capped_distance()` sometimes returns erroneous results for "nsgrid" search method.

* cutoff=2.8
bruteforce: 1115 pairs
pkdtree: 1115 pairs
nsgrid: 1115 pairs
* cutoff=3.2
bruteforce: 2497 pairs
pkdtree: 2497 pairs
nsgrid: 2510 pairs

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.lib.distances import capped_distance
from MDAnalysis.transformations.translate import center_in_box
from MDAnalysis.tests.datafiles import PDB_xvf

u = mda.Universe(PDB_xvf)
ag = u.select_atoms('index 0')
u.trajectory.ts = center_in_box(ag)(u.trajectory.ts)

box = u.dimensions
reference = u.select_atoms('protein')
configuration = u.select_atoms('not protein')

for cutoff in [2.8, 3.2]:
    print(f"* cutoff={cutoff}")
    for method in ['bruteforce', 'pkdtree', 'nsgrid']:
        pairs, distances = capped_distance(
            reference.positions,
            configuration.positions,
            max_cutoff=cutoff,
            box=box,
            method=method,
            return_distances=True,
            )
        print(f"{method}: {len(pairs)} pairs")

```

## Current version of MDAnalysis ##

- MDAnalysis 1.0.0 (conda-forge)
- Python 3.7.7
- Ubuntu 18.04.5 LTS

### PR DESCRIPTION
**Pull request by richardjgowers**
Rewrote lib.nsgrid module

Fixes #2919 #2345 #2229

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by zemanj** [comment]
@richardjgowers does this PR supersede #2937?
Sorry for the long radio silence from my side, I'll review ASAP.

**Comment by richardjgowers** [comment]
@zemanj yes.  This is a rebase of that PR onto master instead of develop, so it gets released sooner.  If you could review soon that would be great.

**Comment by IAlibay** [comment]
@richardjgowers I went ahead and reverted the temporary removal of nsgrid from test_distances, hopefully that should fix the failures that were happening.

**Comment by IAlibay** [comment]
=.= I have no idea why it's now suddenly picking up numpy 1.20... we didn't have these issues up until now. Technically all the failures we are saying _should_ get fixed by #3139, I guess the options here are a) pin CI temporarily, b) merge the code in #3139 into this branch (although it might end up making it really hard to review the changes made here).

**Review by lilyminium — APPROVED** [review]
I shallowly skimmed the pyx file so have no real comments on that -- I'm going to approve this based on the tests directly addressing NSGrid issues.

**Comment by zemanj** [comment]
@lilyminium It turns out that "shallowly skimming the pyx file" was not a great idea at all.
I know I should have reviewed the code already weeks ago but my free time is very limited these days.
Anyway, we need to be extremely careful with code that is of such fundamental importance for the package as this one, especially since this PR was for the master branch.

Even though the code is now *much* nicer than before, I discovered the following problems:
* The function `coordintoprimarycell()` does not guarantee that atoms will really lie within the box and should be replaced by `_triclinic_pbc()` from `calc_distances.h`.
* The test for issue #2345 does not reproduce the respective system properly because it is stored as a pdb file (which lacks the necessary precision).
* The code segfaults if box dimensions are large and the cutoff comparatively small.
* It is relatively slow for low densities (too few atoms per cell).

Issues (and PR for the first two points) incoming.

**Comment by IAlibay** [comment]
Thanks for looking into this @zemanj!

> Anyway, we need to be extremely careful with code that is of such fundamental importance for the package as this one, especially since this PR was for the master branch.

I agree. To the remaining @MDAnalysis/coredevs given that tomorrow is meant to be the code freeze for 1.1.0, I propose that we hold off on doing so until everything (at least non-performance related) is fixed for NSGrid.

**Comment by lilyminium** [comment]
> @lilyminium It turns out that "shallowly skimming the pyx file" was not a great idea at all.
I know I should have reviewed the code already weeks ago but my free time is very limited these days.
Anyway, we need to be extremely careful with code that is of such fundamental importance for the package as this one, especially since this PR was for the master branch.

Thanks a lot for checking the code and discovering those problems, @zemanj. I shouldn't have reviewed when pressed for time. Although to be honest, I doubt I would have discovered the issues anyway due to my unfamiliarity with this part of the code and the possible failure cases 😬

**Pull request merged**
