### PR TITLE
Updated core/selection.py to include amber N- and C-termini resnames …

### LINKED ISSUE #1702: Amber nomenclature in "protein" selection
### Expected behaviour

- load a pdb with Amber force-field specific residue naming (e.g. CGLY for c-terminal glycine residue)
- selection of "protein" atoms should include the CGLY protein

### Actual behaviour

- pdb including CGLY is correctly loaded into the universe but not in the atom group when selecting for "protein"

Testfile (rename to test.pdb):
[test.txt](https://github.com/MDAnalysis/mdanalysis/files/1458193/test.txt)

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe('test.pdb')
print(u.residues.resnames)
u_prot = u.select_atoms("protein")
print(u_prot.residues.resnames)
```

### PR DESCRIPTION
**Pull request by kain88-de**
resubmission of #1704 
fixes #1702

I'm interested if the errors still come up now.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
@orbeckst do you mind giving this a try on your macs? I don't want to merge this with the consistent failure even though I don't see how it is connected to the changes. It looks like an internal failure for pytest.

**Comment by kain88-de** [comment]
Removing the test fixes the error. Maybe renaming it or rewriting it a bit might help.

**Comment by orbeckst** [comment]
I'll try tomorrow. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
I tried in a fresh anaconda3 venv with python 3.5 (not 3.6 as on Travis – can change if necessary). The output from
```
pytest -n 4 MDAnalysisTests/ 2>&1 | tee TEST.txt
```
is attached as [TEST.txt](https://github.com/MDAnalysis/mdanalysis/files/1488674/TEST.txt). Final result:

**1 failed, 5934 passed, 24 skipped, 1 xfailed, 12699 warnings in 345.26 seconds**

The failing test is **`test_search[b9-qns9]`**.

Below are the "highlights".


```
============================= test session starts ==============================
platform darwin -- Python 3.5.4, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: /Volumes/Data/oliver/Biop/Projects/Methods/MDAnalysis/mdanalysis/testsuite, inifile: setup.cfg
plugins: xdist-1.20.1, forked-0.2, hypothesis-3.38.0
gw0 I / gw1 I / gw2 I / gw3 I
gw0 [5960] / gw1 [5960] / gw2 [5960] / gw3 [5960]

scheduling tests via LoadScheduling

.......... (many) [snip]

_____________________________ test_search[b9-qns9] _____________________________
[gw2] darwin -- Python 3.5.4 /Users/oliver/anaconda3/envs/mdatest3/bin/python

b = array([ 10.,  10.,  10.,  45.,  60.,  90.], dtype=float32)
qns = (([-1.9, 4.2, 0.2], [2.1, -3.1, 0.1]), ([0.2, 0.2, 0.2], [2.1, 2.1, 0.3], [1.1, -1.1, 1.1]))

    @pytest.mark.parametrize('b, qns', doublets)
    def test_search(b, qns):
        """
        Test finding neighbors for a given query vector and type of box.

        Parameters
        ----------
        b : list
            MDAnalysis dimensions like list
        qns : tuple
            a query point and a list of expected neighbors.
        """
        b = np.array(b, dtype=np.float32)
        q = transform_StoR(np.array(qns[0], dtype=np.float32), b)
        # Setting up the periodic tree
        tree = PeriodicKDTree(b)
        coords = transform_StoR(f_dataset, b)
        tree.set_coords(coords)  # Input real space coordinates
        # Carry out the search and retrieve results
        tree.search(q, radius)
        indices = tree.get_indices()
        if indices:
            expected_neighbors = np.sort(expected_neighbors, axis=0)
        else:
            expected_neighbors = list()
>       assert_equal(found_neighbors, expected_neighbors)
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 11.111111111111114%)
E        x: array([[  3.      ,  -3.221825,   1.      ],
E              [ 16.5     ,   3.414214,   1.5     ],
E              [ 22.5     ,  23.121321,   5.5     ]], dtype=float32)
E        y: array([[  3.      ,  -3.221825,   1.      ],
E              [ 16.5     ,   3.414214,   1.5     ],
E              [ 22.5     ,  23.121321,   5.5     ]], dtype=float32)

MDAnalysisTests/lib/test_pkdtree.py:210: AssertionError
=============================== warnings summary ===============================
MDAnalysisTests/coordinates/test_pdb.py::TestWriterAlignments
  cannot collect test class 'TestWriterAlignments' because it has a __init__ constructor
  cannot collect test class 'TestWriterAlignments' because it has a __init__ constructor
  cannot collect test class 'TestWriterAlignments' because it has a __init__ constructor
  cannot collect test class 'TestWriterAlignments' because it has a __init__ constructor

[snip]

1 failed, 5934 passed, 24 skipped, 1 xfailed, 12699 warnings in 345.26 seconds 
```

I also got in there somewhere:
```
Exception ignored in: <bound method ReaderBase.__del__ of <XYZReader bogus/path/mini.xyz with 3 frames of 8 atoms>>
Traceback (most recent call last):
  File "/Users/oliver/anaconda3/envs/mdatest3/lib/python3.5/site-packages/MDAnalysis/coordinates/base.py", line 1780, in __del__
    self.close()
  File "/Users/oliver/anaconda3/envs/mdatest3/lib/python3.5/site-packages/MDAnalysis/coordinates/XYZ.py", line 427, in close
    self.xyzfile.close()
  File "/Users/oliver/anaconda3/envs/mdatest3/lib/python3.5/site-packages/MDAnalysis/lib/util.py", line 703, in close
    self.reset()
  File "/Users/oliver/anaconda3/envs/mdatest3/lib/python3.5/site-packages/MDAnalysis/lib/util.py", line 645, in reset
    self.stream.seek(0)  # typical file objects
ValueError: I/O operation on closed file
```

**Comment by kain88-de** [comment]
ok when I don't use parametrize the tests pass

**Comment by orbeckst** [comment]
Weird. Then let's do the non-parametrized version and add a comment to the tests.

Are we going to work on this PR or on #1704 ? (If it is this one then please *manually* squash your commits because squashing everything through GitHub will loose @sobuelow 's authorship information on the main commit.)

**Comment by orbeckst** [comment]
(Let me know if you need a review somewhere.)

**Comment by richardjgowers** [comment]
This just seems like we're treating the symptoms and not the actual problem here.  The parametrised tests **should** work.  IIRC MacOS has a smaller open file handle limit, so maybe these tests (despite using make_Universe) have tipped over the limit again?

**Comment by kain88-de** [comment]
Well, then why does the python 2.7 test pass? Anyway, a try can't hurt. But I doubt this is related to open files.

**Comment by richardjgowers** [comment]
The newly failing tests are TRR/XTC which is completely unrelated code to here.  So it looks like adding more (of any) tests seems to break some sort of limit.  The workaround here of not parametrising the tests just pushes the problem into a PR next week.  I'd just merge the tests as-is (with param) and open an issue to fix the problem with travis.

**Comment by kain88-de** [comment]
@richardjgowers. Please adopt the PR as you see fit then. I’m not sure what exactly you want to change.

**Pull request closed without merging**
