### PR TITLE
removed * and added explicit imports

### LINKED ISSUE #766: Remove usage of import * from tests
This is a bug causing #765 

```
find . -name '*.py' -exec grep 'testing import \*' {} +
./coordinates/test_reader_api.py:from numpy.testing import *
./coordinates/test_mol2.py:from numpy.testing import *
./coordinates/test_pdbqt.py:from numpy.testing import *
./test_units.py:from numpy.testing import *
./test_nuclinfo.py:from numpy.testing import *
./test_velocities_forces.py:from numpy.testing import *
```

All the uses of `from numpy.testing import *` (listed above) need to be replaced by explicit imports.  Should be an easy fix to get the hand of pull requests etc

### PR DESCRIPTION
**Pull request by abhinavgupta94**
Fixes #766 

Changes made in this Pull Request:
 -  removed * and added explicit imports

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by abhinavgupta94** [comment]
I haven't added any tests and updated the CHANGELOG as I thought they are not relevant in this issue. Should I add those too?

**Comment by jbarnoud** [comment]
There is indeed no new test to write. But the existing ones should pass, which is not the case now as you missed some imports. Waiting for Travis to run the tests can be quite long, you can run the tests locally to detect the issues faster.

The change is small to appear in the CHANGELOG.

**Comment by jbarnoud** [comment]
Also, you should rebase against develop rather than do a merge. It makes the history easier to follow. Once you are done fixing your PR, could you rebase your commits into a single one please?

**Comment by abhinavgupta94** [comment]
Got it. Will do it right away.

**Comment by abhinavgupta94** [comment]
Ah! I had actually rebased my repo (issue-766) to master since the version this error was 0.14.0 and so didn't use the develop version. Should I do open a new PR on master branch?

**Comment by orbeckst** [comment]
Either rebase against develop or open a fresh PR based on the current develop (and `git cherry-pick` your commits into your new branch).

**Comment by orbeckst** [comment]
By the way, name your issue branches like *issue-766-no-import-star* (or similar):  add a little descriptive text after the issue number to make it easier for people to understand the branch without having to go to GitHub.

**Pull request closed without merging**
