### PR TITLE
I just removed a single colon and added a double colon.

### PR DESCRIPTION
**Pull request by suresh33661**
…ough an error.

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
:books: Documentation preview :books:: https://mdanalysis--4250.org.readthedocs.build/en/4250/

### CODE REVIEW

**Comment by suresh33661** [comment]
benchmarks/asv.conf.json at this file in line 23  I changed 'asv'  to "asv".

**Comment by IAlibay** [comment]
> benchmarks/asv.conf.json at this file in line 23  I changed 'asv'  to "asv".

I think I might be missing something important here. Could you give some context on why this is a necessary change?

**Review by IAlibay — CHANGES_REQUESTED** [review]
Blocking for context

**Comment by suresh33661** [comment]
> > benchmarks/asv.conf.json at this file in line 23  I changed 'asv'  to "asv".
> 
> I think I might be missing something important here. Could you give some context on why this is a necessary change?
asv.conf.json  for .json files we use "asv" not 'asv' it througs an error in the IDE
double quotes.

**Comment by hmacdope** [comment]
Sadly @suresh33661 this is not a good enough reason to change the file, the functionality works as is. IDEs are not the ground truth of how code should be written, merely a suggestion. As such I am going to close this PR, let me know if you want further explanation :)

**Pull request closed without merging**
