### PR TITLE
fix for simple rms.rmsd() (Issue #822)

### LINKED ISSUE #822: simple rms.rmsd() gives wrong answer
`rms.rmsd()` without superposition is broken. 

#814 requires this issue to be resolved.

### Expected behaviour
```python
import MDAnalysis as mda; from MDAnalysis.tests.datafiles import PSF, DCD
from MDAnalysis.analysis.rms import rmsd
u = mda.Universe(PSF, DCD)
p = u.select_atoms("protein")
A, B = p.coordinates(u.trajectory[0]),  p.coordinates(u.trajectory[-1])

print(rmsd(A, B) > rmsd(A, B, center=True, superposition=True))
```

should print `True` because the superimposed RMSD is by construction the *smallest* RMSD.

### Actual behaviour

Gives `False`, in fact, the optimal RMSD is 6.929082950080235 while `rmsd(A, B)` gives 4.0152196124068364.

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

'0.14.1-dev0'

### Problem
```python
return np.sqrt(np.sum((a - b) ** 2) / a.size)
```
should be `len(a)`.

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #822 

Changes made in this Pull Request:
 - one line change in `MDAnalysis.analysis.rms.rmsd()`

PR Checklist
------------
 - [x] Tests?
 -  Docs? -- n/a
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
@kain88-de have a look. I need to update the tests.

**Comment by orbeckst** [comment]
(Anyone else is more than welcome to continue... have to board a plane now ;-) ).

**Comment by kain88-de** [comment]
@orbeckst I fixed the tests and added some new tests based on you comments in the issue

**Comment by orbeckst** [comment]
Busy today/tomorrow so please do whatever needs doing. Thanks!

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Apr 12, 2016 um 8:17 schrieb kain88-de <notifications@github.com>:

**Comment by kain88-de** [comment]
@jdetle since you want to have a look at the RMSD function soon anyway you can also check if this fixes the issue and if the new tests are correct.

**Comment by jdetle** [comment]
@kain88-de @orbeckst I will have a go at it as soon as I'm finished with some other work. Did some work on RMSD weighting last night, I'll have a PR for some tests up tonight.

**Comment by jdetle** [comment]
@kain88-de I forgot to mention that I already figured out last night that this doesnt fix the weighting issue.  In the current code there exists no mention of returning an rmsd with weighting when weights is not none.

**Comment by kain88-de** [comment]
@jdetle yes this PR doesn't address the weights. We can solve the weights in a separate PR. I just thought you could have a look over the current code and tests since you spend some time with RMSDs recently to fix the weights.

**Comment by jdetle** [comment]
Will do.

**Comment by jdetle** [comment]
Sorry that I'm late to the party, but how did these tests pass? 

`import numpy as np
shape = (5, 3)
shape = (5, 3)
one = np.arange(np.prod(shape)).reshape(shape)
two = np.arange(np.prod(shape)).reshape(shape) + 1

#print one, two
inner = ((one - two) ** 2)
innerSum = np.sum(inner)
N = two.shape[0]
insideRoot = innerSum/N

print(inner)
print(innerSum)
print(N)
print(insideRoot)
print(np.sqrt(insideRoot))`

`N = b.shape[0]` means that `np.sqrt( x / N )` doesn't divide by the right number of coordinates, (in this case 5 instead of 3*5. This causes a failure on my machine in no_center and test_list in test_rms.py

**Comment by kain88-de** [comment]
You recreated the old tests that fail

**Comment by jdetle** [comment]
Did I? Nowhere in the diffs do I see the new tests expecting sqrt(3) instead of 1.

**Comment by jdetle** [comment]
Ah I see now, thanks.

**Comment by kain88-de** [comment]
they do differ by one now. The distance is one unit vector. Each component is  1/sqrt(3) and the length of that vector is 1.

each atom is now one unit appart from each other spread in a line going from (0,0,0) to (5/sqrt(3). 5/sqrt(3). 5/sqrt(3)).

**Comment by jdetle** [comment]
Ah okay, that makes sense.

**Pull request merged**
