### PR TITLE
WIP: various little forgotten doc updates

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes: small things that were forgotten or are too small for a "real" PR

Changes made in this Pull Request:
 - updated README (should have been part of PR #1462

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Don't bother merging this until we get close to a release. Use it to fix up tiny little things in the docs when you come across them.

**Comment by orbeckst** [comment]
The doc build is failing https://travis-ci.org/MDAnalysis/mdanalysis/jobs/252393466

I _think_ it is because there are no changes to be submitted 

> nothing to commit, working directory clean

and `git commit` returns error status **1**, which is seen as a failure in travis. Should we modify the `maintainer/deploy_docs.sh` script to ignore the return status of `git commit`?

**Comment by orbeckst** [comment]
PS: should have added a `[ci skip]` to the commit in the first place.

**Comment by kain88-de** [comment]
Maybe the deploy script should handle these errors more gracefully. Or we inspect the git commit for [skip ci] to stop it running then.

**Comment by orbeckst** [comment]
The `[skip ci]` would prevent  Travis from even running, so that would have been fine. 

I am not sure how we can tell that `git commit` failed because of no added files (to be ignored) or because of other errors (to be flagged as a failure). The script itself is set up to immediately die if any command exits with non-zero (`set -o errexit`) so it would need to be something like
```bash
git commit || { git status --long | grep 'nothing added to commit'  >/dev/null; }
```
which will check after failure if we had nothing to commit and if so, return an ok (0). But doing it in the way I sketched out is pretty fragile because it relies on informational output from `git status`. Perhaps there's a safer way to get this information.

**Comment by kain88-de** [comment]
I thought I added it to the merge commit

**Pull request merged**
