### PR TITLE
Remove planned deprecations

### LINKED ISSUE #1276: remove deprecated code in analysis.contacts
`analysis.contacts` contains lots of old code that is scheduled for removal.

- [ ] remove deprecated functions in package/MDAnalysis/analysis/contacts.py 
- [x] check that all references to the remove functions are removed from the docs
- [ ] add CHANGELOG entry

### PR DESCRIPTION
**Pull request by kain88-de**
- [x] Fixes #1276
- [x] remove deprecated in HydrogenBondAnalysis

Changes made in this Pull Request:
 - remove old analysis class

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

EDITS
- 2017-05-15 added HydrogenBondAnalysis to TODO list — @orbeckst

### CODE REVIEW

**Comment by richardjgowers** [comment]
This is fine, but would lock the next released version into being 0.17, which I guess is ok.  We could leave this hanging and only merge it once we know that the next release is 0.17?

**Comment by kain88-de** [comment]
Yes this can be left for some time. I assume this PR should hold up fine with changes.

**Comment by richardjgowers** [comment]
This puts us perilously close to finally getting back to 90% coverage!

**Comment by kain88-de** [comment]
Removing almost 1000 lines of code. I think 90% coverage looks pretty pretty close now.

**Comment by richardjgowers** [comment]
Looks good, but can't go in 0.16.x

**Comment by kain88-de** [comment]
@richardjgowers man you are to fast. I barely can keep up rebasing these.

**Comment by richardjgowers** [comment]
@kain88-de MERGE ALL THE THINGS

**Pull request merged**
