### PR TITLE
BUG: Writing a PDB file from an ag with invalid kwargs

### LINKED ISSUE #877: writing files from AtomGroup fails cryptically if wrong kwargs are supplied
### Expected behaviour

Writing a AtomGroup to a file with `atoms.write("foo.pdb", bogus="whatever")` should either write the file or provide an error message that I supplied kwargs ('bogus') that are not appropriate for the writer.
### Actual behaviour

Instead I get the confusing error message

```
ValueError: No writer found for format: foo.pdb
```
### Code to reproduce the behaviour

``` python
>>> import MDAnalysis as mda
>>> from MDAnalysisTests.datafiles import GRO
>>> u = mda.Universe(GRO)
>>> u.atoms.write("foo.pdb", bogus="something something complete")
```

This will raise `ValueError: No writer found for format: foo.pdb`.
### Diagnosis

When detecting coordinate writer we use the following 

``` python
        # From the following blocks, one must pass.
        # Both can't pass as the extensions don't overlap.
        try:
            writer = MDAnalysis.coordinates.writer(filename, **kwargs)
        except TypeError:
            # might be selections format
            coords = False
        else:
            coords = True
```

But if the coordinate writer gets a `kwarg` it does not like then it raises a `TypeError`, too:

``` python
>>> mda.coordinates.writer('foo.pdb', bogus="something")
TypeError: __init__() got an unexpected keyword argument 'remark'
```

and _this_ `TypeError` is wrongly interpreted up to mean "there is no format". 
### Currently version of MDAnalysis:

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.15.0 (but also in develop).

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #877 

Changes made in this Pull Request:
 - I wrote a unit test and patched the issue linked above. Note that the original author reported this as a general flaw of atomgroup writing, but it is isolated to PDB format as far as I can tell (not reproducible with gro or xyz formats)

PR Checklist
------------
 - [x] Tests?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Just to clarify -- with formats other than PDB, the default appears to be silently writing the file. For PDB, the default will be to raise an appropriate exception.

**Comment by tylerjereddy** [comment]
If you're sure that would work, do feel free to change the branch appropriately. I found the Error handling to be a bit confusing and was happy to get anything that worked!

Another question might be why PDB writing is a special snowflake, and if we'd really want to have different behaviours for handling invalid kwargs for different output filetypes.

**Comment by richardjgowers** [comment]
Yeah ok keep the branch alive and I'll have a go.

**Comment by tylerjereddy** [comment]
Looks like there's some discussion to be had beforehand anyway.

**Comment by orbeckst** [comment]
> Looks like there's some discussion to be had beforehand anyway.

Yes, that's why I added https://github.com/MDAnalysis/mdanalysis/issues/877#issuecomment-265784830 – I assume I know your opinion @tylerjereddy but can you just add it for the record to #877 ?

**Comment by richardjgowers** [comment]
Ok this should be good to go, the logic in the code first tries to get an appropriate writer, then uses it, so error messages don't get squashed and confused

**Pull request merged**
