### PR TITLE
Renamed variable `asel` 

### LINKED ISSUE #3911: Change name of `asel` in timeseries to something more comprehensible.
I know we're just doing the same as what memoryreader does, but it just struck me that `asel` is such a weird parameter name for an atomgroup. Not much we can do here, but if I'm not the only one maybe we can consider changing this for 3.0 (in a different PR, let's get this merged!).

_Originally posted by @IAlibay in https://github.com/MDAnalysis/mdanalysis/pull/3890#discussion_r1014879026_
     

I agree with @IAlibay that the name `asel` is a little confusing and could do with a change in 3.0. 
leave your opinions below. 

Will require a deprecation warning first if we go ahead.

### PR DESCRIPTION
**Pull request by HunterZ17**
Fixes #3911 

Changes made in this Pull Request:
 - renamed variable `asel` to `ag_select`

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

----
:books: Documentation preview :books:: https://readthedocs-preview--4077.org.readthedocs.build/en/4077/

### CODE REVIEW

**Comment by hmacdope** [comment]
@MDAnalysis/coredevs what is the go here? I assume we may need to deprecate first?

**Comment by IAlibay** [comment]
> @MDAnalysis/coredevs what is the go here? I assume we may need to deprecate first?

Yeah, as discussed in the original issue, we can't remove this until 3.0, so we need to deprecate the keyword for now, allow both options, and then remove in 3.0.

**Comment by hmacdope** [comment]
@HunterZ17 do you plan on working on this in the near future? If not might be best to close.

**Comment by IAlibay** [comment]
> @HunterZ17 do you plan on working on this in the near future? If not might be best to close.

Closing due to lack of activity.

**Pull request closed without merging**
