### PR TITLE
Cython modules should have same name as source

### PR DESCRIPTION
**Pull request by kain88-de**
This seems to be an implicit assumption in cython. With this the import
errors about non existing init-functions in the cython modules is gone.

I removed the explicit LICENSE file for pyqcprot but the license is still stated 
exactly the same in the pyx file, So that shouldn't be an issue. Does anyone have
information about that?

### CODE REVIEW

**Comment by kain88-de** [comment]
yeah tests are running along just fine.

**Comment by orbeckst** [comment]
Do you have any idea why this worked before? Is it the explicit use of `cythonize`?

**Re pyqcprot:** It's fine to remove the examples. The content of the README (in particular the citations) are in the MDA docs so it's ok to remove it. But I'd like to keep the explicit LICENSE file intact. If you *have* to remove it then append it to the top-level LICENSE with a note that this is the license for pyqcprot and add it verbatim as a comment to the top of the pyx file (if it isn't there already). The LICENSE says:

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this list of 
      conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this list 
      of conditions and the following disclaimer in the documentation and/or other materials 
      provided with the distribution.
* Neither the name of the <ORGANIZATION> nor the names of its contributors may be used to 
      endorse or promote products derived from this software without specific prior written 
      permission.


Also add a link to @synapticarbors original repository https://github.com/synapticarbors/pyqcprot (in case it's not in the pyx file).

(Unless Josh has anything else to say.)

**Comment by kain88-de** [comment]
@orbeckst  everything you requested is already done in the source. The License is noted in the 'pyx' file which I think is better then using a separate LICENSE file and we also list the licence in the top-level LICENSE file. We also link to the github repo.

**Comment by kain88-de** [comment]
Oh and yeah I think this is because we are using `cythonize` explicitly now. And I would like to keep using it because it without it I can't share code between cython modules (since I'm doing that in the [new xdrlib branch](https://github.com/kain88-de/mdanalysis/blob/ba87760a965ce94a546c61e6223315648763b8d3/package/MDAnalysis/lib/formats/xtc.pyx#L204)

**Comment by orbeckst** [comment]
Ok.

Can you please also check the sphinx docs? There might be references to `_distances` and `_distances_omp`. Fix those (if they exist) and I merge.

**Comment by kain88-de** [comment]
I updated the docs as well now.

**Pull request merged**
