### PR TITLE
test for writing DX files from density (Issue #544)

### PR DESCRIPTION
**Pull request by orbeckst**
Requires a 0.3.1 release of GridDataFormats, see MDAnalysis/GridDataFormats#24.

### CODE REVIEW

**Comment by orbeckst** [comment]
rebased against develop (in particular with #552 fixed).

**Comment by orbeckst** [comment]
Rebased against develop and force-pushed. Added new requirement for GridDataFormats >= 0.3.1.

**Comment by orbeckst** [comment]
No idea why, on travis, python appears to be unable to find GridDataFormats, even though it is clearly being installed (in version 0.3.1):
```python
from gridData import Grid
```

fails in `MDAnalysis.analysis.density`.

**Comment by kain88-de** [comment]
@orbeckst did you check locally of the gridData package can be loaded in a new virtualenv?

**Comment by orbeckst** [comment]
rebased against develop

**Comment by orbeckst** [comment]
Installing GridDataFormats into fresh virtualenv worked and all tests passed.

**Comment by orbeckst** [comment]
rebased against develop

**Comment by orbeckst** [comment]
Now part of the tests pass in [build #1038](https://travis-ci.org/MDAnalysis/mdanalysis/builds/96147158):
* SETUP=full CYTHONIZE=true: **passes**
* SETUP=minimal CYTHONIZE=false: **fails** because `gridData` could not be imported

I don't quite understand the failure, though, because the travis config *always* does a `pip install GridDataFormats`, regardless of the `SETUP` variable.

**Comment by kain88-de** [comment]
Yeah I also don't quite get the error. You could try to start python and import `gridData` independent of MDAnalysis. Adding a line like `python -c import gridData` should do that.

**Comment by orbeckst** [comment]
@kain88-de thanks for the idea: now I know why the minimal fails: GridDataFormat wants scipy. 
```
$ python -c 'import gridData; print(gridData.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/gridData/__init__.py", line 191, in <module>
    from .core import Grid
  File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/gridData/core.py", line 30, in <module>
    from scipy import ndimage
ImportError: No module named scipy
```

So I will decorate the tests.

**Comment by orbeckst** [comment]
... or see if I can make scipy optional in GridDataFormats, i.e. only loaded if one wants to do the interpolations.

**Comment by kain88-de** [comment]
Currently this is not possible. The ndimage function is already called at the initialization of the `Grid` object.

**Comment by orbeckst** [comment]
ah, crap... this fails at the top level as soon as `analysis.density` is imported.

Well, wait for MDAnalysis/GridDataFormats#25 ...

**Comment by orbeckst** [comment]
Just release GridDataFormat 0.3.2: will update and rebase this branch and then it should work...

**Comment by orbeckst** [comment]
(I am a bit miffed that QC makes the PR look as if it does not pass the tests... most of the QC issues are things that I will simply ignore.)

**Comment by mnmelo** [comment]
How I see it we have to tweak as we go. Any given test can be disabled, so go ahead and disable the ones you think won't apply to our style (or tell me which and I'll do it).

As to the build "failing", I think it's harmless, and draws the attention of the PR reviewer to possible code issues. When we prune to leave only the tests we consider important a failure will be much more meaningful.

**Comment by orbeckst** [comment]
I reviewed the [QC issue](https://www.quantifiedcode.com/app/project/gh:MDAnalysis:mdanalysis/diff/4a7e3cfa89f583ceabc314420bd9c65271b3cbd7/738befdc8d66df0c5020222cfe5fb439660fde2f/issues?groups=code_patterns%3Akv4o9Hx2,code_patterns%3A5ZdRTEsh,code_patterns%3A4m6i5Dpz,code_patterns%3A3ueqPTsn,code_patterns%3A2QdgB8ll,code_patterns%3A1ynDCGAE,code_patterns%3A1sMHNVxe) and I will *not* fix any of the reported issues --- they all relate to how we write our tests and I don't think that there's anything wrong with it,

@kain88-de, please consider the PR complete from my end (short of other problems you or anyone else might identify).

**Pull request merged**
