### PR TITLE
Rename libmda to libmdanalysis and clean up __init__.pxd

### LINKED ISSUE #3738: Change the name of libmda to libmdanalysis
## Is your feature request related to a problem? ##

Discussion in #3734 has indicated that `libmda` is likely too generic a name for our public Cython API

## Describe the solution you'd like ##

We should rename it to something like `libmdanalysis`

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #3738 

Triggered by discussion on #3734 

Changes made in this Pull Request:
 - Changes the name of libmda to `libmdanalysis`
 - Clean up accidental cimport of `cutil.pxd` 

PR Checklist
------------
 - [X] Issue raised/referenced?

### CODE REVIEW

**Review by orbeckst — DISMISSED** [review]
Add a stupid little test, please, that shows that the import works.

I'm a bit surprised that coverage did not flag the PR.

**Comment by hmacdope** [comment]
> Add a stupid little test, please, that shows that the import works.
> 
> I'm a bit surprised that coverage did not flag the PR.

Is it possible to check a Cython import at all? I thought that can only happen at compile time.

**Comment by orbeckst** [comment]
What I meant, there should be a unit test that checks that you can do what the module promises, e.g.,
```python
from MDAnalysis.libmda import Timestep
```

Admittedly, I don't know much about cython, I just thought that this should be testable.

**Comment by hmacdope** [comment]
AFAIK I don't think it can be tested easily as the `cimport` will only work in a `pyx` or `pxd` file and throws a compile time error,  which is non compatible with pytest unless there is some super duper trickery someone knows about.

**Review by orbeckst — APPROVED** [review]
With your explanation I think there’s not more to be done.

**Comment by orbeckst** [comment]
Please merge at your leisure.

**Comment by hmacdope** [comment]
Thanks @orbeckst :+1:

**Pull request merged**
