### PR TITLE
Updated references format to BibTex.

### LINKED ISSUE #2837: References are formatted properly
## Expected behavior ##

References are formatted properly

## Actual behavior ##

Mark*down* markup != reStructuredText

Screen Shot 2020-07-11 at 6 41 32 am

## Code to reproduce the behavior ##

https://github.com/MDAnalysis/mdanalysis/blob/3e56b70da3b48a523924308e1149d46fadddbb5d/package/MDAnalysis/analysis/contacts.py#L257

## Current version of MDAnalysis ##

2.0.0-dev0 docs

## More ##

It might be easier to just use bibtex and autoformat the references, as the user guide does. Then we'll  also have a consistent style.

### PR DESCRIPTION
**Pull request by ojeda-e**
This PR partially Fixes #2837

Changes made in this Pull Request:
 1. Added `references.bib` in `/package/doc/sphinx/source/` with BibTeX format of all references used in the MDAnalysis repo.
 2. Updated `config.py` to add BibTex extension.
 3. Updated `gh-ci.yaml` to build docs with BibTex.
 4. To start, I implemented BibTex references in three different files:
    4.1 Documentation: `encore.rst`.
    4.2 Analysis: `bat.py`
    4.3 Base: `units.py`

With [4], my intention is to show a preliminary version of the docs with BibTex references before modifying further files. It would be nice to get some feedback with the changes made so far.

Next steps
------------
Implement BibTex in:

~~- [ ] `package/doc/sphinx/source/documentation_pages/references.rst`.~~
- [x] `package/doc/sphinx/source/documentation_pages/analysis/encore.rst`.
- [x] `packagage/doc/sphinx/source/documentation_pages/analysis/hole2.rst`.
- [x] `package/MDAnalysis/analysis/contacts.py`
- [x] `package/MDAnalysis/analysis/difussionmap.py`
- [x] `package/MDAnalysis/analysis/dihedrals.py`
- [x] `package/MDAnalysis/analysis/gnm.py`
- [x]  `package/MDAnalysis/analysis/msd.py`
- [x]  `package/MDAnalysis/analysis/psa.py`
- [x]  `package/MDAnalysis/analysis/pca.py`
- [x] `package/MDAnalysis/analysis/rms.py`
- [x] `package/MDAnalysis/analysis/waterdynamics.py`
- [x] `package/MDAnalysis/analysis/encore/similarity.py`
- [x] `package/MDAnalysis/analysis/hole2/__init__.py`
- [x] `package/MDAnalysis/analysis/hydrogenbonds/hbond_autocorrel.py`
- [x] `package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py`
- [x] `package/MDAnalysis/analysis/legacy/x3dna.py`
- [x] `package/MDAnalysis/lib/correlations.py`
- [x] `package/MDAnalysis/lib/transformations.py`
- [x] `package/MDAnalysis/visualization/streamlines.py`
- [x] `package/MDAnalysis/visualization/streamlines_3D.py`
- [x] `package/MDAnalysis/analysis/nucleicacids.py`
- [x] `package/MDAnalysis/analysis/nuclinfo.py`
- [x] `package/MDAnalysis/analysis/data/filenames.py`

PR Checklist
------------
 - [N/A]Tests
 - [x] Docs?
 - [ ] CHANGELOG updated
 - [x] Issue referenced

### CODE REVIEW

**Comment by lilyminium** [comment]
Screen Shot 2022-05-12 at 11 23 10 am

It looks great, thanks @ojeda-e! (example above). This is more of a design question: would it be easier to have a single `references.rst` that has the entire bibliography? Or is it more neat and modular to have individual `References` sections per page/docstring (as it currently is)?

I also wonder if it's possible to change the inline style to something more like normal text, e.g. `Tiberti et al., 2015` instead of SurnameYear.

**Comment by ojeda-e** [comment]
Thanks @lilyminium, and also thanks for your questions. :)

I was/am hesitant about the `references.rst` page because I am not convinced what would be the best approach here. I like the references per section/page, but I also wonder if having full references may provide value to some users. 
What I can do is to include the rest of the references (checkboxes) and give the `references.rst` a try to check how it looks once we have them all. Probably it will be easier for us to make a decision once we have it at a full length: if we don't like it, then we toss it. Or maybe we can keep both? In any case, probably we'll know better once we have everything in place. What do you think?

About the style, yes, agreed, the style can be improved. I didn't know what would be best, so thanks for suggesting the example of `Tiberti et al., 2015`. I found that we can create a [custom formatting](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html?highlight=custom#custom-formatting-sorting-and-labelling). However, it requires [Pybtex plugins](https://docs.pybtex.org/api/plugins.html) and thought it was better to ask before adding them in the changes. I will start by modifying the keywords first before using Pybtex, maybe it's not necessary.

If it is ok with you, I will work on the rest of the pages, then will tune the style, and then I'll add `references.rst` as the last step.

**Comment by ojeda-e** [comment]
**Summary**
I updated some other files and added an initial style that uses the reference key.  I added the MDA style only for one example while we make a decision on the style.

For example, in `package/MDAnalysis/lib/correlations.py`, the reference

```BibTex
@article{Gowers2015,
	author = {Gowers,Richard J.  and Carbone,Paola },
	title = {A multiscale approach to model hydrogen bonding: The case of polyamide},
	journal = {The Journal of Chemical Physics},
	volume = {142},
	number = {22},
	pages = {224907},
	year = {2015},
	doi = {10.1063/1.4922445},
	url = { https://doi.org/10.1063/1.4922445},
}
```
would be shown as `Gowers2015` (reference key).  


**Issues**
- I am finding discrepancies between what I see locally rendered and the build.

While I see `package/MDAnalysis/lib/correlations.py` shown as 
image
image

the [build docs](https://mdanalysis--3663.org.readthedocs.build/en/3663/documentation_pages/lib/correlations.html?highlight=correlations#module-MDAnalysis.lib.correlations), OTOH, show:

image

with empty references.

I checked the dependencies for Sphinx and compare my mda-dev env and the one from the docs and it looks like they are the same, so I can't really find the reason for the discrepancy.
~~Sphinx                        4.5.0~~
```
sphinx-rtd-theme              1.0.0
latexcodec                    2.0.1
pybtex                        0.24.0
pybtex-docutils               1.0.1
sphinxcontrib-bibtex          2.4.2
text-unidecode                1.3
```
Edit: I made a mistake here, the version of Sphinx in docs was pretty out of date (current one is 4.5.0 previous was 1.8.5. While writing this edit, @IAlibay commented [below](https://github.com/MDAnalysis/mdanalysis/pull/3663#pullrequestreview-973081862) ). 

Maybe @lilyminium has an idea on how to troubleshoot this?

- The PR is getting very large, so far 28 files changed, and there are still several files that need to be updated to BibTex format, mostly `.rst` files. I wonder if it would be easier to open and new issue for the rest of the changes. I offer three options:

Option 1: Remove the style from this PR (which also seems problematic because of discrepancies) and open two new issues: one to finish updating the references, and one to address the style of the references.

Option 2: Remove the style from this PR. Open one more issue to both finish references and fix style.

Option 3: Fix style in this PR. Open one more issue to finish 

I am more inclined to go for Option 1 because it will fix the issues progressively and the style would be the final touch here. It may also give some time to fix the discrepancy. 

Edit: Forgot to tagg @orbeckst @richardjgowers @IAlibay @jbarnoud in case they have other suggestions.

**Review by IAlibay — COMMENTED** [review]
@ojeda-e I cleaned that docs environment file in my proposal PR for numpy / python version increasing you might want to copy the change from there (essentially the main thing is - let's not pin sphinx to any given version anymore)

**Comment by ojeda-e** [comment]
I think I have the main fixes so far. Pinning @lilyminium for a review here :) 

A quick explanation of the changes using the same example as in [the previous comment](https://github.com/MDAnalysis/mdanalysis/pull/3663#issuecomment-1126728643).

1. The references in `package/MDAnalysis/lib/correlations.py` look like:

image

image

2. The MDA style for references was set for three different cases, depending on the number of authors:

- One author: `LastnameYear`. Example: [Frèchet1906](https://mdanalysis--3663.org.readthedocs.build/en/3663/documentation_pages/analysis/psa.html#id134)
- Two authors:  `Lastname1stAuthor-Lastname2ndAuthorYear`. Example: [Araya-Secchi et al. (2014)](https://mdanalysis--3663.org.readthedocs.build/en/3663/documentation_pages/lib/correlations.html#id3)
- More than two authors: `Lastname1stAuthor et al. (Year)`. Example: [Gowers et al. (2015)](https://mdanalysis--3663.org.readthedocs.build/en/3663/documentation_pages/lib/correlations.html#id1)

I would like to ask for some suggestions for the labels to use in the references. I am not totally convinced that for two authors that's the best label. Maybe `Lastname1stAuthorYear` is good enough. 

3. Since Sphinx doesn't allow to add the bibliography of duplicate references in separate files, we need to use the `:labelprefix:` and `:keyprefix` directives as shown in the [documentation](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#key-prefixing). So I added a superscript (ᵃ,ᵇ) for the `labelprefix` which IMO looks better. Example: [ᵃChavent et al. (2014)](https://mdanalysis--3663.org.readthedocs.build/en/3663/documentation_pages/visualization/streamlines.html#id12) for streamlines and [ᵇChavent et al. (2014)](https://mdanalysis--3663.org.readthedocs.build/en/3663/documentation_pages/visualization/streamlines_3D.html#id65) for streamlines3D.

4. There is no consistency in the way the section reference is in docstrings. Sometimes they are
```
References
------------
```

or sometimes they appear as

```
.. rubric: References
```
Although the outcome seems to be the same, I could also change them to make them consistent, if there is any interest.

I would like is to keep the changes of this PR to the 29 files changed and open one or two issues to finish the remaining references. I completely underestimated the amount of work here needed. Thanks.

**Comment by richardjgowers** [comment]
@ojeda-e pretty sure I only wrote one of the two papers above, I think somewhere the Araya-Secchi paper got mushed to my name?

re2) Yeah I'd not seen that dual author style before.  I *do* think we can worry about style later, and include the material benefits of this PR sooner though.

re4) I think the `.. rubric` notation is pure rst, and the other syntax is numpy napoleon which (I think) gets converted to the former somewhere in the doc process.  I think we generally prefer the napoleon style because it is more human readable

**Comment by orbeckst** [comment]
Quick comment: The rubric is sometimes necessary when we do not want the References to show up in a table of contents. You sometimes have to see if the Napoleon style works. The lack of consistency is not necessarily because of carelessness but may be because of limitations in when Napoleon recognizes sections and how we want to organize things. However, if there's a consistent way that works then I am all for it — often, we worked around limitations in the past that were fixed in the present but we never revisted the past workarounds.

**Comment by orbeckst** [comment]
Just keep a simple key — `Lastname1stAuthorYear` would work for me for all cases. The a/b/... prefixes look ok for duplicate keys.

**Comment by IAlibay** [comment]
I'm going to agree with @orbeckst, it's probably best to take a "per case" implementation of whatever way we want to have the references. That being said, having the preferred style for "standard cases" being Napoleon style seems good to me.

> I would like is to keep the changes of this PR to the 29 files changed and open one or two issues to finish the remaining references. I completely underestimated the amount of work here needed. Thanks.

That's fine, but I would like to not have "docs in progress" for 2.2.0 (it wouldn't be the worst tbh, but also if we can avoid it it'd be best). If there's still stuff to do then I'm going to have to ask if this PR can be put on hold until the 2.2.0 release?

**Comment by ojeda-e** [comment]
Thanks for the comments. I updated it to `Lastname1stAuthorYear` for all cases.

Not in a rush to get this merge @IAlibay. In the meantime, I will check all the changes in this PR are working as expected.

**Comment by ojeda-e** [comment]
Ok, I think this PR is ready for review @lilyminium @IAlibay considering the hold for the 2.2.0 release. I fixed some other mistakes I found while double-checking in the previous push. 
Again, thanks for all your input. I really like how the docs look with these changes. :)

**Comment by ojeda-e** [comment]
Hi @MDAnalysis/coredevs, is anyone available for a review here?

**Review by orbeckst — APPROVED** [review]
Looking good — quite a lot of work! Well done.

However, adding references has become more involved for anyone writing docs. One can no longer just add them to the reST but instead must add them to `references.bib`.  One also needs to know the citation construct and how to write a bibliography as it's no longer covered by the standard reST/sphinx format.

You are now the resident expert on citations in our docs. Therefore the following is really important for the future sustainability of the project: **Transfer your knowledge** on how to add citations and what to consider to the **User Guide** to the https://userguide.mdanalysis.org/stable/contributing_code.html#working-with-the-code-documentation section?

- [x] raise an issue in https://github.com/MDAnalysis/UserGuide/issues to discuss citations
- [ ] add a section on citation handling to the User Guide (to close the issue)

Thanks!

**Comment by orbeckst** [comment]
@ojeda-e I am giving folks a day or so to also chime in. If I don't get to merging tomorrow, please feel free to ping me.

In the meantime, please open the issue for the User Guide and reference this PR (and it's issue) so that it gets nicely linked.

**Comment by ojeda-e** [comment]
Thanks @orbeckst. I'll start to work on the second part once it gets merged.

**Comment by orbeckst** [comment]
Thank you for the work, @ojeda-e !

**Pull request merged**
