### PR TITLE
Issue #521 mol2writefix

### PR DESCRIPTION
**Pull request by richardjgowers**
MOL2Writer still needs an AtomGroup or Universe to write (rather than just a Timestep) but I can't see an easy fix for this right now.  This at least fixes the issue at hand

### CODE REVIEW

**Comment by kain88-de** [comment]
Looks good to me. The first QC issue is actually a real one which should be fixed.

**Comment by richardjgowers** [comment]
ok done

**Comment by kain88-de** [comment]
@jbarnoud is it possible to tell QC to ignore docstring issues for tests?

**Comment by jbarnoud** [comment]
I do not know. Perhaps @mnmelo knows, he is our QC expert.

**Comment by richardjgowers** [comment]
@kain88-de I've turned them off

**Pull request merged**
