### PR TITLE
Updated LICENSE and AUTHOR info regarding xdrfile (closes #679)

### LINKED ISSUE #679: New xdrlib information in AUTHORS and LICENSE is missing/outdated
I'm opening this as a reminder so as not to let 0.14.0 ship without these fixes.

The new license aspects of xdrlib are outdated. The Gromacs base is now BSD.
We also haven't decided if the name libxdrfile2 stays, or if we call our modifications something else: with @kain88-de's cython approach (#441) and splitting of `xtc_seek.c`/`trr_seek.c` from `xdrfile.c` (#661) there is less of a clear new library to speak of.
@orbeckst has advocated keeping the name. I agree with that.
Right now we don't provide an actual `libxdrfile2.so` or `libxdrfile2.a`, but rather a mix of that with cython bindings (called `xdrlib.so`). This gets confusing but `xdrlib.so` could be renamed `libxdrfile2` to keep the external appearance and conform to the name we were using before.

### PR DESCRIPTION
**Pull request by mnmelo**
Further standardized XDR error message reporting and exceptions
(now mostly IOError).

Removed reference to the old SWIG numpy.i in the credits.

### CODE REVIEW

**Comment by orbeckst** [comment]
@mnmelo why did you close this without merging --- I thought it resolved #679 ?

**Comment by kain88-de** [comment]
He is waiting for #656 to be merged, because there where some conflicts between the two PRs

**Comment by jbarnoud** [comment]
Aren't there other ways to put a PR in hold than to close it? Closing it seems to me like a good way to just forget it.

**Comment by kain88-de** [comment]
the original plan was to merge this into my branch in my repo. But we have switched back and decided to rather stay with doing the PR's one after the other.

**Pull request closed without merging**
