### PR TITLE
New module to analize water dynamics.

### PR DESCRIPTION
**Pull request by alejob**
Now this pull request is able to merge automatically.

This module has five new analysis methods:
Hydrogen Bond Lifetimes (HBL)
Water Orientation Relaxation (WOR)
Angular Distribution (AD)
Mean Square Displacement (MSD)
Surivival Probability (SP)

The corrections and suggestions has been added. 
Thanks for the feedback.

### CODE REVIEW

**Comment by alejob** [comment]
I'm solving the problem...

**Comment by orbeckst** [comment]
@alejob looks good, just do the following: 
* In the docs, add 

   ```
   .. versionadded:: 0.11.0
   ```

   to the top of the module docs and to the bottom of the class docs of each class.
* Add an entry to CHANGELOG under *Enhancements* and add your *user name* alejob as a contributor to the newest release. (You are already in AUTHORS.)

I don't know if you can amend this pull request or if you need a new one but just mention me in your comments so that I am directly notified and then I can do the merge (provided tests still pass).

**Comment by alejob** [comment]
Hi @orbeckst, it's done. 

I have a question, in CHANGELOG apparently there is a mistake, because there is a 0.10.1 version. I followed the rule number 3 (don't ever delete anything) and didn't touch that part of the LOG.

**Comment by orbeckst** [comment]
On 10 Jun, 2015, at 13:08, Alejandro Bernardin wrote:

> Hi @orbeckst, it's done.
> 
> I have a question, in CHANGELOG apparently there is a mistake, because there is a 0.10.1 version. I followed the rule number 3 (don't ever delete anything) and didn't touch that part of the LOG.

Don't worry about the 10.0.1, it will be changed.

**Comment by orbeckst** [comment]
@alejob : Thank you for the contribution, it will be in 0.11.0 :-)

**Comment by alejob** [comment]
Thanks you @orbeckst and @richardjgowers for your feedback.

**Comment by richardjgowers** [comment]
Congrats on getting #300 , very cool code too!

**Pull request merged**
