### PR TITLE
Enabling pure python py3.11 cron CI and get Cirrus to py3.11

### PR DESCRIPTION
**Pull request by IAlibay**
Towards #3878 

Changes made in this Pull Request:
 - Change cron job from py3.11-rc.2 to py3.11

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by PicoCentauri** [comment]
We also might want to add a line the `[build-system]` section in the `pyproject.toml` similar to scipy's:

`"numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",`

**Comment by IAlibay** [comment]
> We also might want to add a line the `[build-system]` section in the `pyproject.toml` similar to scipy's:
> 
> `"numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",`

@PicoCentauri - already there 🙃 https://github.com/MDAnalysis/mdanalysis/blob/45d84612e8145e38d97e332b7e1e1b7c8f4f65a4/package/pyproject.toml#L19

**Comment by IAlibay** [comment]
So python@3.11 is available on brew, just waiting on updates to make their way to cirrus.

Then the last thing on the to-do list is to update azure pipelines to pick up 3.11.

**Comment by PicoCentauri** [comment]
Ahh perfect!

**Comment by IAlibay** [comment]
So we're blocked by h5py here. There's a PR on their repo to add py3.11 wheels so I'd probably just wait for that to happen (there's no big rush right now, we still more or less know py311 is fine).

**Comment by IAlibay** [comment]
We're going to end up waiting for ~ couple weeks for h5py, so I'd prefer move that to a follow-up PR where we also test adding py3.11 to the gh actions CI (conda install).

This should be good to merge as-is.

**Review by fiona-naughton — APPROVED** [review]
lgtm :)

**Pull request merged**
