### PR TITLE
Unhardcode LammpsDumpParser

### PR DESCRIPTION
**Pull request by lilyminium**
**Fixes below:**

[Amir can't load their LammpsDump file because atom lines have more than 5 fields.](https://groups.google.com/forum/?pli=1#!topic/mdnalysis-discussion/XzkQ-scJxLc)

```
>>> cell = mda.Universe(path, format='LAMMPSDUMP', atom_style='id type x y z xs ys zs')


ValueError                                Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/MDAnalysis/core/universe.py in __init__(self, *args, **kwargs)
    289                     with parser(self.filename) as p:
--> 290                         self._topology = p.parse(**kwargs)
    291                 except (IOError, OSError) as err:
/anaconda3/lib/python3.7/site-packages/MDAnalysis/topology/LAMMPSParser.py in parse(self, **kwargs)
    609             for i in range(natoms):
--> 610                 idx, atype, _, _, _ = fin.readline().split()
    611 
ValueError: too many values to unpack (expected 5)
```

**Changes made in this Pull Request:**
```diff
-                  idx, atype, _, _, _ = fin.readline().split()
+                  idx, atype, *_ = fin.readline().split()
```

I know nothing about Lammps formats, so maybe atom lines having >5 fields is a sign that something is very wrong -- but then an informative error could be raised. Or possibly it should have at least 5 fields (for x, y, z)?

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by rkingsbury** [comment]
`MDAnalysis` expects LAMMPSDUMP to be in the default 'atom' style https://userguide.mdanalysis.org/stable/formats/reference/lammpsdump.html#lammpsdump-format, which would have only 5 fields (atom ID, atom type, x, y, z) but it is not uncommon for users to output additional fields

**Comment by IAlibay** [comment]
@lilyminium I'm not super familiar with the format, do you happen to remember why this ended up stalling? (i.e. was there a practical reason or a lack of hands on deck to review?)

**Comment by IAlibay** [comment]
> `MDAnalysis` expects LAMMPSDUMP to be in the default 'atom' style https://userguide.mdanalysis.org/stable/formats/reference/lammpsdump.html#lammpsdump-format, which would have only 5 fields (atom ID, atom type, x, y, z) but it is not uncommon for users to output additional fields

@rkingsbury I think part of the problem here is that most of our devs aren't familiar with the LAMMPS format. Do you happen to have a reference to some docs for the non-'atom' style formatting?

**Comment by rkingsbury** [comment]
> 
> 
> @lilyminium I'm not super familiar with the format, do you happen to remember why this ended up stalling? (i.e. was there a practical reason or a lack of hands on deck to review?)

No, I have no idea. I've only recently started using `MDAnalysis`

**Comment by IAlibay** [comment]
> > @lilyminium I'm not super familiar with the format, do you happen to remember why this ended up stalling? (i.e. was there a practical reason or a lack of hands on deck to review?)
> 
> No, I have no idea. I've only recently started using `MDAnalysis`

Sorry for the confusion @rkingsbury that question was for @lilyminium the dev who opened this pull request.

**Comment by lilyminium** [comment]
Python 3 concerns iirc. This is one of the first PRs I ever made, back in the dark 2.7 days.

I also didn't push too hard because I'm not terribly familiar with LAMMPS. @rkingsbury is this a good solution or should anything be changed?

**Comment by hmacdope** [comment]
@lilyminium  I have been working on this in parallel for #3358. Problem with current implementation in this PR being that there is no guarantee coordinates will be in the  `fields[-3:]` spot, or that they will be in any given convention. There may also be multiple coordinate formats present.  See the following for more info. https://docs.lammps.org/dump.html.

How would you like to proceed? I can work over the top of this PR if that is easiest or  wait for this to be merged then put my own changes over the top. :)

**Comment by lilyminium** [comment]
I'm not too attached either way. Feel free to merge this branch into your own if that's easiest.

**Comment by amirhs1** [comment]
I contacted Lammps developers and they told me that
_"Please also note that fix commands like fix property/atom allow to set custom section names for storing the associated properties. So technically speaking the list of section names is infinite."_

However, they suggested me to see the documentations for these two commands (In particular, the 2nd one): [read_dump](https://docs.lammps.org/read_dump.html) and [read_data](https://docs.lammps.org/read_data.html)

**Comment by hmacdope** [comment]
Note that majority of discussion on this has shifted to #3360

**Comment by hmacdope** [comment]
@lilyminium, with #3360 being merged I think this may be able to be closed.

**Comment by hmacdope** [comment]
@lilyminium closing

**Pull request closed without merging**
