### PR TITLE
Reader speed boost

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #1357

### CODE REVIEW

**Comment by orbeckst** [comment]
I think this has to be merged to retain original authors.

(One of the travis jobs hung so I restarted it.)

**Comment by kain88-de** [comment]
@orbeckst you can squash or merge this. I don't mind  it.

**Comment by orbeckst** [comment]
#1308 also listed the GRO reader as one whose speed should be boosted but this PR did not address GRO, correct?

Is anyone working on GRO?

**Comment by kain88-de** [comment]
I checked gro. It wasn't as easy to add there for a reason I don't remember right now.

**Comment by kain88-de** [comment]
I also didn't worry much about it since it's a one frame format.

**Pull request merged**
