### PR TITLE
Addresses failure of `test_load()` in PSA (#2049)

### PR DESCRIPTION
**Pull request by sseyler**
Fixes #2049 and also boosts PSA code coverage (#1006).

Changes made in this Pull Request:
 - `test_load()` now passes after calling `save_paths()` with default arguments
 - `PSAnalysis` now has default base filename and prefix for consistency with default saving behavior of `PSAnalysis.generate_paths()`
 - Better consistency of `Path.fit_to_reference()` with `MDAnalysis.analysis.AlignTraj`
 - Better consistency of `PSAnalysis.generate_paths()` with `MDAnalysis.analysis.AlignTraj`
 - Updated PSA docs for consistency with above changes

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Thanks @sseyler , I'll wait for CI to finish. Feel free to ping me.

**Comment by orbeckst** [comment]
Weird travis failure on macOS  [960.10](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/191220986) (Python 2.7) and [960.9](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/191220985) (Python 3.6)
```
$ eval $MAIN_CMD $SETUP_CMD
/Users/travis/.travis/functions: line 104: pytest: command not found
The command "eval $MAIN_CMD $SETUP_CMD" exited with 127.
```
even though the installation logs indicate that `pytest` package was installed:
```
   pytest-4.4.0               |           py36_1         344 KB  conda-forge
```

@MDAnalysis/coredevs any idea what's wrong here?

**Comment by tylerjereddy** [comment]
I pushed this feature branch to my fork and opened a PR to the same master branch on my fork & so far the Mac job there is doing just fine with pytest running the suite: https://github.com/tylerjereddy/mdanalysis/pull/2

Maybe a restart is warranted, and if it starts showing up more regularly we can open an issue.

**Comment by tylerjereddy** [comment]
Commit history isn't the cleanest, but CI is all green now if that's what you were waiting for.

**Comment by orbeckst** [comment]
Many thanks @tylerjereddy . I'll quickly compact the history a bit.

**Comment by tylerjereddy** [comment]
We're getting the MacOS failures again--have those happened in any PR other than this one?

**Comment by orbeckst** [comment]
yes:
- recent merge into develop [965.9](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/191925510) (merge of PR #2243)
- this PR (I just restarted the macOS jobs)
- others?

**Comment by orbeckst** [comment]
I have to resolve the merge conflict in this PR so CI will run again anyway...

**Comment by orbeckst** [comment]
Now AppVeyor doesn't want to run... will rebase manually.

**Comment by orbeckst** [comment]
macOS still failing

**Pull request merged**
