### PR TITLE
cache the parse tree when necessary [select_atoms]

### PR DESCRIPTION
**Pull request by yliu120**
Users can cache the parse tree to improve some performance when they need to call select_atoms() for many many times. 

Use cases:

1) User want to check all potential neighbors of a specific atom/AtomGroup throughout a trajectory.

```
univ = Universe("traj.gro", "traj.xtc")
for ts in univ.trajectory:
    group = univ.select_atoms("around 8 (resid 1 and name CA)")
    # do something with group
```

In this case, the current code base will parse the selection string for n_frames times.
Rather than doing this, we can do the following:

```
univ = Universe("traj.gro", "traj.xtc")
for ts in univ.trajectory:
    group = univ.select_atoms("around 8 (resid 1 and name CA)", cached=True)
    # do something with group
```

Then now the parser should only work once. Unfortunately, the apply() method will
still be called for n_frame time. Another optimization can be done but in another pull
request/issue.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by yliu120** [comment]
Reference to issue/#1118

**Comment by kain88-de** [comment]
There is already work on this in #1080. Your example would work like this under the scheme.

```python
univ = Universe("traj.gro", "traj.xtc")
group = univ.select_atoms("around 8 (resid 1 and name CA)", updating=True)
for ts in univ.trajectory:
    # do something with group
```

**Comment by mnmelo** [comment]
@yliu120, I'm very curious about what you wrote:

> Unfortunately, the apply() method will still be called for n_frame time. Another optimization can be done but in another pull request/issue.

Such functionality is not in #1080, and my first impression is that reapplying every frame is something that has to be done. How exactly did you plan on avoiding it?

**Comment by yliu120** [comment]
I am happy to see there is a #1080 to fix this issue. I am sorry that I didn't know there is one before I wrote this.

@mnmelo Thanks for your question. Think this reapplying issue in such a way: In the core.selections module, only DistanceSelection type and its subtype needs to be updated for each frame. In principle, while we are reading the same trajectory, we will have the same topology. So selections like "resid 3" or "name CA" or "segid 4KEF" will not change.

So when you update the atomsel, you can cache those result for the not "DistanceSelection" type of selections. Doing something like this:

```python
class AndOperation(LogicOperation):
    token = 'and'
    precedence = 3

    @lru_cache(max_size=512)
    def apply(self, group):
        rsel = self.rsel.apply(group)
        lsel = self.lsel.apply(group)

        # Mask which lsel indices appear in rsel
        mask = np.in1d(rsel.indices, lsel.indices)
        # and mask rsel according to that
        return unique(rsel[mask])
```

Then when you reapplying, (e.g., selectionstr = "around 8 (protein and resid 45 and name CA)")
The ast should be like

                                       around 8
                                             |
                                          And (cached), when we are here we return.
                                          /     \
                                     pro    And
                                                /   \
                                           Resid  Name

In this case, we only need to rerun the operator/selection we need, for other selections, we can use the cache to skip hundreds of lines of code.

Note that this should be careful, cuz the user may write something like "resid 8 and around 8 resid 9".

**Comment by mnmelo** [comment]
I see your point now. We had a similar, though less thorough, discussion under #1080. The consensus was that even something that seems static, like topology names, might not be so. Cases might be users that re-assign atom/residue names along a trajectory, or base the updating selection off a group that is itself already updating.

That said, I wouldn't be totally against a system like you propose, provided we have a number of flags in place to signal whether data has become stale so that it's compatible with the above concerns. Still, it might be more hassle than it's worth, and some performance numbers would be welcome to know whether we're really spending so much time on those hundreds of lines of code.

**Comment by richardjgowers** [comment]
I think caching the Selection object is optimising around the wrong point (benchmarks below).  Parsing the selection is fast, applying it is the slow step.

We could look at declaring some attributes to be static so you could cache the selections, but I'd be surprised if there was a whole piece of analysis where the slow step was selecting atoms rather than working with the AtomGroups, (eg the calculation of distances).

```python
import MDAnalysis as mda

# Grab a large system, this is 2.4M atoms
u = mda.fetch_mmtf('3J3Q')


In [29]: %timeit u.select_atoms('segid g8 and name CA and resid 40')
1 loop, best of 3: 328 ms per loop

In [30]: from MDAnalysis.core.selection import Parser

In [31]: %timeit sel = Parser.parse('segid g8 and name CA and resid 40', {})
The slowest run took 11.67 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.93 µs per loop

In [33]: %timeit sel.apply(u.atoms)
1 loop, best of 3: 326 ms per loop


```

**Comment by yliu120** [comment]
@richardjgowers I really appreciate your benchmark data above. 

In #1080 , @mnmelo only optimize the parsing step but not the "apply" step. As you said, the selecting atom may not be slow but the KDTree step might be (in great probability). I agree on that but considering caching necessary "stale" selections can still improve performance. "segid g8 and name CA and resid 40" only contains selections but it show that 326ms per loop. 100 times slower than parsing. Could you please try "around 10 (segid g8 and name CA and resid 40)"?

In my previous post, I mentioned to optimize both parsing/applying step. User should have some options like "updating" keyword in #1080 to select whether they really want a quick selection.

**Pull request closed without merging**
