### PR TITLE
fix errors in new sphinx version

### PR DESCRIPTION
**Pull request by kain88-de**
Changes made in this Pull Request:
 - cite reference Seyler2015b to fix sphinx build.

PR Checklist
------------
 ~- [ ] Tests?~
 - [x] Docs?
 ~- [ ] CHANGELOG updated?~
 ~- [ ] Issue raised/referenced?~

### CODE REVIEW

**Comment by kain88-de** [comment]
Turns out there are more reference issues. I assume this is due to a sphinx update. I managed to fix some but I don't know why there is an error in `encore.rst` about missing dereferences.

**Comment by kain88-de** [comment]
See https://github.com/sphinx-doc/sphinx/pull/3565

**Comment by orbeckst** [comment]
This is fixed in PR #1126 – I think we will be able to close this PR after merging #1126

**Comment by kain88-de** [comment]
@orbeckst can this be closed then? Do you know about the current error I'm getting?

**Comment by orbeckst** [comment]
I didn't know about any false warnings in sphinx. I just got the failures due to citations and made sure that everything is referenced. In particular, I remember looking at the encore docs and wondering why it didn't work. I think I worked around it in 8cd760379e6b7d8437cac7901cbebb083a1b819c by just renaming the reference... weird. I made the same changes in references that you have here.

PR #1126 builds fine with sphinx 1.6.1 and warnings as errors so I am pretty sure this PR can be closed.

I will do so and we can re-open if necessary.

**Pull request closed without merging**
