### PR TITLE
PQRParser now reads icodes

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes Issue #1317

Changes made in this Pull Request:
 - PQRParser reads icodes
 - PQRParser uses icodes to define residues

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by richardjgowers** [comment]
@orbeckst @kaceyreidy this should fix your problems with PQR files

**Comment by orbeckst** [comment]
(The tests pass, there was just one stop that hung after the tests so I restarted. But everything is ready to be merged.)

**Comment by richardjgowers** [comment]
@orbeckst [resid + icode selection works :)](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/groups.py#L1776)

```python
u.select_atoms('resid 60A')
Out[4]: <AtomGroup with 21 atoms>

u.select_atoms('resid 60A-60C').icodes
array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C',
       'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C'], dtype=object)
```

**Comment by orbeckst** [comment]
Nice!

> On 1 May, 2017, at 13:11, Richard Gowers <notifications@github.com> wrote:
> 
> @orbeckst resid + icode selection works :)
> 
> u.select_atoms('resid 60A'
> )
> Out[
> 4]: <AtomGroup with 21 atoms>
> 
> 
> u.select_atoms(
> 'resid 60A-60C'
> ).icodes
> array([
> 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'
> ,
>        
> 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B'
> ,
>        
> 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C'
> ,
>        
> 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C'], dtype=object)
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Pull request merged**
