### PR TITLE
PEP8 fixes topology/test_topology_str_types.py

### PR DESCRIPTION
**Pull request by utkbansal**
* Replace hard tabs with spaces for indentation
* Order imports

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by utkbansal** [comment]
@jbarnoud Merge?

**Comment by utkbansal** [comment]
@jbarnoud This is the sixth commit that doesn't show me as the author!

**Comment by jbarnoud** [comment]
@utkbansal Look at the history: I am only author of the merge commit, but your commit appears earlier at the time you actually committed it. That is how the "merge" button works, but I agree it is confusing.

**Comment by utkbansal** [comment]
@jbarnoud Sorry for the false alarm. It was a bit confusing.

**Comment by jbarnoud** [comment]
@utkbansal Don't worry. It was a legitimate concern, and I did not realize what was happening right away either.

**Pull request merged**
