### PR TITLE
Release 0.16.2

### PR DESCRIPTION
**Pull request by kain88-de**
This is how a release 0.16.2 branch could look like. It starts from e24da32 and cherry-picks the commits from #1404.  

I think I can do it that we merge #1404 into develop and I do a similar cherry picking after that. I think that is the cleanest option and keeps a steady development history in the `develop` branch while `master` continues to point to the latest stable release version.

@MDAnalysis/coredevs are you OK with this model?

### CODE REVIEW

**Comment by orbeckst** [comment]
Looks good to me. 

Thanks for working on it!

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
Given that Travis full is timing out, I am trying to do a quick local test.

**Comment by kain88-de** [comment]
So #1404 is merged now. There haven't been any changes since I made the original PR. This is a viable branch for release 0.16.2 now.

**Comment by kain88-de** [comment]
@richardjgowers you need to fix the merge conflicts during the merge. I can't get rid of them. I'm not sure why to be honest.

**Comment by orbeckst** [comment]
FYI: Running the full tests (including ncdf, HOLE, ClustalW, ...) on Linux x86_64 
```
./testsuite/MDAnalysisTests/mda_nosetests -v --processes=12 --process-timeout=400 --no-open-files analysis auxiliary core coordinates formats lib topology utils
```
mostly passes:

       Ran 5439 tests in 149.601s
       FAILED (KNOWNFAIL=4, SKIP=3, errors=2)

The errors are due to trajectory index files not being readable by numpy/zipfile (see [testlog.txt](https://github.com/MDAnalysis/mdanalysis/files/1095933/testlog.txt)), which I think is actually due to race conditions when running the tests at high parallelization levels (I used 12 processes); I will re-run with 2 procs and will post results when that is done. 

It took me a while that (at least at the moment – perhaps due to #1370 ?) we cannot run the tests in the way we [recommend testing for developers](https://github.com/MDAnalysis/mdanalysis/wiki/UnitTests#recommended): 
```
cd testsuite/MDAnalysisTests
./mda_nosetests -v --processes=4 --process-timeout=120
```
If I try to have `mda_nosetests` collect the files itself, then I get ~100 ERRORs and various weird failures.

**Comment by kain88-de** [comment]
really I always collect with mda_nosetests and it works fine.

**Comment by orbeckst** [comment]
Then I don't really have a good explanation why it does not work for me (see  
[testing_implicittests_2core.txt](https://github.com/MDAnalysis/mdanalysis/files/1095996/testing_implicittests_2core.txt)
).

     Ran 6013 tests in 522.195s
     FAILED (KNOWNFAIL=4, SKIP=6, errors=62, failures=10)

I work in a venv, actually pip-uninstalled MDAtests before `pip install --upgrade testsuite/`, I removed all `*.pyc` files from my source tree.
```
cd ./testsuite/MDAnalysisTests && ./mda_nosetests -v --processes=2 --process-timeout=400 --no-open-files 2>&1 | tee ../../testing_implicittests_2core.txt
```

It's not worth making a big fuss about it given that the testing is changing anyway.

**Comment by kain88-de** [comment]
I can run all tests on my machine in a single process. Only the testsuite_test_authors test files for a reason that is unkown to me.

**Comment by kain88-de** [comment]
I removed the TRZ fix

**Comment by richardjgowers** [comment]
@kain88-de can you rebase the CHANGELOG/fix the conflict with @utkbansal now needing to be in 16.2

**Comment by kain88-de** [comment]
@richardjgowers I'd love to solve the merge conflict but I can't I honestly don't know why there is an error in the first place. I tried yesterday to fix it on my laptop with local test merges but I just can't get git to work right on this one.

**Pull request merged**
