### PR TITLE
Tests can now detect memleaks on a test-by-test basis (closes #323)

### LINKED ISSUE #323: Testing for memleaks
Recent issues (#312, #297) showed it'd be very useful to report uncollectable objects in our tests. Two solutions below (as I wrote this and tested further I became in favor of solution 2):

1.
A very simple way to do this is to have a `teardown_package` module-level function that runs `gc.collect()` and then checks whether `gc.garbage` is empty. Nose automatically runs this at the very end of the tests and we get one check for leaks during the entire test run.

The problems with this approach are:
- In my hands the presence of such a function kept nose from parallelizing. It apparently did spread out into multiple threads but they all ran, extra slow, in only one core (I'm guessing it did threading instead of multiprocessig and ran into GIL slowness, but I could be totally wrong).
- In order to be comprehensive we want our run to be serial anyway, otherwise memleaks in child test processes are missed.

I don't know if the testing of Travis builds is done in parallel. If so, then this becomes more problematic than just slowing down testing during development.

A solution might be to check if the `--processes` flag is set, and if so skip the definition of `teardown_package` (couldn't find exactly how to access the flag, though). A workflow for development would then be to run parallel until all passes, and finally run once in serial to check for memleaks (if you're debugging memleaks then tough luck, you're stuck with having to repeatedly run in serial).
Again, if Travis tests in parallel then this would mean memleaks don't get tested there.

2.
A second approach is to create a class, say, `MemleakTest` that subclasses TestCase. Through some hacking we can get our `MemleakTest` to wrap `tearDown` within its own `tearDown`method that invokes `gc.collect()` and then checks whether `gc.garbage` is empty. Each test class we need to memleak-check just has to inherit from `MemleakTest`.
After fiddling around this seems pretty straightforward to do. `gc` ends up being imported in every test call, but there's no performance hit once it's already loaded, right?
I'll push a branch soon.

### PR DESCRIPTION
**Pull request by mnmelo**
Here it is. Let me know what you think.
I exemplified the use in `test_persistence.py` and included there the positive case where a leak *does* occur (testing the tester... is this getting too meta?).
The job now is to extend the use to all test classes we think should be tested for memleaks (all of them?)

One caveat:
I'm using a `@classmethod setUpClass` to hack the wrapping of `tearDown`. We don't use `setUpClass` anywhere else on the tests, but future test classes must also not override it (I added a note in the docs).

### CODE REVIEW

**Comment by richardjgowers** [comment]
So does this new subclass of TestCase run an additional test at the end of all the tests to make sure that everything has been properly deleted?

**Comment by mnmelo** [comment]
Yes, at the end of each test, in each class that subclasses it. And as it is it doesn't affect test parallelization.

**Comment by orbeckst** [comment]
This looks like a very wily way to do the mem leak testing ;-).

So if I subclass from `MemleakTest` then I can always use the "magic" method `test_that_memleaks()` to test the Memleak-tester? I am glad that you added the example, otherwise my head would spin from too much meta. I imagine that you don't really need to have a `test_that_memleaks()` in all subclasses, right?
Does parallel testing still work, e.g. can someone else confirm (e.g., @tylerjereddy , who recently reported that this worked (again?) for him?).

Assuming that parallel test are working, I am happy with it.

**Comment by mnmelo** [comment]
No, that wasn't probably so clear.
test_that_memleaks is only there as a positive control for the MemleakTest class (to test the tester...)
You get memleak testing just by subclassing MemleakTest.

One thing I noticed is that you'll only catch leaks of objects that have been deleted in the class' tearDown. If say, self.leaky_universe isn't deleted then it'll still be in scope when the leak tester runs, and gc will not report it then as uncollectable.

This might be annoying because it'll be picked up on the next class that gets run, and the memleak will be reported out of place.

Maybe give me some time to sort this out before merging ;-)

**Comment by mnmelo** [comment]
Ok,
I did some more hacking and now I also ensure all remaining objects that are created during setUp and the test get deleted before attempting to garbage collect. Now a memleak should be reported rright at the end of the test that created it.

**Comment by orbeckst** [comment]
Looking good, pretty funky class magix.

**Pull request merged**
