### PR TITLE
Force recompilation of cython files

### PR DESCRIPTION
**Pull request by kain88-de**
touching them should be enough.

see #559

### CODE REVIEW

**Comment by richardjgowers** [comment]
We need this as a separate build so that we test both the `.c` we ship and the `.pyx` we ship works.  So in the `.yml` this new line gets placed behind an if statement.

**Comment by kain88-de** [comment]
first this should run without the matrix. I'm not sure why it isn't working though.  @richardjgowers it would be nice if you could do the matrix stuff on travis. I have no idea how to do that.

**Comment by orbeckst** [comment]
Travis is really annoying me today. I just merged #559, which passed as a PR, and now develop fails. 

I am hitting the "rerun" now... maybe the Gremlins will play elsewhere.

**Comment by kain88-de** [comment]
Any idea why the heck it suddenly can't import the logs?

**Comment by orbeckst** [comment]
No effing idea. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Dec 4, 2015 um 5:24 schrieb kain88-de <notifications@github.com>:

**Comment by orbeckst** [comment]
I restarted the build on travis, maybe it will work now and a11c164 will pass.

**Comment by kain88-de** [comment]
So yeah I figured out what the problem is. cython assumes that source and shared-object have the same name in the end. If you change that then the init function has the wrong name and python can't import it. I'm not sure yet if this is a problem from us or cython.

**Comment by kain88-de** [comment]
the build fail should be addressed now in #569

**Comment by kain88-de** [comment]
tests are now done in a matrix. Now we test both `.pyx` and `.c` files

**Comment by richardjgowers** [comment]
Thanks, this is also awesome!  One thing, once the other PR with a build matrix goes through, I think MINIMAL won't have Cython.  So we don't want 4 (2x2) builds but rather
- Full with rebuild
- Full without rebuild
- Minimal (without rebuild, because no Cython)

https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

Should just be adding an exclusion, or specifying the three builds manually.

**Comment by kain88-de** [comment]
Sounds good to me too. This can be merged now. Afterwards we can specify the correct *setup* builds

**Pull request merged**
