### PR TITLE
Make GSD optional

### LINKED ISSUE #3819: Make GSD an optional requirement
As per other file format specific dependencies, it would make more sense for GSD to not be a base dependency.

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #3819 

Changes made in this Pull Request:
 - Make GSD an optional requirement

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

----
:books: Documentation preview :books:: https://mdanalysis--4174.org.readthedocs.build/en/4174/

### CODE REVIEW

**Comment by IAlibay** [comment]
Opening this early so I can get some feedback from @MDAnalysis/coredevs - this is probably quite an abrupt change, do we need to have some kind of deprecation window?

**Review by richardjgowers — APPROVED** [review]

**Comment by RMeli** [comment]
I don't think so IMO. It might surprise some users, but the error message is very clear and the solution a pip install away.

**Comment by IAlibay** [comment]
Ok this should be good to go I think (unless I forgot to fix some test somewhere). Since it's a core dependency change, I'm going to leave this here for a week for other @MDAnalysis/coredevs to chime in, and if there are no objections it'll get merged.

Specifically pinging @orbeckst here, since we've spent a lot of time pondering in the past on how best to do these types of changes.

**Review by RMeli — APPROVED** [review]

**Review by hmacdope — APPROVED** [review]
LGTM thanks @IAlibay

**Comment by orbeckst** [comment]
For reference: conda-forge feedstock was already updated https://github.com/conda-forge/mdanalysis-feedstock/pull/57

**Review by orbeckst — APPROVED** [review]
I agree.

Eventually it would be good to also allow gsd > 3.0 but we have to be able to test it. In the short term, the restriction is sensible.

**Comment by orbeckst** [comment]
@IAlibay I'll let you do the merging (unless you want someone else to do it, then change the assignee). Thanks for working out the problem and the quick-fix.

**Comment by joaander** [comment]
> I agree.
> 
> Eventually it would be good to also allow gsd > 3.0 but we have to be able to test it. In the short term, the restriction is sensible.

Please test GSD 3.0.1.

**Comment by orbeckst** [comment]
@joaander thanks, we'll check that #4172 is solved with gsd 3.0.1. Will just take a few days (people on holidays etc).

If it works we could blacklist 3.0.0 and otherwise allow `gsd!=3.0.0`. We'll probably still make it optional as we have been trying to slim down dependencies.

**Comment by joaander** [comment]
@orbeckst understood. If 3.0.1 passes your tests, I expect 3.0.0 will work for your users. I find that most users follow PEP8 guidelines and issue imports at the top of the module, not inside child threads.

**Pull request merged**
