### PR TITLE
TST: added asv benchmarks for analysis.distances

### PR DESCRIPTION
**Pull request by tylerjereddy**
This PR adds asv benchmarks for `analysis.distances` functions. I ran the new benchmarks locally with:

`asv run -e -s 20 --bench DistancesBench -j 10 "ddb57592..9ba1ab964 --merges" >& log.txt` 

and the complete [log file is available](https://github.com/MDAnalysis/mdanalysis/files/1507634/log.txt). As usual, some benchmarks will fail for really old commits and I also noticed that `time_contact_matrix_sparse` is prone to a timeout failure when 10,000 points are used (there's a 60 second limit -- fair enough, I think -- we might want to skip this particular test at 10k points).

There are really no notable regressions across the full complement of functions in this analysis module -- nothing worse than about 1.4 x slow down.

One benchmark, `time_dist` does seem to improve notably:

image

Finally, I've avoided box / pbc-related benchmarks until we / I decide on a reliable / consistent way to look at this, but I did include pre-allocated array benchmarks where applicable to help prevent regressions more completely.

### CODE REVIEW

**Comment by orbeckst** [comment]
Would it be worthwhile to already structure the analysis benchmarks like the tests, i.e., a directory `analysis` and then call this one `distances.py`?

**Comment by tylerjereddy** [comment]
@orbeckst If you think that is a good idea it is certainly possible as arbitrary subdirectory nesting is supported (all `.py` files will get scraped in).

As things evolve with the benchmarks I imagine we'll find that some refactoring will have to happen. Anyway, I can do this tomorrow for these additions if people like that idea.

**Comment by tylerjereddy** [comment]
Ok, the suggested file path reassignment has been performed. I don't see a compelling reason to re-run the benchmarks locally though -- feel free to do this on your machine if you want to check that everything still works ok (should be fine).

**Comment by orbeckst** [comment]
@tylerjereddy Do we still need to use our own fork of asv? 

Is the [benchmarks/README.rst ](https://github.com/MDAnalysis/mdanalysis/blob/develop/benchmarks/README.rst) up-to-date?

**Comment by tylerjereddy** [comment]
@orbeckst Yes, we need to use our own fork of `asv` because of the `setup.py` path in our library. The upstream changes I made to asv were merged, but they only addressed the issue with custom conda channels for things like our testsuite.

Pauli and I agreed to close my crude initial attempt at more broadly handling flexible library installations in asv because this requires quite a bit more thought (I think some people want more generic build / make type support). I bet that will be a challenging one to solve judging by the effort required just to get conda channel support added & the small number of active developers.

The README doesn't look too bad. It might be missing a few of our empirical observations about the usefulness of using only merge commits in some cases, etc., but it isn't too far out of date just yet.

**Comment by orbeckst** [comment]
This means that we have to maintain our fork of ASV for the foreseeable future, doesn't it?
Do you tend to merge upstream changes into the flexible branch?

> Am Nov 29, 2017 um 18:47 schrieb Tyler Reddy <notifications@github.com>:
> 
> @orbeckst Yes, we need to use our own fork of asv because of the setup.py path in our library. The upstream changes I made to asv were merged, but they only addressed the issue with custom conda channels for things like our testsuite.
> 
> Pauli and I agreed to close my crude initial attempt at more broadly handling flexible library installations in asv because this requires quite a bit more thought (I think some people want more generic build / make type support). I bet that will be a challenging one to solve judging by the effort required just to get conda channel support added & the small number of active developers.

**Comment by orbeckst** [comment]
@tylerjereddy I saw airspeed-velocity/asv#547 which asks for a way to specify the location of `setup.py`. If solved, would be sufficient for our case, wouldn't it? Should we chime in there?

**Comment by tylerjereddy** [comment]
@orbeckst I've added a brief comment in there, but unfortunately we'll have to maintain our fork for now. Development of asv is tricky, and both of the other people involved there are also busy with duties on the scipy core team.

**Pull request merged**
