### PR TITLE
Fixed copying record_type attribute

### LINKED ISSUE #2178: Universe.copy() error with PDB file
**Expected behavior**

I expect to have a new, independent copy of the universe. It works 

**Actual behavior**

I receive the following error.

```
TypeError                                 Traceback (most recent call last)
<ipython-input-423-f4aece42e018> in <module>
----> 1 y = x.copy()

/opt/homebrew/anaconda3/envs/mdanalysis/lib/python3.7/site-packages/MDAnalysis/core/universe.py in copy(self)
    354     def copy(self):
    355         """Return an independent copy of this Universe"""
--> 356         new = self.__class__(self._topology.copy())
    357         new.trajectory = self.trajectory.copy()
    358         return new

/opt/homebrew/anaconda3/envs/mdanalysis/lib/python3.7/site-packages/MDAnalysis/core/universe.py in __init__(self, *args, **kwargs)
    310 
    311             # generate and populate Universe version of each class
--> 312             self._generate_from_topology()
    313 
    314             # Load coordinates

/opt/homebrew/anaconda3/envs/mdanalysis/lib/python3.7/site-packages/MDAnalysis/core/universe.py in _generate_from_topology(self)
    365         # Put Group level stuff from topology into class
    366         for attr in self._topology.attrs:
--> 367             self._process_attr(attr)
    368 
    369         # Generate atoms, residues and segments.

/opt/homebrew/anaconda3/envs/mdanalysis/lib/python3.7/site-packages/MDAnalysis/core/universe.py in _process_attr(self, attr)
    887                   'segment': self._topology.n_segments}
    888         logger.debug("_process_attr: Adding {0} to topology".format(attr))
--> 889         if (attr.per_object is not None and len(attr) != n_dict[attr.per_object]):
    890             raise ValueError('Length of {attr} does not'
    891                              ' match number of {obj}s.\n'

/opt/homebrew/anaconda3/envs/mdanalysis/lib/python3.7/site-packages/MDAnalysis/core/topologyattrs.py in __len__(self)
    262     def __len__(self):
    263         """Length of the TopologyAttr at its intrinsic level."""
--> 264         return len(self.values)
    265 
    266     def __getitem__(self, group):

TypeError: len() of unsized object
```

**Code to reproduce the behavior**

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PDB, XTC

u = mda.Universe(PDB)
v = u.copy()
# or
u = mda.Universe(PDB, XTC)
v = u.copy()
```

**Current version of MDAnalysis**
0.19.2 and Python 3.7 (but it also fails in 2.7)

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #2178 #1926 

Changes made in this Pull Request:
 - can now initialise record_type attr off boolean values

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by richardjgowers** [comment]
@jbarnoud yeah it's fragile, so maybe could do something like that.  Downsides would be it would be an O(N) string operation and PDB parsing is already slow.  My argument would be that this stuff isn't really used by users but by the readers, so less checking is ok?

**Comment by jbarnoud** [comment]
@richardjgowers The `where` is already O(N) so it would not change the overall complexity. It would make it a bit slower, though; but will it be any significant? If it is, or really thought to be, I am fine with skipping the check. In this case, though, it may be worth having a word about it in the doc.

**Comment by richardjgowers** [comment]
@jbarnoud or I could even just store this as another `dtype=object` array, so whatever you put in you get back out.  Not sure why I encoded this as binary tbh... memory footprint reasons?

**Comment by richardjgowers** [comment]
@jbarnoud ok I simplified it, it's just a string field now

**Comment by jbarnoud** [comment]
Travis blocks because of #2180, but I guess Travis will block everything because of that issue.

**Pull request merged**
