### PR TITLE
pin numpy version for Python 3.4

### LINKED ISSUE #2066: Python 3.4 Travis fail due to unmet dependencies
The Python 3.4 tests are all failing now:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.15 -> *[track_features=blas_openblas]
  - numpy=1.15 -> python[version='>=3.7,<3.8.0a0'] -> tk[version='>=8.6.7,<8.7.0a0']
  - python=3.4
Use "conda info <package>" to see the dependencies for each package.
```

Examples:
- https://travis-ci.com/MDAnalysis/mdanalysis/jobs/144464939
- https://travis-ci.org/MDAnalysis/mdanalysis/jobs/425782569

Do we need to pin numpy or should we deactivate 3.4 tests?

cc: @richardjgowers @jbarnoud @tylerjereddy

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #2066 

Changes made in this Pull Request:
- `NUMPY_VERSION=1.14` (last version known to be compatible with  Python 3.4 when installed via conda and conda-forge channel)
- This is a band-aid and should be reverted if the dependencies  in the conda-forge packages have been corrected.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
I guessed the numpy version as 1.14 – let's see if Travis passes...

**Comment by orbeckst** [comment]
Looks like a failure about to happen https://travis-ci.org/MDAnalysis/mdanalysis/jobs/426532118
```
## Package Plan ##
  environment location: /home/travis/miniconda/envs/test
  added / updated specs: 
    - numpy=1.14
    - python=3.4
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    numpy-1.14.0               |py34_blas_openblas_200         9.0 MB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    openblas-0.2.20            |                8        17.0 MB  conda-forge
    libgfortran-3.0.0          |                1         281 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        26.2 MB
The following NEW packages will be INSTALLED:
    blas:        1.1-openblas                  conda-forge
    libgfortran: 3.0.0-1                       conda-forge
    numpy:       1.14.0-py34_blas_openblas_200 conda-forge [blas_openblas]
    openblas:    0.2.20-8                      conda-forge
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.14 -> python[version='>=2.7,<2.8.0a0'] -> *[track_features=debug]
  - numpy=1.14 -> python[version='>=2.7,<2.8.0a0'] -> tk=8.6
  - python=3.4
  - scikit-learn
Use "conda info <package>" to see the dependencies for each package.
```

@richardjgowers @zemanj can you figure out which version of numpy we should pin??

**Comment by kain88-de** [comment]
Your tests now all pass on travis. Not sure where there is a problem left

**Comment by zemanj** [comment]
The appveyor build now complains about conda not being the latest version.
`ci-helpers` claims "Installing miniconda latest [...]" but when conda is run it results in a `NativeCommandError` that looks like it is actually meant to be a warning:
```
+ conda create -n testing python=$env:PYTHON_VERSION pip setuptools whe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.10
  latest version: 4.5.11
Please update conda by running
    $ conda update -n base -c defaults conda
```
I have no clue whether running `conda update -n base -c defaults conda` under Windows will work. If it does, should be an easy fix then.

**Comment by zemanj** [comment]
Ok auto-updating conda in the appveyor build works but the warning is not related to the `NativeCommandError` thrown when the testing environment is set up by conda:
```PowerShell
conda create -n testing python=$env:PYTHON_VERSION pip setuptools wheel cython mock six biopython networkx joblib matplotlib scipy vs2015_runtime pytest mmtf-python GridDataFormats hypothesis pytest-cov codecov
...
+ conda create -n testing python=$env:PYTHON_VERSION pip setuptools whe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
...
```
Will try replacing `conda` by `conda.exe` according to [this](https://github.com/conda/conda/issues/6666#issuecomment-355616475) comment.

**Comment by zemanj** [comment]
No luck. Seems to be a typical case of [spiders](https://youtu.be/gNuuyiHAkeY).
I don't have a Windows installation available to reproduce this and get the traceback. @tylerjereddy Could you look into this?

**Comment by kain88-de** [comment]
You can also use ci-helpers with appveyor. Could make your life easier.

**Comment by zemanj** [comment]
@kain88-de Good call. Fiddling with this without being able to test it locally seems to me like fishing in muddy waters, though... @MDAnalysis/coredevs If anyone has access to a Windows box I'd be glad if you could jump in!

**Comment by kain88-de** [comment]
https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

you have a whole host of machines to access ;-)

**Comment by zemanj** [comment]
@kain88-de lol thx! Just to make sure I don't do anything stupid here: Setting an RDP password in `appveyor.yml` will basically make the RDP publicly accessible, but there should be no secrets to discover through that. Am I right?

**Comment by kain88-de** [comment]
No clue. I haven't ever used this. I just know almost all CI providers
offer this for troubleshooting purposes. The docs should tell you more.

**Comment by zemanj** [comment]
The reason seems to be that (crappy?) PowerShell interprets any writes to stderr (called Error stream in PS speak) as an error. I have it working in my MDA fork now but I'm trying to clean things up a bit before pushing this here.

**Comment by orbeckst** [comment]
This is still looking messy on Travis https://travis-ci.com/MDAnalysis/mdanalysis/jobs/144770514 – many packages are not installed from conda but via fallback-pip (scipy, scikit-learn, biopython). I am not sure what conda is trying to do and there are still
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.14 -> python[version='>=2.7,<2.8.0a0'] -> *[track_features=debug]
  - numpy=1.14 -> python[version='>=2.7,<2.8.0a0'] -> tk[version='>=8.6.8,<8.7.0a0']
  - python=3.4
  - scikit-learn
```
everywhere.

**Comment by zemanj** [comment]
@orbeckst True, there's certainly something fishy going on. I'll try to find some time to look into that tomorrow. In the meantime I'd suggest we use the fix as is since this is urgent.

**Comment by orbeckst** [comment]
Ok, then approve and merge the PR and open/reopen the issue, please. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Pull request merged**
