### PR TITLE
Syntax error corrected in psa.py Issue# 738

### PR DESCRIPTION
**Pull request by Saxenauts**
Corrected the syntax error as suggested, #738
First submission to mdanalysis, to understand the work flow.

### CODE REVIEW

**Comment by richardjgowers** [comment]
Hey

Looks good!

So with every fix you need to add a line to `package/CHANGELOG` that references the issue number too.

Because it's your first commit
 - add yourself to `package/AUTHORS`
 - add yourself alphabetically to `package/doc/sphinx/source/conf.py` in the authors variable

**Comment by Saxenauts** [comment]
Hi,

I've done as suggested, however I'm a bit dubious about the CHANGELOG formatting I've done, could you ascertain if that is how it is done?

Thanks

**Comment by kain88-de** [comment]
@Saxenauts the formating looks correct. 

But you started branch from `master` and not `develop`. That's the reason the CHANGELOG was empty for you and we have merge conflicts now.

There are two ways to fix this. Either rebase against `develop` or start a new branch and `cherry-pick` the two commits you have made. Fixing the conflicts in `CHANGELOG` along the way. Afterwards you can either force push to `Saxenauts:syntax_error` (updating this PR) or create a new branch on gitlab and open a new PR.

**Comment by kain88-de** [comment]
You can look online or in the git manuals how `rebase` and `cherry-pick` should be used.  If you don't find the information helpful you can also ask us.

**Pull request closed without merging**
