### PR TITLE
Edited fixtures in test_distances.py

### LINKED ISSUE #3759: Make fixtures in `test_distances` use return just the `Universe`  and not the trajectory as well
## Is your feature request related to a problem? ##

Coming from some discussion on #3730 and a comment by @orbeckst: https://github.com/MDAnalysis/mdanalysis/pull/3730#discussion_r910184346

The trajectory fixtures and their naming in `test_distances.py ` are slightly confusing as they return the universe **and** the trajectory.
This is confusing and a little bit of an anti-pattern.  An example is  the following fixture:

```python
@pytest.fixture()
def DCD_Universe():
    universe = MDAnalysis.Universe(PSF, DCD)
    trajectory = **universe.trajectory**
    return universe, trajctory
```

## Describe the solution you'd like ##

Move to only returning the `Universe ` and  have each test call trajectory if required. 
## Describe alternatives you've considered ##

Leave it the way it is?

### PR DESCRIPTION
**Pull request by hsadia538**
Fixes #3759 

Changes made in this Pull Request:
-Removed trajectory return calls
-Universe fixtures return universe only now
-Edited tests and called trajectory where needed

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by hsadia538** [comment]
Hello, @ojeda-e @hmacdope  can you take a look?
Also, what should I do about the code coverage?

**Review by ojeda-e — COMMENTED** [review]
Thanks for working on this @hsadia538!
It's looking good so far. I minor comment here:
- Usually, changes in tests are not included in the CHANGELOG. Since the CHANGELOG is mainly used to notify users about changes in the functionality, there is no need to add this fix.

Other than that it looks good to me. Maybe @hmacdope has more comments before approving.


Please wait for confirmation by @hmacdope.

**Comment by hsadia538** [comment]
@ojeda-e  alright, thanks.
I have updated the changelog as per your review.

**Review by hmacdope — APPROVED** [review]
~~Looks good to me! Thanks so much @hsadia538. @ojeda-e feel free to merge :)~~
EDIT: need to fix CHANGELOG but otherwise all good.

**Review by hmacdope — CHANGES_REQUESTED** [review]
Sorry forgot one last thing CHANGELOG

**Comment by ojeda-e** [comment]
Sorry, @hmacdope. Just to clarify, I told @hsadia538 to take the message off the CHANGELOG since changes in tests weren't relevant to include there (as I have pointed out in the past). Maybe @orbeckst can have a third opinion here?

**Comment by orbeckst** [comment]
I agree with @ojeda-e that we should not add a text section on internal test changes to CHANGELOG.

However, **add your GitHub handle to the list of authors contributing to the 2.3.0 release**.

**Comment by ojeda-e** [comment]
Thanks for confirming @orbeckst. 
@hsadia538 we'll approve once you add your handle as described above.

**Comment by hsadia538** [comment]
@ojeda-e  Thank you all for approving
I have added the handle to the list.

**Review by ojeda-e — CHANGES_REQUESTED** [review]
@hsadia538, you added the handle to the last release :)
Please move your handle to the 2.3.0 release section, check lines 16-17.

**Comment by hsadia538** [comment]
> @hsadia538, you added the handle to the last release :) Please move your handle to the 2.3.0 release section, check lines 16-17.

THANK YOU for catching that

**Comment by hsadia538** [comment]
@ojeda-e  done!

**Review by ojeda-e — APPROVED** [review]
Approved @hsadia538, congratulations! 
Thanks for your contribution to MDAnalysis! 🎉

**Comment by hsadia538** [comment]
@hmacdope  Can you approve as well
It is still showing pending requested changes.

**Comment by hsadia538** [comment]
@ojeda-e  what should I do about the codecov check? It's Failing with 94% coverage.

**Comment by hmacdope** [comment]
> @hmacdope Can you approve as well It is still showing pending requested changes.

@hsadia538 I will re-examine when all checks are finished, (the azure ones are still running).

In general it is important to be patient when waiting for approval or review, as in most cases the developers may not be able to get to a PR for several days as most have other full time jobs. :)

**Comment by hsadia538** [comment]
> > @hmacdope Can you approve as well It is still showing pending requested changes.
> 
> @hsadia538 I will re-examine when all checks are finished, (the azure ones are still running).
> 
> In general it is important to be patient when waiting for approval or review, as in most cases the developers may not be able to get to a PR for several days as most have other full time jobs. :)

Understood! Just wanted to remind becuase

**Review by hmacdope — APPROVED** [review]
Looks good to me! Don't worry about codecov, - 0.01% is not a big deal and may be a codecov problem given that I can't open the report. 

Thanks for your contribution @hsadia538

**Comment by hsadia538** [comment]
> > @hmacdope Can you approve as well It is still showing pending requested changes.
> 
> @hsadia538 I will re-examine when all checks are finished, (the azure ones are still running).
> 
> In general it is important to be patient when waiting for approval or review, as in most cases the developers may not be able to get to a PR for several days as most have other full time jobs. :)

Understood!

**Comment by hsadia538** [comment]
Thank you for reviewing! @hmacdope

**Pull request merged**
