### PR TITLE
Activate coverage report for analyses

### LINKED ISSUE #804: Coverage is not reported for the analyses
Since #743 got accepted, we mandate tests for the analysis modules. Yet, [coverall](https://coveralls.io/github/MDAnalysis/mdanalysis) does nor report the test coverage for these modules. This makes the review of PR like #803 more difficult.

### PR DESCRIPTION
**Pull request by jbarnoud**
Fixes #804

Changes made in this Pull Request:
 - Coverage is reported for analysis modules

We should expect a large drop in test coverage. The coverall badge will not look as bright.

PR Checklist
------------
 - [ ] ~~Tests?~~
 - [ ] ~~Docs?~~
 - [ ] ~~CHANGELOG updated?~~
 - [x] Issue raised/referenced?

See issue #804.

### CODE REVIEW

**Comment by kain88-de** [comment]
How much does this drop coverage?

**Comment by jbarnoud** [comment]
@kain88-de I do not know: I was waiting for travis to be done and to send the data to coverall.

**Comment by jbarnoud** [comment]
@kain88-de We go down to 79.53% coverage.

**Comment by richardjgowers** [comment]
@jbarnoud you'll want to update the readme, there's an explanation of how we measure coverage that can get simplified now

**Comment by kain88-de** [comment]
@jbarnoud that isn't to bad. I expected worse.

**Pull request merged**
