### PR TITLE
Smart repr and str for Groups 

### LINKED ISSUE #1223: Smart Reprs for Groups
In PR #1222 we fix the `repr`to match old behaviour, but this  makes `Residue/SegmentGroup` representation a little long as it will *always* print the repr of each member:

```python
u = mda.Universe(PSF, DCD)

rg = u.residues[:10]

<ResidueGroup [<Residue MET, 1>, <Residue ARG, 2>, <Residue ILE, 3>, <Residue ILE, 4>, <Residue LEU, 5>, <Residue LEU, 6>, <Residue GLY, 7>, <Residue ALA, 8>, <Residue PRO, 9>, <Residue GLY, 10>]>
```

TODO: 
 - Implement both `__str__` and `__repr__` for `AtomGroup`, `ResidueGroup`, and `SegmentGroup`.  Ideally this is done in a generic way in `GroupBase`
 - `__repr__` is to be short and terse (similar to how AtomGroup is now) ie `'<ResidueGroup with 5 Residues>'`
 - `__str__` is to be long, pretty and informational, similar to how `ResidueGroup` is currently, so `AtomGroup` needs a similar treatment.
 - the `str` representation needs to truncate itself if the Group is over 10 members, and instead only show the first and last three members in a verbose way.  This is similar to how long numpy arrays truncate the repr of themselves:

```python
np.arange(10000)
array([   0,    1,    2, ..., 9997, 9998, 9999])

```

### PR DESCRIPTION
**Pull request by jeiros**
Fixes #1223 

Changes made in this Pull Request:
 - Added a smart `__str__` method in `GroupBase`

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
I squash-merged #1222 – please rebase your PR against develop.

**Comment by jeiros** [comment]
Ok, rebased it. Not too sure if the commits are showing twice now because I had started working on another branch, which I then renamed to `issue-1223-smart-reps` to be inline with the PR.

**Comment by richardjgowers** [comment]
Hmm ok, I think what's happened here is you branched from the PR branch, and then that got squashed so the commits are different.  You could probably rebase a lot to fix this, or just branch of the latest version of develop then copy in the changes you've made here (what I'd do).

Apart from that, there's a `repr(sg)` test that I think got missed, but otherwise good

**Comment by jeiros** [comment]
Hi @richardjgowers 
If I branch out of dev and copy there the changes, I will need to open a new PR to merge it back into dev, won't I? I'll take a look at the test that's failing.

**Comment by richardjgowers** [comment]
@jeiros you could do `git push -f` (usually evil, good here) to overwrite this branch in your repo, then this PR will lose memory of this weird branch and will only know the new fresh branch

**Comment by jeiros** [comment]
Hi @richardjgowers 
Travis is failing on the [full setup](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/206957284), but I don't think it's related to the changes introduced in my PR. It looks like it's hit the time limit and has been closed

**Pull request merged**
