### PR TITLE
ParmEdConverter: fix NameError when catching NoDataError

### PR DESCRIPTION
**Pull request by cbouy**
Converting to parmed when the AtomGroup doesn't have a resname leads to a NameError: the current code tries to catch the NoDataError but because NoDataError is not imported from exceptions.py it triggers a `NameError: name 'NoDataError' is not defined`

Changes made in this Pull Request:
 - import NoDataError from exceptions

Is the changelog update needed here ?

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by lilyminium** [comment]
Oops, thanks for finding this. Could you please add a test as well so the tests will catch it in the future as well?

**Comment by orbeckst** [comment]
You don't need to update the CHANGELOG as this just fixes something that hadn't been released yet. (We don't absolutely strictly adhere to what I just said because our release cycles are so stretched out that we need to track bugs in develop and often fix issues that never show up in a released version. But in the case here a CHANGELOG entry seems overkill.)

**Review by orbeckst — CHANGES_REQUESTED** [review]
Can you please add a test?

Not for testing that your fix worked but rather because it indicates that we didn't test a possible (and perhaps not uncommon) failure mode earlier.

**Comment by cbouy** [comment]
Sorry for the delay and the messed up commits, should be fixed now

**Review by orbeckst — APPROVED** [review]

**Comment by orbeckst** [comment]
Thank you!

**Pull request merged**
