### PR TITLE
WIP, TST: add 32-bit support

### LINKED ISSUE #2342: Tests on i686: ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'int'
Related to #1362, many test fail on i686 with something like:
```
core/test_wrap.py:187:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../../BUILDROOT/python-MDAnalysis-0.20.0-1.fc31.i386/usr/lib/python3.7/site-packages/MDAnalysis/core/groups.py:2313: in residues
    rg = self.universe.residues[unique_int_1d(self.resindices)]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'int'
MDAnalysis/lib/_cutil.pyx:52: ValueError
____________ TestWrap.test_wrap_duplicates[True-com-group-segments] ____________
[gw4] linux -- Python 3.7.4 /usr/bin/python3
self = <MDAnalysisTests.core.test_wrap.TestWrap object at 0xe12b56cc>
level = 'segments', compound = 'group', center = 'com', is_triclinic = True
    @pytest.mark.parametrize('level', ('atoms', 'residues', 'segments'))
    @pytest.mark.parametrize('compound', ('atoms', 'group', 'segments',
                                          'residues', 'molecules', 'fragments'))
    @pytest.mark.parametrize('center', ('com', 'cog'))
    @pytest.mark.parametrize('is_triclinic', (False, True))
    def test_wrap_duplicates(self, level, compound, center, is_triclinic):
        # get a pristine test universe:
        u = UnWrapUniverse(is_triclinic=is_triclinic)
        # select molecule 12:
        group = u.atoms[39:47]
        # select the rest of the universe's atoms:
        rest = u.atoms[:39]
        # select topology level:
        if level == 'residues':
            group = group.residues
        elif level == 'segments':
>           group = group.segments
```

List of all errors [here](https://github.com/MDAnalysis/mdanalysis/files/3580628/build_i686.txt).

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #2342

Currently WIP, with my fork feature branch `fix_32bit` reducing total failures to 137 from around 1000 or so. I will first aim to add 32-bit testing to CI.

I'm currently stuck trying to get the `testsuite/MDAnalysisTests/core/test_wrap.py` tests passing--some of the C++ stuff in `_cutil.pyx` is not friendly for Python maintainers...

Anyway, will aim to get the large number of 32 bit test failures reproduced in CI here for demo purposes, then will try pushing in the WIP improvements to drop the fail count down...

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Initial Azure CI output confirms 32-bit testing with failures related to buffer dtype mismatches as one might excpect, with 

`= 1085 failed, 14289 passed, 84 skipped, 2 xfailed, 2 xpassed, 27795 warnings, 27 error in 758.51s (0:12:38) =`

I'll now push in some of the WIP improvements from my feature branch to demonstrate better results. I should also improve out test code line to produce xml output for the summary, but that can wait for now.

**Comment by tylerjereddy** [comment]
Ok, the improved results are now clearly visible in 32-bit Azure CI run:

`= 137 failed, 15264 passed, 84 skipped, 2 xfailed, 2 xpassed, 27939 warnings in 695.13s (0:11:35) =`

@zemanj may be able to help for some of the `testsuite/MDAnalysisTests/core/test_wrap.py` failures--there's an awful lot of integer typing in `_cutil.pyx`

I'll try to take a look at some other failures as time permits...

**Comment by richardjgowers** [comment]
I’m partly responsible for cutil too, I’ll have some time in the next week to dig into that.
  

  
  

  
  
>

**Comment by tylerjereddy** [comment]
Pushed in some more fixes -- CI should hopefully confirm the new result I get locally for full test suite:

`= 89 failed, 15312 passed, 84 skipped, 2 xfailed, 2 xpassed, 27935 warnings in 535.94s (0:08:55) =`

**Comment by tylerjereddy** [comment]
How much is the slow down in practice? Without benchmarks we're just speculating I think. It may be modest.

**Comment by tylerjereddy** [comment]
I think a top-level / initialization variable could be used to detect if you're on a 32-bit platform & if not the astype calls can all be no-ops that return the same type.

**Comment by tylerjereddy** [comment]
Superseded by #2696, so closing. We might want to extract the addition of the 32-bit Linux test to CI from here though.

**Pull request closed without merging**
