### PR TITLE
Deprecate PSA and replace with PathSimAnalysis mdakit

### PR DESCRIPTION
**Pull request by IAlibay**
Towards #4308

Changes made in this Pull Request:
 - Remove local PSA code in favour of importing directly from PathSimAnalysis

TODO:
 - [x] Remove tests
 - [x] Add raising of warning
 - [x] Decide what to do with docs
 - [x] Fix py3.12 deployment upstream

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4403.org.readthedocs.build/en/4403/

### CODE REVIEW

**Comment by IAlibay** [comment]
Discussion points:

1. Tests: I opted to just remove all the tests except from the ones checking for the module import warning. The idea here is that we then don't have to duplicate efforts trying to fix two things at the same time. However, it does mean that we're running CI less often / we're less likely to pick up things like NumPy 2.0 future issues.
2. Docs: Again here I opted to remove the docs and just point to pathsimanalysis, so that we can keep everything synced up. However it means that the docs don't really do much anymore.

**Comment by IAlibay** [comment]
Ok this is good to go - discussion from last week's call was that we would remove docs & tests and just intersphinx to the kits.

**Review by orbeckst — APPROVED** [review]
I agree with the decisions & looks fine to me. 

Docs show the deprecation and link to PSA kit ✅

**Comment by IAlibay** [comment]
Thanks @orbeckst !

**Pull request merged**
