### PR TITLE
Two doctest fixes

### PR DESCRIPTION
**Pull request by ljwoods2**
Fixes  #3925 

Changes made in this Pull Request:
 -  Fixed doctests in overview.rst
 -  Fixed doctests in atomicdistances.py 

PR Checklist
------------
 - [X] Tests?
 - [X] Docs?
 - [X] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4366.org.readthedocs.build/en/4366/

### CODE REVIEW

**Review by RMeli — CHANGES_REQUESTED** [review]
Thanks @ljwoods2, LGTM. Please update the `CHANGELOG`, then I think it's good to go.

**Comment by RMeli** [comment]
Thanks @ljwoods2. Can you please also add a line explaining the fix to the CHANGELOG, under the "Fixes" entry?

**Comment by RMeli** [comment]
Thanks @ljwoods2. Please solve the conflicts, the `AUTHORS` and `CHANGELOG` files have been modified in the meantime.

**Comment by ljwoods2** [comment]
@RMeli Got it, thank you for being patient and explaining the process!

**Review by RMeli — APPROVED** [review]

**Pull request merged**
