### PR TITLE
fixed docs for PDBParser "conect" keyword

### LINKED ISSUE #1246: Doc for keyword *bonds* of PDBWriter is wrong
The documentation of `PDBWriter.__init__` tells:

```
*bonds*
           write bonds to the PDB file as CONECT_ records [``False``]
```

This is in contradiction with the signature of the signature that tells that the default value for the argument is `"conect"`. It is also in contradiction with the code of `PDBWriter._write_pdb_bonds`:

```python
        # Write out only the bonds that were defined in CONECT records
        if self.bonds == "conect":
            bonds = ((bond[0].index, bond[1].index) for bond in bondset if not bond.is_guessed)
        elif self.bonds == "all":
            bonds = ((bond[0].index, bond[1].index) for bond in bondset)
        else:
            raise ValueError("bonds has to be either None, 'conect' or 'all'")
```

### PR DESCRIPTION
**Pull request by orbeckst**
- fixes #1246
- supercedes and closes PR #1279 by @Shtkddud123
- added @Shtkddud123 to AUTHORS
- updated CHANGELOG

PR Checklist
------------
 - n/a Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Please *merge* (no rebasing) in order to keep @Shtkddud123 as commit author.

**Comment by richardjgowers** [comment]
Looks like this got squashed instead of merged or something

**Comment by kain88-de** [comment]
Yeah that was a squash and merge. Sorry about that I thought github would still use the original author in as in the git-log instead of using the PR author.

**Comment by orbeckst** [comment]
We had this experience before, thus my comment https://github.com/MDAnalysis/mdanalysis/pull/1329#issuecomment-298433558.

Please amend the author information on the commit in develop. You'll need to unprotect develop, amend the author, and force push. Email the developer list.

**Comment by kain88-de** [comment]
done

**Comment by orbeckst** [comment]
Thanks!

**Pull request merged**
