### PR TITLE
Fixed MMTFParser using chain_name not chain_id field

### LINKED ISSUE #1107: MMTF parser doesn't work well.
### Expected behaviour
show all residues in A chain:

### Actual behaviour
['HOH', 'HOH', 'HOH']

### Code to reproduce the behaviour

``` python
from MDAnalysis.coordinates.MMTF import fetch_mmtf
s=fetch_mmtf("1kq2")
s.A.residues
list(r.resname for r in s.A.residues)

```

### Currently version of MDAnalysis:
0.16.0-dev0

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #1107

PR Checklist
------------
 - [ ] Tests?
 - n/a Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
Will this also change the behavior I see in #1110?

**Comment by richardjgowers** [comment]
Not really.  The raw mmtf file has 10 chains
```
In [1]: import mmtf

In [2]: mmtf.fetch('1nmu')
Out[2]: <mmtf.api.mmtf_reader.MMTFDecoder at 0x7f56cc0d9d50>

In [3]: top = mmtf.fetch('1nmu')
top.
In [4]: top.num_chains
Out[4]: 10
```

**Comment by richardjgowers** [comment]
I think this ties in with #1108 a little and isn't really finished.

Ideally we should use both the `chain_id_list` and `chain_name_list` fields, but I don't know what the difference between these two is.  Maybe someone who works with bio systems (@dotsdl @kain88-de ) could figure out what the difference is and what we should use as the chainID?

**Comment by kain88-de** [comment]
@arose Can you explain what the difference between `chain_id_list` and `chain_name_list` is in the new mmtf format?

**Comment by arose** [comment]
@kain88-de sure! From the [spec](https://github.com/rcsb/mmtf/blob/master/spec.md#chain-data): "For storing data from mmCIF files the chainIdList field should contain the value from the label_asym_id mmCIF data item and the chainNameList the auth_asym_id mmCIF data item. In PDB files there is only a single name/identifier for chains that corresponds to the auth_asym_id item. When there is only a single chain identifier available it must be stored in the chainIdList field."

So if you want the same as in the corresponding PDB files, use chainNameList.

**Comment by kain88-de** [comment]
So with the PDB entry in question I just checked. The `chain_name_list` we use right now has the correct entries for the chain.

**Comment by kain88-de** [comment]
The original proglem is that `mmtf_model.A` doesn't return chain A

**Comment by kain88-de** [comment]
The bug of the user is fixed using the correct selection `mmtf_model.select_atoms('protein and segid A')`

**Comment by kain88-de** [comment]
@arose thanks for you answer. Btw is there an official python library for mmcif as well?

**Comment by arose** [comment]
there is pdbx, see http://mmcif.wwpdb.org/docs/sw-examples/python/html/

**Comment by kain88-de** [comment]
Closing this as the issue isn't with the mmtf parser

**Pull request closed without merging**
