### PR TITLE
public function listed

### LINKED ISSUE #3655: lib.distances.minimize_vectors is not documented
## Expected behavior ##

Any public functions appear in the docs. In particular https://github.com/MDAnalysis/mdanalysis/blob/3a03af01886977aa53d2a43086cae86c45038738/package/MDAnalysis/lib/distances.py#L1565 should.

## Actual behavior ##

https://docs.mdanalysis.org/2.2.0-dev0/documentation_pages/lib/distances.html#module-MDAnalysis.lib.distances does not contain `minimize_vectors`

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.2.0-dev

### PR DESCRIPTION
**Pull request by aditi2906**
Fixes #3655

Changes made in this Pull Request:
Listed the function "minimize_vectors()"
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Review by richardjgowers — APPROVED** [review]

**Review by IAlibay — CHANGES_REQUESTED** [review]
The versionchanged entry in the docstring render for minimized_vectors isn't showing properly - can you add an extra empty line before it please?

**Comment by IAlibay** [comment]
There's a deeper issue with the azure runners - double checking

**Comment by IAlibay** [comment]
> There's a deeper issue with the azure runners - double checking

The issue was with py3.7 picking up the recent networkx release candidate. Since we just ditched py3.7 then updating against develop should do the trick.

**Review by IAlibay — APPROVED** [review]
Thanks, lgtm (as long as CI returns green this time around)

**Pull request merged**
