### PR TITLE
Try uppercase atom names when guessing the mass

### LINKED ISSUE #2265: Metal Atoms in PDB not properly recognized
**Expected behavior**

I expect
```
In [1]: import MDAnalysis as mda                                                                                                                                                         
In [2]: u = mda.Universe("example.pdb") 
```
to work with the PDB file below.

**Actual behavior**

The following warnings are issued:
```
/users/lina3015/software/python/mdanalysis-develop/package/MDAnalysis/topology/guessers.py:73: UserWarning: Failed to guess the mass for the following atom types: Ca
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/users/lina3015/software/python/mdanalysis-develop/package/MDAnalysis/topology/guessers.py:73: UserWarning: Failed to guess the mass for the following atom types: Fe
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/users/lina3015/software/python/mdanalysis-develop/package/MDAnalysis/topology/guessers.py:73: UserWarning: Failed to guess the mass for the following atom types: Mg
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
```

The problem comes from the fact that the name of the atoms are `Mg, Fe, Ca` instead of `MG, FE, CA`. [Open Babel](https://github.com/openbabel/openbabel) 2.4.1 outputs the name of the elements with the second letter in lower case.

The problem is discussed in Issue #1808.

**Code to reproduce the behavior**

PDB file:
```
HEADER Example
SEQRES   1 A  3    SER LYS GLY
ATOM      1  N   SER A   2      13.761  13.879 -11.601  1.00 66.03           N
ATOM      2  HN1 SER A   2      12.949  13.271 -11.831  1.00  0.00           H
ATOM      3  HN2 SER A   2      14.536  13.296 -11.225  1.00  0.00           H
ATOM      4  HN3 SER A   2      13.478  14.583 -10.889  1.00  0.00           H
ATOM      5  CA  SER A   2      14.219  14.576 -12.829  1.00 65.42           C
ATOM      6  HA  SER A   2      14.524  13.844 -13.577  1.00  0.00           H
ATOM      7  C   SER A   2      15.409  15.463 -12.478  1.00 64.57           C
ATOM      8  O   SER A   2      16.554  15.049 -12.613  1.00 64.91           O
ATOM      9  CB  SER A   2      13.078  15.409 -13.424  1.00 66.10           C
ATOM     10  HB1 SER A   2      12.909  16.282 -12.794  1.00  0.00           H
ATOM     11  HB2 SER A   2      12.173  14.803 -13.453  1.00  0.00           H
ATOM     12  OG  SER A   2      13.388  15.841 -14.740  1.00 67.19           O
ATOM     13  HG  SER A   2      12.635  16.375 -15.097  1.00  0.00           H
ATOM     14  N   LYS A   3      15.133  16.673 -12.004  1.00 63.15           N
ATOM     15  H   LYS A   3      14.140  16.965 -11.905  1.00  0.00           H
ATOM     16  CA  LYS A   3      16.189  17.600 -11.619  1.00 61.61           C
ATOM     17  HA  LYS A   3      17.177  17.202 -11.851  1.00  0.00           H
ATOM     18  C   LYS A   3      16.032  17.823 -10.119  1.00 59.63           C
ATOM     19  O   LYS A   3      16.667  17.140  -9.322  1.00 59.93           O
ATOM     20  CB  LYS A   3      16.053  18.916 -12.392  1.00 62.69           C
ATOM     21  HB1 LYS A   3      15.627  18.694 -13.371  1.00  0.00           H
ATOM     22  HB2 LYS A   3      15.374  19.566 -11.841  1.00  0.00           H
ATOM     23  CG  LYS A   3      17.362  19.663 -12.601  1.00 63.33           C
ATOM     24  HG1 LYS A   3      17.713  20.040 -11.641  1.00  0.00           H
ATOM     25  HG2 LYS A   3      18.102  18.976 -13.013  1.00  0.00           H
ATOM     26  CD  LYS A   3      17.183  20.833 -13.559  1.00 64.34           C
ATOM     27  HD1 LYS A   3      16.514  21.561 -13.099  1.00  0.00           H
ATOM     28  HD2 LYS A   3      18.155  21.294 -13.732  1.00  0.00           H
ATOM     29  CE  LYS A   3      16.593  20.409 -14.911  1.00 65.03           C
ATOM     30  HE1 LYS A   3      16.367  21.308 -15.484  1.00  0.00           H
ATOM     31  HE2 LYS A   3      15.672  19.857 -14.725  1.00  0.00           H
ATOM     32  NZ  LYS A   3      17.501  19.548 -15.727  1.00 65.45           N
ATOM     33  HZ1 LYS A   3      18.382  20.064 -15.924  1.00  0.00           H
ATOM     34  HZ2 LYS A   3      17.718  18.678 -15.200  1.00  0.00           H
ATOM     35  HZ3 LYS A   3      17.033  19.304 -16.623  1.00  0.00           H
ATOM     36  N   GLY A   4      15.116  18.721  -9.756  1.00 56.92           N
ATOM     37  H   GLY A   4      14.586  19.222 -10.498  1.00  0.00           H
ATOM     38  CA  GLY A   4      14.827  19.029  -8.362  1.00 53.00           C
ATOM     39  HA1 GLY A   4      14.484  20.063  -8.318  1.00  0.00           H
ATOM     40  HA2 GLY A   4      14.024  18.367  -8.038  1.00  0.00           H
ATOM     41  C   GLY A   4      15.964  18.883  -7.376  1.00 49.65           C
ATOM     42  O   GLY A   4      16.115  17.829  -6.749  1.00 50.49           O
TER
HETATM 5935 MG    MG     1      20.414  28.113  14.934  1.00 25.89          Mg
HETATM 5936  O   HOH     2      20.617  18.139 -10.469  1.00 44.84           O
HETATM 5937  O   HOH     3      19.500  17.550 -12.901  1.00 49.35           O
HETATM 5938  O   HOH     4      13.990  17.613  -4.873  1.00 38.69           O
HETATM 6932 FE    FE     1       7.237 -13.445  41.879  1.00 16.53          Fe
HETATM 6933  O   HOH     2      12.331 -25.176  49.589  1.00 11.03           O
HETATM 6934  O   HOH     3       0.846 -28.056  24.965  1.00  3.98           O
HETATM 6935  O   HOH     4      -1.805 -28.400  30.994  1.00  7.38           O
HETATM 3744 CA    CA     1      18.911  11.652   7.836  1.00  2.33          Ca
HETATM 3745 CA    CA     2      18.013   3.000  21.617  1.00 13.46          Ca
HETATM 3746  O   HOH     3      19.129  20.805   2.497  1.00 13.12           O
HETATM 3747  O   HOH     4      10.694  18.824  22.901  1.00 14.21           O
HETATM 3748  O   HOH     5      24.830  32.697   7.145  1.00 17.46           O
END
```

**Currently version of MDAnalysis**

- Which version are you using? 0.19.3-dev
- Which version of Python (`python -V`)? Python 3.7.3
- Which operating system? Linux Ubuntu 18/macOS 10.14

### PR DESCRIPTION
**Pull request by RMeli**
Fixes #2265

This is an attempt to get rid of the `UserWarning: Failed to guess the mass for the following atom types: Ca` warning when PDB files contain metal atoms. 

It is probably not the best approach, but it's the one that minimize side effects (such as changing `tables.py`). Please let me know if you want to solve issue #2265 in a different way.

Changes made in this Pull Request:
 - Try uppercase atom names when guessing the mass

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by richardjgowers** [comment]
I think there's a thing with carbon-alpha which will make this cause lots of tears down the line @orbeckst ?

**Comment by RMeli** [comment]
Yes, I followed the discussion in Issue #1808. However `CA` has a mass of `40.08000` in `TABLE_MASSES `. Additionally, in `TABLE_ATOMELEMENTS`, which is described at the *translation of atomnames to types/element *, `CAL`, `C0` and `CA2+` are all mapped to `CA`.

I agree we probably need to be more careful and I'm happy to re-work this PR in order to solve the problem at a deeper level. 

Maybe the element names in `tables.py` should only be the actual element names (first letter uppercase, second letter lowercase) so that there is no confusion? The problem of `CA` being alpha-carbon could then be solved by the parser if it needs to guess the element (because that information is omitted) or if the element name provided is not the standard name; for example `CA` as `HETATM` is `Ca` while `CA` in a chain is alpha-carbon, or something on these lines.

However, I'm by no means very informed on all the corner cases and therefore I'd be happy to discuss it further and possibly fix it the way you prefer.

**Comment by RMeli** [comment]
Thanks for pointing out your PR, @lilyminium. I _think_ you PR was already in my [bugfix/metals](https://github.com/RMeli/mdanalysis/commits/bugfix/metals), but I'll double check on my laptop.

I think it would be nice to have a standard and clean `tables.py` (where there is no ambiguity on the element name: `C` is any carbon, `Ca` is calcium, `CA` does not exist) and then refine the atom guess in the parsers for different file formats (for which the complexity and the details of this guess will be different). For example passing the residue name for PDB files sound a good idea to me (but I'm by no mean an expert)!

**Comment by lilyminium** [comment]
My apologies, I misunderstood the issue. @richardjgowers by the point an atom's element is Ca (either through user/file specification or element guessing), it makes sense that the atom's mass should correspond. If it's causing carbon-alpha grief, it would be better to fix the element guessing rather than hack the mass lookup.

I agree with you @RMeli,  the capitalisation of elements is a bit all over the place and results in unnecessary errors like #1808 and #2265 . I see I've contributed to this confusion by uppercasing `tables.elements`. Maybe everything should be in Capitalised style?

**Comment by RMeli** [comment]
> So maybe a better solution is for PDBParser to have a better element guesser (one that actually ensures that elements are returned too...), then mass->element should just be a trivial dict lookup?

@richardjgowers, I agree. This is probably the best option.

I think the required steps are the following:

* Duplicate all properties in `tables.py` where the element name is capitalised (for temporary backward compatibility) and associate them to the correct element name
* Improve the atoms type guess in `PDBReader`
  * Try to use the element name PDB field, if present
  * Raise a warning and use other information if the element name PDB field is not present 
* Improve the atom type guess for other formats, if needed
* Cleanup `tables.py` so that they only contain standard element names

**Comment by orbeckst** [comment]
I agree with the general discussion that **parsers should be assigning elements** to atoms because this the place to encode domain-specific knowledge. 

There's the caveat that coarse grained systems cannot be assigned an element.

People will likely also want to have a way to disable any guessing, e.g., so that they can fix-up the topology by themselves.

If not having elements is not a big deal, but having no masses will lead to AtomGroup and friends not having a whole bunch of methods (see also #1845) . So we should have a decent way to warn users and give suggestions what to do. Something along the line of: "you can manually assign uniform mass = 1 to all particles with ... or better: use a topology format that contains masses explicitly."

**Comment by RMeli** [comment]
I agree that the guessing should be controllable by the user. I could give it a try in the next few weeks.

**Comment by richardjgowers** [comment]
thanks @RMeli !

**Pull request merged**
