### PR TITLE
WIP: ten2sixteen.py

### PR DESCRIPTION
**Pull request by tylerjereddy**
This is a work in progress pull request to update the MDAnalysis `lib2to3`-based migration code originally written to facilitate the transition of scripts used before version `0.11` to the updated API. We are now preparing to further facilitate the transition to the new topology system described in #363 by providing similar automated script conversion from pre-`0.16` code to match the new API. This will involve renaming `ten2eleven.py` to `ten2sixteen.py` and adding / updating appropriate fixers.

The documentation of the API changes (https://github.com/MDAnalysis/mdanalysis/wiki/Issue363-Changes) is also a work in progress and should be built up as the automated conversion code is developed.

Tasks:
- [ ] update CHANGELOG once the full set of adjustments are made in `ten2sixteen`
- [x] rename `ten2eleven.py` to `ten2sixteen.py`
- [ ] update the wiki page (https://github.com/MDAnalysis/mdanalysis/wiki/Migrating-MDAnalysis-code-with-ten2eleven.py) to reflect the above name change
- [x] The docstrings and comments of current fixers (`MDAnalysis/migration/fixes/`) need to reflect the name change `ten2eleven.py` to `ten2sixteen.py` 
- [ ] New Fixers Needed (sublist needs expansion)
  - [ ] Change all `.positions` calls on anything that isn't an `AtomGroup` to `.atoms.positions` (how will the fixer know that any arbitrarily named `ResidueGroup` and `SegmentGroup` is not an `AtomGroup`? May be possible, otherwise inject warning / comment code?)

### CODE REVIEW

**Comment by orbeckst** [comment]
@dotsdl and @richardjgowers can you help with the list of required fixers?

**Comment by richardjgowers** [comment]
I'm not sure there's a simple list of find and replaces that need doing.  For example, `Residue.positions` needs changing to `Residue.atoms.positions`, but `AtomGroup.positions` is fine.  And I think the 2to3 framework we used is just doing very complicated regex like changes iirc?

We could have a list of properties that get prefixed by `.atoms` so that they still work, but this would make lots of ugly `AtomGroup.atoms.positions` instances

**Comment by orbeckst** [comment]
Am Apr 17, 2016 um 15:36 schrieb Richard Gowers <notifications@github.com>:

> And I think the 2to3 framework we used is just doing very complicated regex like changes iirc?

No, it parses the AST, and it might know about instances but Tyler knows more.

**Comment by tylerjereddy** [comment]
It would certainly be more challenging than most of the fixers I've written so far. I suspect the strategy would be something like this:

1. Parse the AST tree for `Residue` objects based on usage of i.e., `.residues`, and append the associated variable names to a list.
2. Do a second AST parse of the module for method / property calls on those variable names that have a new signature and replace as needed.

But I do wonder if the object tracking could be so robust that it handles, for example, taking a list of residue objects and then indexing that list to generate a single residue object, which is then called using the old approach. Probably, though not likely fun to write.

**Comment by richardjgowers** [comment]
@tylerjereddy that sounds like it'd work, but maybe it's overly complicated.   I think, if you can just write a fixer for anything that's decorated with  `warn_atom_property` to get prefixed by `.atoms` that should do it...(@dotsdl ?)

**Comment by richardjgowers** [comment]
I think we didn't end up needing this because the changes we made in 16 weren't really applicable to this?

**Pull request closed without merging**
