### PR TITLE
test reorganization: analysis and coordinates

### PR DESCRIPTION
**Pull request by orbeckst**
- new subdirectory analysis/
- split the unwieldy test_analysis.py into separate
  files and removed superfluous imports (and got rid of
  the awful 'from numpy.tests import *': use only classes/
  functions that are actually needed)
- also moved test_mol2 and test_pdbqt to the coordinates/
  directory
- part of work on reorganizing tests #466
- todo: fixing tempfile handling #440
        density tests #410
        issues with PSA tests (#487 and #440)

### CODE REVIEW

**Comment by mnmelo** [comment]
Ah dang! precisely the test file I just used in the wiki examples! ;)

**Comment by orbeckst** [comment]
Am Oct 18, 2015 um 15:30 schrieb mnmelo <notifications@github.com>:

> Ah dang! precisely the test file I just used in the wiki examples!

Sorry, I know, but had to be done.

**Comment by richardjgowers** [comment]
Looks good, the todos are other issues, so am I good to merge this now? @orbeckst

**Comment by orbeckst** [comment]
Merge away. 

--
Oliver Beckstein
email: orbeckst@gmail.com
skype: orbeckst


Am Oct 18, 2015 um 18:10 schrieb Richard Gowers <notifications@github.com>:

**Comment by kain88-de** [comment]
@orbeckst did you check that coverage stayed the same? According to coveralls this PR slightly decreased coverage

https://coveralls.io/builds/3875543

Was this because you rewrote some of the tests?

**Comment by orbeckst** [comment]
Need to check.

--
Oliver Beckstein
email: orbeckst@gmail.com
skype: orbeckst


Am Oct 19, 2015 um 10:00 schrieb kain88-de <notifications@github.com>:

**Pull request merged**
