### PR TITLE
Added ENT file extension to PDBReader, Writer and Parser.

### LINKED ISSUE #834: ENT efile extension should be recognized as PDB
".ent" is an extension that use to be common for PDB files. It is still in use in the PDB ftp server. If you download a copy of the whole PDB, you get file names pdbXXXX.ent.gz.

### Expected behaviour

Files with '.ent' as file extension are treated as PDB files.

### Actual behaviour

The extension is not recognized:

```
ValueError: Cannot autodetect topology type for file '/coarse/jon/pdb/qs/pdb1qsh.ent.gz' (file extension could not be parsed).
           You can use 'Universe(topology, ..., topology_format=FORMAT)' to explicitly specify the format and
           override automatic detection. Known FORMATs are:
           dict_keys(['DMS', 'XPDB', 'PDBQT', 'DATA', 'TPR', 'GRO', 'CONFIG', 'PSF', 'TOP', 'XYZ', 'HISTORY', 'CRD', 'PDB', 'GMS', 'MOL2', 'PQR', 'XML', 'PRMTOP', 'PARM7', 'Permissive_PDB'])
           See http://docs.mdanalysis.org/documentation_pages/topology/init.html#supported-topology-formats
           For missing formats, raise an issue at http://issues.mdanalysis.org
```

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe('pdb1bta.ent.gz')

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.14.1-dev0 but I did not see recent changes on that respect.

### PR DESCRIPTION
**Pull request by jdetle**
Fixes #834 

Changes made in this Pull Request:
 - Added ENT file format to PDB reader, writer and parser
 - Updated tests to check succesful loading of ENT file format

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

Updated tests to check succesful loading of PDB file from ENT extension.

Updated CHANGELOG

### CODE REVIEW

**Comment by richardjgowers** [comment]
I think the failure is somewhere in the setup.py for testsuite you need to add the .ent file, there'll be rules for `*.pdb` etc, so add one for ent.

The other thing is that we really need to put the test data on a diet, so could we shrink the .ent file to ~5 lines?

**Comment by jbarnoud** [comment]
From what I see, you may have to add `data/*.ent` around line 170 of `testsuite/setup.py` so the ENT file get picked during the install. (Which is what @richardjgowers just said above).

Beside that, thanks for the fix, I needed it to work.

**Comment by jdetle** [comment]
@jbarnoud I believe this is ready to be merged.

**Comment by jbarnoud** [comment]
Could you rename the ent file so nobody in the future gets surprised with a 1 residue long ribinuclease inhibitor? 
Except for that, I used your branch yesterday and it worked well. So I'll merge as soon as the file is renamed. 
Le 29 avr. 2016 2:55 AM, John Detlefs <notifications@github.com> a écrit :@jbarnoud I believe this is ready to be merged.

**Comment by orbeckst** [comment]
Does this also work for topologies?

Please update the list of supported file formats (and then check the 'docs' checkbox)
- trajectory formats
- topology formats

**Comment by jdetle** [comment]
I don't know how I caused the errors showing up in Travis, anyone know what is going on?

**Comment by kain88-de** [comment]
What errors?

**Comment by jbarnoud** [comment]
There was an error for some builds, I restarted these builds and they passed.

**Comment by jdetle** [comment]
I'm headed to class but they should show up in the Travis CI build report
On Fri, Apr 29, 2016 at 2:52 PM kain88-de <notifications@github.com> wrote:

> What errors?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/pull/835#issuecomment-215891388>
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by jdetle** [comment]
Weird, any idea why that happened?
On Fri, Apr 29, 2016 at 2:56 PM Jonathan Barnoud <notifications@github.com>
wrote:

> There was an error for some builds, I restarted these builds and they
> passed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/pull/835#issuecomment-215892310>
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by jbarnoud** [comment]
I got similar errors after I merged #809. I do not know where they come from. For the records, the builds which failed were the full build on linux and the minimal one on macos.

**Comment by jdetle** [comment]
This seems like something we should look into reproducing.
On Fri, Apr 29, 2016 at 3:00 PM Jonathan Barnoud <notifications@github.com>
wrote:

> I got similar errors after I merged #809
> <https://github.com/MDAnalysis/mdanalysis/pull/809>. I do not know where
> they come from. For the records, the builds which failed were the full
> build on linux and the minimal one on macos.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/pull/835#issuecomment-215893296>
>
-- 
Have a wonderful day,
John J. Detlefs

**Pull request merged**
