### PR TITLE
Use cythonize to compile cython files

### PR DESCRIPTION
**Pull request by kain88-de**
I experienced some errors in the cython compilation in other branches
when I experiment and do more advanced stuff. This helps to get clean
compilations from cython.

This is also the recommended way according to the docs.

### CODE REVIEW

**Comment by orbeckst** [comment]
Is travis really cythonizing files? We ship C files and doesn't cython check if these C files are out of date and only rebuilds them in this case?

**Comment by kain88-de** [comment]
yup but I'm currently writing a lot of new cython-code and I run into problems with the old style. Basically setuptools called the cython compiler wrong and then I had some stuff missing in the generated c-files. This is fixing it for me. To save others the pain I thought I'd just make it a small PR.

The problems started to occur when I started to use `cdef` functions from other cython-modules

**Comment by hainm** [comment]
@orbeckst from my experience with pytraj, if you did not explicitly use 'cythonize', the pre-cythonized c/cpp. I got the same (or similar) issue.

By the way, my rule of thumb for development is
- only ship cythonized files (c/cpp) when release. It's very easy to install cython (vs numpy, scipy, ...)
- solving merging conflict of cythonized files is pain in the ***.

**Comment by orbeckst** [comment]
On 3 Dec, 2015, at 17:20, kain88-de wrote:

> yup but I'm currently writing a lot of new cython-code and I run into problems with the old style. Basically setuptools called the cython compiler wrong and then I had some stuff missing in the generated c-files. This is fixing it for me. To save others the pain I thought I'd just make it a small PR.
> 
> The problems started to occur when I started to use cdef functions from other cython-modules

Makes sense. My comment was more directed at the question if this gets actually tested on Travis. If not, then this PR passing tests does not mean very much.

Perhaps we should have a build matrix with (1) shipped C files, (2) cythonize (if this is possible)?

**Comment by kain88-de** [comment]
I'm not sure about how exactly to do the build-matrix thing in travis but you can force a recompilation of the cython files with `find . -name '*.pyx' -exec touch '{}' \;`. The new timestamp will trigger the recompilation.

But I think forcing the recompilation is enough

**Comment by hainm** [comment]
You should still make the matrix. If not, the pre-cythonized files are not tested.

**Pull request merged**
