### PR TITLE
Doctest failures

### PR DESCRIPTION
**Pull request by MohitKumar020291**
Fixes #3925 

Changes made in this Pull Request:
 - fixes doctest run, Screenshot attached(failure and passed):
 

Still some changes are failing.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

----
:books: Documentation preview :books:: https://mdanalysis--4188.org.readthedocs.build/en/4188/

### CODE REVIEW

**Comment by MohitKumar020291** [comment]
Reviewers sorry for problem. I need to check what went wrong.

**Comment by MohitKumar020291** [comment]
@orbeckst I made these changes but I do not know "why those datasets get added?". Although the changes are making many doctests pass of `analysis` and `encore`. These commits are good: 
1.)[fixed extra.py](https://github.com/MDAnalysis/mdanalysis/pull/4188/commits/018e3f3a6affa2bc0c2675e7a8a7b6c3ebd30a35)
2.)[fixed pca.py](https://github.com/MDAnalysis/mdanalysis/pull/4188/commits/f856bbb62b264fc22931472291d5d9f52de48f78)
3.)[fixed psa.py](https://github.com/MDAnalysis/mdanalysis/pull/4188/commits/6148cf3c33de5d2a40345e8aac23fe38d95dbaf2)
4.)[similarity.py 2 fixed](https://github.com/MDAnalysis/mdanalysis/pull/4188/commits/7f3c32928c61ace111b4e6650ae8cb8c3f385749)
5.)[Changes needed further](https://github.com/MDAnalysis/mdanalysis/pull/4188/commits/dbfae9db65cd4115e702f46f4bc7f8637d379426)
6.)[removed double align.py](https://github.com/MDAnalysis/mdanalysis/pull/4188/commits/0d4557b9e4cd27cafca5a24b29a2c8782bb217b6)

For proof: I have attached screenshot above (in PR description).

**Comment by RMeli** [comment]
Hi @MohitKumar020291, thanks for your contribution. This PR is close, so please re-open it and fix the issues or open another one that we can review. If a PR is close, it's very unlikely someone will look at it.

Concerning the added files, probably they are temporary files that somehow you added to your commit. If you use "git add --all", it is good practice to always check with "git status" which files have been changed/added, before using "git add". In this way you can check that the changes in your repo look as you expect.

**Comment by MohitKumar020291** [comment]
@RMeli Thanks for review, I will go with opening a new PR. Thanks for other suggestions also.

**Pull request closed without merging**
