### PR TITLE
Feature distancesmove

### PR DESCRIPTION
**Pull request by richardjgowers**
Final part of #287 , mainly a travis check, can merge this once it passes

### CODE REVIEW

**Comment by orbeckst** [comment]
Looks ok, just merge once it passes.

Should I then rebuild the docs or are you going to do this?

**Comment by richardjgowers** [comment]
I know I've asked this before, but is it just running sphinx and pushing that to dev?

**Comment by orbeckst** [comment]
On 8 Jul, 2015, at 16:10, Richard Gowers wrote:

> I know I've asked this before, but is it just running sphinx and pushing that to dev?

1) pull
2) install (developer installation is fine but must be installed so that sphinx can import)
3) A totally clean rebuild (when you are not 100% sure if there are any generated files that need deleting):

	cd doc/sphinx 
	rm -r ../html        # only necessary if you removed docs
	make html

	There are still lots of reST warnings and issues and it probably takes a lifetime to fix them (and even that isn't straightforward because it's not always clear (to me, anyway)) where the problem is in the file. Check if there are some serious issues, e.g. "document referenced but no heading" � that indicates some import issues or Gremlins or Faeries or Pixies.

	If any fixes in the restructured text are needed, put them in their own commit � I frequently amend commits at this stage... 

4) check 'firefox ../html/index.html'
5) If all is good, 'git status',  then 'git add' any newly added files and properly 'git rm' any files that were not rebuilt and show up as deleted.
6) commit (just make sure that the commit only contains generated files)
7) push to develop

8) now update the developer docs at devdocs.mdanalysis,org in the gh-pages branch:

	git fetch --all   # just in case
	git checkout -b gh-pages
	git merge develop
	git push origin gh-pages

	git checkout -b develop   # just in case ;-)

DONE.

**Comment by richardjgowers** [comment]
Cool thanks.  I've nearly got the Timestep API fix done, so I'll rebuild when that is finished.

**Comment by orbeckst** [comment]
UPDATE on docs writing: Have a look at the wiki page [WritingDocumentation: Updating the docs](/MDAnalysis/mdanalysis/wiki/WritingDocumentation#generating-the-docs) where I added the information from above.

**Pull request merged**
