### PR TITLE
Remove vim fileencoding hint

### LINKED ISSUE #527: coveralls misses most of the files
@richardjgowers's [answer to my question why coverage fell to 85%](https://groups.google.com/d/msg/mdnalysis-devel/BZlpaDb6VXU/3Ke6hztgAwAJ) is that coveralls only recognizes a paltry 13 source files at the moment. But it's not clear why and how to fix it.

### PR DESCRIPTION
**Pull request by kain88-de**
This hint seems to be responsible for coveralls failing to parse the
and report and the files.

Fixes #527

### CODE REVIEW

**Comment by kain88-de** [comment]
Yeah this worked. We are back to 87% coverage.

**Comment by orbeckst** [comment]
Isn't this really a bug in `coveralls` because [PEP 0263](https://www.python.org/dev/peps/pep-0263/) says that what we have been doing is the way to add encoding information to Python source files:

"More precisely, the first or second line must match the regular     expression "coding[:=]\s*([-\w.]+)". The first group of this     expression is then interpreted as encoding name."

**Comment by orbeckst** [comment]
Is there a downside for `vi` users when we remove the vi-hint? @dotsdl might want to comment?

**Comment by kain88-de** [comment]
So this bug occurs when the fileencoding statement appears two times in the first two lines. I created an issue with coverage.py. Lets see what happens


https://bitbucket.org/ned/coveragepy/issues/453/source-code-encoding-can-only-be-specified

**Comment by orbeckst** [comment]
Thanks for filing the issue with `coverage`.

I suppose we could merge your fix and `git reverse` it if/when `coverage` gets fixed. In this way we get back to a working CI infrastructure. (Or will the `vi` users be screwed?)

**Comment by richardjgowers** [comment]
Thanks Max!

@dotsdl can we use this on the 363 branch too so we're not writing tests blind?  Or does it screw you over?  (Would you just have to avoid any files with UTF characters?)

**Comment by kain88-de** [comment]
This shouldn't screw @dotsdl or other vim users over. vim and emacs are both very good at picking up the file extension even without the hint. They actually guess the file-encoding in similar ways to `file`. It only really matters for new files and there I assume he set up vim to use UTF-8 by default.

*remark*. I used vim extensively before I switch to emacs (and even now I emulate it with evil)
@dotsdl have a look at [spacemacs](https://github.com/syl20bnr/spacemacs) and [magit](https://github.com/magit/magit), all the goodness of vim and much much more.

**Comment by dotsdl** [comment]
I think I should be good. If we see this issue crop up again on new commits, we'll know otherwise.

**Comment by orbeckst** [comment]
Ok, please someone merge.

Oliver

On 14 Dec, 2015, at 15:03, David Dotson wrote:

> I think I should be good. If we see this issue crop up again on new commits, we'll know otherwise.
> 
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by dotsdl** [comment]
@richardjgowers let's go ahead and also remove these hints from the `issue-363` branch.

**Comment by kain88-de** [comment]
BTW we are now at 90% code coverage. :+1:

**Comment by orbeckst** [comment]
On 14 Dec, 2015, at 15:49, kain88-de wrote:

> BTW we are now at 90% code coverage. 

woot!

@richardjgowers should be happy!

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment]
The issue has been fixed in coverage. With the next release we should be able to revert this PR.

https://bitbucket.org/ned/coveragepy/pull-requests/77/fix-error-with-double-occurence-of/diff

**Comment by kain88-de** [comment]
FYI there is a [new version](http://nedbatchelder.com//blog/201601/coveragepy_41b1.html) of coverage.py that is in beta right now and will likely change our results. But it includes my fix for the file-encoding. So we should be able to revert this PR soon.

**Pull request merged**
