### PR TITLE
Added function lib.mdamath.make_whole

### PR DESCRIPTION
**Pull request by richardjgowers**
So I'm not going to explain what this does, cause part of the review is to check my docs make sense!

Also, paging someone else to review stuff ( @dotsdl @mnmelo )

### CODE REVIEW

**Comment by richardjgowers** [comment]
So I might have accidentally killed everything by a forced push... 

Anyway, the function now does a walk of the molecule before changing positions, so is now safer.

**Comment by dotsdl** [comment]
Waiting for a response on adding a warning for checking that a molecule is split over the periodic boundary. Then I think we'll be good to merge.

**Comment by richardjgowers** [comment]
I'm a little stuck with how to do such a (simple) check.  I can't use bonds.mean() because if all the bonds are "high" then they look artificially high, and the box then looks "too small".  Maybe just a heuristic, if the box is under 10A then it's too small for this?

**Comment by dotsdl** [comment]
Not sure either. @orbeckst , what do you think is a reasonable test for spitting out a warning that the molecule might not be considered to be straddling a periodic boundary (line 335)? I'm inclined to say that the "box length under 10A" is more than reasonable given the size of a normal bond is 1-2A. Any weird corner cases?

**Comment by orbeckst** [comment]
Alternative idea for the check: compare bond lengths without PBC taken into account to lengths WITH PBC (which I think works for all boxes already). Assuming you initially has everything inside box, any disagreement indicates a broken molecule, doesn't it?

Otherwise I'd just flag anything that's above a "typical" bond length. One would need to define typical for atomistic and coarse grained force fields and probably make this value a kwarg. Alternatively, look at the distribution of bond lengths of the whole system and look for a gap in the histogram and flag anything above the gap.

**Comment by dotsdl** [comment]
Looks great! The box tests look a lot more robust now. Merging!

**Pull request merged**
