### PR TITLE
[resolves #3993] repurposed _conclude to perform _single_frame loop 

### LINKED ISSUE #3993: [ENH]: Change MSD code to accumulate values using `.timeseries`.
## Is your feature request related to a problem? ##

The MSD code currently uses a custom loop to collect positions  in `_run()` and then calculates the actual MSD in `_conclude`. The loop over ts.positions is the same as that handled by  `.timeseries` so we could probably streamline it. 

## Describe the solution you'd like ##

This could be made more streamlined using `.timeseries` to replace the _run() loop.

### PR DESCRIPTION
**Pull request by ooprathamm**
Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Review by hmacdope — CHANGES_REQUESTED** [review]
This is not quite right, the aim is to use `Reader.timeseries` to gather the positions in `_prepare()` and then to leave `_conclude()` the same. The _single_frame method can become blank.

**Comment by hmacdope** [comment]
I would recommend trying to understand the purpose of the code and the operations conducted therein. Also make sure you run the test suit yourself to verify correctness.

**Comment by ooprathamm** [comment]
implemented the same using .timeseries , works on the test case in the docs but test suite is failing.

**Comment by hmacdope** [comment]
@ooprathamm have a look at the failures and try and fix the issue. :)

**Comment by IAlibay** [comment]
@ooprathamm you have three simultaneous PRs opened on `gsoc-starter` labelled issues.

1. The MDAnalysis team asks that folks aiming to participate in GSoC only attempt to complete one such labelled issue: https://github.com/MDAnalysis/mdanalysis/wiki/Google-Summer-Of-Code#close-an-issue-of-mdanalysis
2. We also would heavily encourage new starters not attempting to do multiple PRs at the same time. Merging a PR can be a long process and having multiple issues only serves to distract attention from completing the PR. There's also lots of important information (style, which files need updating, etc...) you pick up on completing your PR which can then be applied to any future PR.

Given that the three PRs are currently in progress, I'll let @MDAnalysis/gsoc-mentors work out what the best course of action is here.

**Comment by orbeckst** [comment]
@ooprathamm given our “only one GSoC PR” rule we will only review one of your PRs. See https://github.com/MDAnalysis/mdanalysis/wiki/GSoC-FAQ#can-i-work-on-multiple-gsoc-starter-issues  . By default we will choose your first one #4010 and *close the other ones*. 

If you prefer that we look at another one of your PRs instead please let us know here; you can also close all but one of your PRs by yourself. 

I hope you understand that we will enforce our rules in order to maintain a fair playing field for all applicants.

**Comment by ooprathamm** [comment]
@IAlibay @orbeckst I was unaware of “only one GSoC PR” rule . please do as you find appropriate.

please consider the first one ( #4010 )

**Comment by orbeckst** [comment]
Hello @ooprathamm , no problem, I understand it's a bit difficult because we're not officially in GSoC yet so you only find out when we tell you. 

I'm going to close your PRs *except PR #4010* .

**Pull request closed without merging**
