### PR TITLE
Feature blankuniverse

### PR DESCRIPTION
**Pull request by richardjgowers**
Currently it's a pain to create a blank Universe to fill up with data then save.  This adds the classmethod `Universe.create_dummy` which lets you create a Universe of arbitrary size:

``` python
new_u = mda.Universe.create_dummy(20)

for i, atom in enumerate(new_u.atoms):
    atom.name = 'Congaman{}'.format(i+1)
new_u.atoms.resnames = 'Congaline'

new_coords = np.stack([np.zeros(20), np.zeros(20), np.arange(20)]).T
new_u.trajectory.ts.positions = new_coords
```
It's different from Merge because that merges existing populated structures, this just creates them from nothing.

Also allows reading a trajectory without having any topology information except the number of atoms:

``` python
u = mda.Universe(1000, 'mytraj.trr', topology_format='dummy')
```

And then obviously your atoms names etc are all defaults.

### CODE REVIEW

**Comment by orbeckst** [comment]
Good idea, but I don't like the `create_dummy()` method, or more specifically, the name. How about making it `create()` and let it work like `__init__()` *except* that everything is optional? You then have a clean way to create either a "normal" universe or a dummy one, but we don't have to call it dummy. Similarly, make a dummy if `__init__()` gets `None` for the *topology*.

**Comment by orbeckst** [comment]
@tylerjereddy has been looking into topology building recently so he might also have some insights.

**Comment by kain88-de** [comment]
I also don't like `create_dummy`.  It would be nicer if the init method can just figure out what we want. like just giving a number of atoms.

```python
u = mda.Universe(natoms=20)
```

Similar things go for the topology. If I don't want to give a special topology my first try would be.

```python
u = mda.Universe('some.trr', topology=None)
```

**Comment by richardjgowers** [comment]
I did think of just `mda.Universe(20)` to create a blank Universe, but the `__init__` is already a bit long and complicated, so maybe a class method would make it clear that "normal" Universes need filenames.  Using a `n_atoms` keyword might make this all nicer, so options would be..

``` python
mda.Universe(top, traj)  # normal usage?
mda.Universe(top)  # single file traj or no traj
mda.Universe(traj, n_atoms=20)  # traj without topology
mda.Universe(n_atoms=20)  # blank Universe
```

Can TRRs be loaded without knowing `n_atoms` beforehand?  If so, could write a quick parser so that they work standalone (for whatever reasons).

**Comment by hainm** [comment]
In mdtraj and pytraj, just

Trajectory(xyz=xyz, top=top)

**Comment by kain88-de** [comment]
> Can TRRs be loaded without knowing n_atoms beforehand? If so, could write a quick parser so that they work standalone (for whatever reasons).

Yes, that information is in the header file. My new implementation is checking that. i'm not sure about the current reader though.

> so maybe a class method would make it clear that "normal" Universes need filenames. 

Hm not really. Plus it will/might be harder to find this functionality for the user.  kwargs and a good docstring should be fine. I also like the options you've written to create universes.

**Comment by richardjgowers** [comment]
So this will end up looking very different soon, so I'm closing this, but I'll revive the idea soon!

**Pull request closed without merging**
