### PR TITLE
selection string can be unicode

### PR DESCRIPTION
**Pull request by kain88-de**
Changes made in this Pull Request:
 - check if select is a generic string type in RMSD calculation

PR Checklist
------------
 - [x] Tests?
 - ~[ ] Docs?~
 - [x] CHANGELOG updated?
 - ~[ ] Issue raised/referenced?~

### CODE REVIEW

**Comment by orbeckst** [comment]
Thanks!

Do we have similar defective string tests elsewhere, too?

**Comment by kain88-de** [comment]
likely. Not sure how to test for them.

**Comment by orbeckst** [comment]
At least two more:
```
> git grep 'is str'

package/MDAnalysis/analysis/density.py:        if (len(args) > 0 and type(args[0]) is str) or (type(kwargs.get('grid', None) is str)):
package/MDAnalysis/analysis/psa.py:        if type(metric) is str:
package/MDAnalysis/analysis/rms.py:    if type(select) is str:
```
(and manually filtered)

**Comment by kain88-de** [comment]
I’m still missing one case the Oliver found in the code.

**Comment by kain88-de** [comment]
I'm not going to test the other corner cases we found because no basic test to bunnyhop onto exists.

**Comment by orbeckst** [comment]
The OSX py 3.6 test failed in test_get_Writer – totally unrelated to this PR, I restarted https://travis-ci.org/MDAnalysis/mdanalysis/jobs/306825357

**Comment by kain88-de** [comment]
Don’t brother restarting. That will fail again. Richard merged the recent selection string PR with the failure and wants to find out what a correct solution is.

**Comment by orbeckst** [comment]
Do you or @richardjgowers want to hold of on merging then?

**Comment by kain88-de** [comment]
I’m ok merging

**Comment by orbeckst** [comment]
@kain88-de could you please resolve the conflicts and rebase (and squash everything?). Thanks.

**Comment by orbeckst** [comment]
It needs to be revised, I didn't have the time to do it. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Pull request merged**
