### PR TITLE
Using Capped distance in distance selections

### LINKED ISSUE #974: "around" selection is slow and memory-intensive
As of `0.15` performing an `around` search can be quite expensive, both compute-wise as memory-wise. This crops up more obviously for systems with many atoms, and where the reference for `around` is itself also large.

This was tested in a system with ~640k atoms, where the reference has 1130 atoms (`select_atoms around 15 name ATNAME`). It took at least 15 seconds. Doubling the system size (and reference too) busts my 16Gb of memory.

From the discussion in #383, and later the addition of OpenMP (#529), I was under the impression our implementation was quite fast. But for comparison, for the same system and machine VMD does the same selection operation with little memory usage spike, and virtually instantaneously. Granted, VMD doesn't do PBC but is it enough to account for this?

I took a look at their code and from what I could understand they implement several optimizations some of which I thought we were already doing since #529:
- gridded search;
- parallelization (threading);
- pre-filtering of the search space (for compact references it's easy to define a parallelepiped that contains it with a padding equal to the cutoff, and you're sure your contacts will all be inside that volume);
- shortcutting (when an atom being searched is found to be in contact, no need to calculate further distances from it to the other reference atoms).

I admit I'm not familiar with the internals of `distance_array` and `contact_matrix`, but my question is: is there room for optimization or am I hitting MDAnalysis' limits here?

### PR DESCRIPTION
**Pull request by ayushsuhane**
Fixes #974 , part of #782

Increases the performance of 'around' selection using NSgrid.

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [X ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by ayushsuhane** [comment]
As benchmark for 'around' selection is already present, I compared the three methods (exactly same functions) for that specific case. It seems that the timings have improved by an order of magnitude.
(https://github.com/ayushsuhane/Benchmarks_Distance/blob/master/Notebooks/AroundBenchmark.ipynb)[https://github.com/ayushsuhane/Benchmarks_Distance/blob/master/Notebooks/AroundBenchmark.ipynb]
However, bear in mind, the improvement is for this case and not for every case. 

@orbeckst mentioned adding benchmarks. While this will be reflected if we run the benchmarks, should I add more cases? Maybe PBC/nonPBC as in here (Issue #1721 ). But due to lack of time, I guess I will pick it up after GSOC period is over.

**Comment by ayushsuhane** [comment]
I am not sure how to add another method here mostly because of flags. Any suggestions to get around the problem without breaking the tests (and more specifically code). I thought its better to discuss here, how do we want to proceed. Do we want to keep earlier code and optimize the methods or do we want to replace with one or two using flags/keywords. As we are on the topic, I don't think using capped function for optimization (in its current form)  is suitable here, because it does extra computations of pairs/distances which we don't need in this case.

**Comment by orbeckst** [comment]
This is looking promising already. 

We want to get rid of the flags #782 so there might not remain a way for the user to choose a method. Bearing this in mind, would you recommend to switch over to NSGrid (and take the performance hit in some cases)?

**Comment by orbeckst** [comment]
> benchmarks: While this will be reflected if we run the benchmarks, should I add more cases? Maybe PBC/nonPBC as in here (Issue #1721 ). 

PBC/non-PBC would be excellent.

**Comment by richardjgowers** [comment]
@ayushsuhane I think ideally we'd reuse `capped_distance_array`, then we could simplify this greatly.  The only reason I can think not to is that it calculates indices **and** distances, so maybe could be faster.  Is this why you didn't use that?

**Comment by richardjgowers** [comment]
Ah just reread, you could add a `return_distances` kwargs (default True) to `capped_distance` and then it should be identical to this right?  It doesn't make sense to have so much duplicated code.

**Comment by ayushsuhane** [comment]
@richardjgowers Yes. While this is the case with Periodic KDTree and distance array, it would not be a problem if we are using only capped_distance(.., .., method='nsgrid') as it returns all the distances and pairs, which serves the purpose here. 

However, yes, adding return distance to kwargs is a good idea. I will look into it

**Comment by ayushsuhane** [comment]
@orbeckst  For this special case of around selections, it wouldn't hurt to take a hit and replacing with nsgrid. But I think a better approach would be to use capped_distance and optimize there. So that if anyone plan to change/modify the method later, one has to change only the capped_function, and not worry about its dependencies.

That being said, there are certain drawbacks in the capped_distance, which I wrote with different assumptions and needs to be changed. For instance, ``_bruteforce_capped`` checks distance with every atoms individually in a loop, which is a bad idea for a numpy array but it can handle arbitrary size of atoms. Now that we wouldn't want to use brute  force for arbitrary size and limit it only till its the fastest, it would be better to change it. Similarly for ``_pkdtree_capped`` where we have used for loops to get individual distances and pairs, which can/should be avoided.

**Comment by ayushsuhane** [comment]
@richardjgowers One more thing. It seems importing any library inside the function, for instance ``from . import PeriodicKDTree`` inside ``_pkdtree_capped`` takes a large amount of time  which is reflected baldly in benchmarks. Any suggestions how can we avoid it. Also, I guess its a bad practice to use local imports, isn't it? I thought we just did it for the time being, but if we are looking for optimizations, it shouldn't really be there

**Comment by ayushsuhane** [comment]
It seems importing doesn't take any significant time. My bad.

**Comment by ayushsuhane** [comment]
I think after #2041, we can move to ``capped_distance`` directly. Here is an example of choosing the best method for  around selection based on the rules specified in capped_distance.

image

However, I have one concern in changing the codebase of around. It seems tests are written for different flags and methods for every class i.e. `` apply_kdtree``, ``apply_distmat``. So there are essentially two things, one is removal of flags, and another is using a single method instead of multiple ``_apply`` methods. What do you think should be done first. Any suggestions how should I go about it?

**Comment by richardjgowers** [comment]
@ayushsuhane I think you can just rip the flags (& associated tests) out.  If someone chose `kdtree` in the flags and we don't respect that, they'll still get the same distances out, so it's not going to hurt anyone.

**Comment by richardjgowers** [comment]
@ayushsuhane this needs a quick rebase right?

**Comment by richardjgowers** [comment]
Looks solid, iirc the coverage for selections was complete, so if tests pass this is good to go

**Comment by ayushsuhane** [comment]
@richardjgowers Not sure what is happening here. Can you take a look? I tried restarting the build but the appveyor still fails due to encore.

**Comment by zemanj** [comment]
@ayushsuhane This looks like yet another random number issue to me... I just had the same test failing on my linux box, but it passed in a subsequent run. The failing test uses ``analysis.encore.bootstrap.get_ensemble_bootstrap_samples()`` with only 10 samples, so probably that's the culprit. Maybe just give it another try?

**Comment by zemanj** [comment]
@orbeckst Ok I restarted the Travis build for this PR, but now my noob question: In how far is that related to AppVeyor?

**Comment by zemanj** [comment]
@richardjgowers Ok I gotta remember that shortcut :wink:

**Comment by richardjgowers** [comment]
@zemanj it’s unrelated :) I didn’t immediately see the rerun appveyor button on mobile so I turned the PR off then on again....

**Comment by zemanj** [comment]
That's what i thought... I don't see any option to rerun a build on AppVeyor either. Not on mobile, though.

**Pull request merged**
