### PR TITLE
added GitHub citations for main library

### LINKED ISSUE #3402: DOC: add citation file
Seems like a nice thing to do so we can get a link like below on our main GitHub page. Probably just needs a PR similar to https://github.com/scipy/scipy/pull/14630 with a `CITATION.bib` in repo root with the two main papers I suppose.

image

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #3402 

Changes made in this Pull Request:
 - add GitHub CITATION.bib file
 - currently cite 2011 and 2016 papers

PR Checklist
------------
 - n/a Tests?
 - n/a Docs?
 - n/a CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
The MDAnalysisTests.coordinates.test_h5md.TestH5MDWriterWithRealTrajectory PermissionError on Windows is starting to happen a lot. Should we put an xfail on it?

(I've restarted CI to see if it's more of a transient error)

**Review by IAlibay — APPROVED** [review]
I can't check if github will like it (looking at your fork it seems to pick it up but won't let me see the file - I suspect it needs to be in the main branch?) - but lgtm

(if we can get CI to work - let's merge and see what happens)

**Comment by orbeckst** [comment]
I don't know if we want to do cff files https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files .

**Comment by IAlibay** [comment]
It's not immediately clear to me that we can add two preferred citations, Github might not parse the bib file, but it will still link to it, so I _think_ that's probably best (so we know we're linking folks to both the citations?).

**Comment by orbeckst** [comment]
Works for me!

**Comment by tylerjereddy** [comment]
yeah, probably `.bib` file is safest for now--just a convenient/high exposure link to the raw bib file basically

**Pull request merged**
