### PR TITLE
Remove start/stop/step from AnalysisBase kwargs

### PR DESCRIPTION
**Pull request by IAlibay**
Addresses #1463

Changes made in this Pull Request:
 - Removed support for `start`, `stop`, and `step` keywords on object creation for :class:`AnalysisBase` and :class:`AnalysisFromFunction` 
 - Where appropriate docstring was changed. If the docstring indicated that `start`, `stop`, and `step` keywords could be passed to `__init__` a `versionchanged` tag was added.

To do:
 - [x] Currently the tests for `AnalysisFromFunction` don't seem to test out the `start`/`stop` arguments very well, it's probably worth adding an extra test there.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
I *think* that should be everything for AnalysisBase, pinging @orbeckst here as the author of #1463

**Comment by orbeckst** [comment]
@IAlibay only contacts.q1q2 is strictly part of this PR re: AnalysisBase. I would also be ok with only fixing q1q2 and then opening another issue/PR for harmonizing start/stop/step in non-standard methods with the AnalysisBase model. I leave it up to you and how much time you can spare. Thank you so much for moving the code towards 1.0 — really much appreciated!!

**Comment by IAlibay** [comment]
@orbeckst thanks for the review 😄 

So going by https://github.com/MDAnalysis/mdanalysis/issues/1463#issuecomment-582019826 my plan was to do all the :class:`AnalysisBase` changes in this PR and then raise a separate PR for the non-AnalysisBase stuff (I have already started working on the waterdynamics stuff on a separate branch).

Going by https://github.com/MDAnalysis/mdanalysis/issues/1463#issuecomment-582019826 would you prefer it if I raised the non-AnalysisBase required changes as separate issues or is the dicussion here sufficient?

**Comment by IAlibay** [comment]
Aside from `q1q2`, I'll also add the waterdynamics hbonds call to this PR since this directly involves a :class:`AnalysisBase` method.

A note (to self) here: `pytest` didn't complain when running `test_waterdynamics`, and it should have. Extra tests will be needed here.

**Comment by IAlibay** [comment]
Unfortunately encountered #2511 whilst fixing this, it'll need to be fixed before this PR can be tied off.

**Comment by IAlibay** [comment]
With #2520 completed, this should be complete of :class:`AnalysisBase`

**Comment by orbeckst** [comment]
Many thanks @IAlibay !

This should be *merged* once CI is good.

**Pull request merged**
