### PR TITLE
DOC: Wrapping up updates to MDA citation requirements

### LINKED ISSUE #993: update citation in docs
Discussion MDAnalysis/MDAnalysis.github.io#27 lead to the new citation blurb: ask for both papers to be cited in academic work: http://www.mdanalysis.org/pages/citations/

We need to update the MDAnalysis docs in a similar way:
- [x] sphinx docs
- [x] README, meta data, etc

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #993 

Wrapping up the updates to MDA citations in docs. I've drafted the changes for `SUMMARY` and `README`, so far.

### CODE REVIEW

**Comment by orbeckst** [comment]
@kain88-de and @richardjgowers – would you mind having a quick look over our changes?

**Comment by kain88-de** [comment]
Can you please also update the README in the testsuite.

**Comment by kain88-de** [comment]
and calc_distances.h

**Comment by kain88-de** [comment]
xtc_seek.c/h, trr_seek.c/h (On those please also update the mode to C my emacs doesn't like that it pretends to be python)


I think that are all the leftovers besides the encore code that I found

**Comment by orbeckst** [comment]
I think I addressed all of your comments (and also correl.h and removed crud from the testsuite/INSTALL).

**Comment by orbeckst** [comment]
P.S.: Whoever merges, just squash my additions into @tylerjereddy 's commit.

**Comment by orbeckst** [comment]
Oops... Needs to be fixed. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Pull request merged**
