### PR TITLE
Cimport consistency

### LINKED ISSUE #3908: change `cimport numpy as np` to `cimport numpy as cnp` for consistency
## Is your feature request related to a problem? ##

We should be consistent with the way we cimport numpy in the codebase. 

Lots of places currently use
```cython
 cimport numpy as np
```

While the more modern approach and the one taken in some PRs #3777 , `timestep.pyx` and a few random other existing places is to

```cython 
 cimport numpy as cnp
```

Personally I prefer the second one (and its the one used by pandas) as it is much clearer when the C API is being used vs python API. 
@tylerjereddy  do you know if there is a standard for scipy?

Regardless of which way we go we should be consistent if possible.

Let me know what you think on this issue and if we come to a conclusion I can raise a seperate issue for taking some action. 
Might be a nice easy `good-first-issue` etc.

### PR DESCRIPTION
**Pull request by Hakarishirenai**
Fixes #3908

Changes made in this Pull Request:
 - Have updated all `cimport numpy` from `np` to  `cnp`
 
PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by Hakarishirenai** [comment]
@hmacdope can you give it a look ?

**Comment by hmacdope** [comment]
Seem to be a large number of test failures @Hakarishirenai? You will have to go through and have a look at each one and fix it. Do you know how to run the tests locally? Have a look on the [contributing page](https://userguide.mdanalysis.org/stable/contributing.html) and [tests guide](https://userguide.mdanalysis.org/stable/testing.html) for some tips if not.

**Comment by Hakarishirenai** [comment]
Sure, will give it a look and try fixing them!

**Comment by Hakarishirenai** [comment]
@hmacdope does this looks good ?

**Comment by Hakarishirenai** [comment]
@hmacdope does this look good ?

**Comment by hmacdope** [comment]
Thanks for fixing the tests! Great job.  Would you mind running the benchmarks to see if we have any regressions?

I only ask because it is possible to select different versions of a function or datatype silently when using `import numpy as np` AND `cimport numpy as np`, which is no longer the case with your changes.

The command you want is probably something like  
```bash
asv continuous  [commit from develop] [commit from your branch]
```
The readme on running the benchmarks is at https://github.com/MDAnalysis/mdanalysis/tree/develop/benchmarks

**Review by hmacdope — CHANGES_REQUESTED** [review]
Benchmark block

**Comment by Hakarishirenai** [comment]
Sure, will give it a try

**Comment by orbeckst** [comment]
@hmacdope you blocked the PR. Did anything change that would allow us to move forward? Or should we close the PR??

**Comment by hmacdope** [comment]
@orbeckst  Waiting for a benchmark run by @Hakarishirenai  to certify no cython Numpy functions are being alaiesed back to Python level. I suppose I should probably just run them myself off this branch.

**Comment by hmacdope** [comment]
@Hakarishirenai are you able to run the benchmarks? I havn't had a chance Otherwise I will mark this PR as stale in a few days.

**Comment by IAlibay** [comment]
I'm closing this PR as stale (due to lack of activity), please reopen if necessary.

**Pull request closed without merging**
