### PR TITLE
Adding elements attribute to PDB parser and unit tests

### LINKED ISSUE #2647: PDB Parsers should provide an elements attribute
## Elements attribute in PDBParser ##

Related to #2423, #2553 and #2630, the PDBParser does not provide an elements attribute. Primarily have an attribute to define the element of an atom as per the periodic table.

```
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import *
>>> u = mda.Universe(PDB)
>>> u.atoms.elements
array(['N', 'C', 'C', 'O', 'C', 'Cu', 'Fe', 'Ca'], dtype=object)
```

Elements class exists and enforcing elements would be needed.

### PR DESCRIPTION
**Pull request by AmeyaHarmalkar**
Fixes #2647

Changes made in this Pull Request:
 -  Adds elements attribute to check for valid elements and adds them to the Elements class
 -  Adds suitable unit tests to check for missing, non-valid and valid elements.
 -  Solves a part of the problem that #2553 raises.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by AmeyaHarmalkar** [comment]
@IAlibay the new PR for the issue like you suggested.
Let me know if I need to do any further changes.

**Comment by IAlibay** [comment]
@AmeyaHarmalkar I think there has been some misunderstanding, I meant that you should finish PR #2627 solely allowing for elements to be parsed if they are all present & normal (as you are doing here). Then open up a new PR/issue set for dealing with alternative cases where elements are non-normal, including any appropriate changes to `guessers.py`.

**Comment by AmeyaHarmalkar** [comment]
Oh, I completely misunderstood you then. Should I do a hard reset on the other branch then do the changes? I will close this PR and delete the issue.

**Comment by IAlibay** [comment]
> Oh, I completely misunderstood you then. Should I do a hard reset on the other branch then do the changes? I will close this PR and delete the issue.

Sorry about that, this is definitely on me for bad communications. Probably closing this PR would be a good idea, however you can keep the issue open, just add it to the header of #2627 and we can close it when we merge the PR.

Re: hard reset -> just revert the one file, you can do that using git checkout: https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision

**Pull request closed without merging**
