### PR TITLE
Generate doc tables for transplanted methods, continued

### LINKED ISSUE #1845: docs for many AtomGroup methods missing
### Expected behaviour
radius_of_gyration(), principal_axes() (see #1828 ), center_of_mass() and most other "compute something on an AtomGroup" (that require e.g., mass) should be in the docs for AtomGroup.

### Actual behaviour
They are not in the docs anymore (at least since 0.17.0 but probably since #363 / 0.16.0)

### Code to reproduce the behaviour
Look at https://www.mdanalysis.org/mdanalysis/documentation_pages/core/groups.html#MDAnalysis.core.groups.AtomGroup

I think the problem is that we only attached certain methods to AtomGroup when specific TopologyAttrs are present. The bare AtomGroup does not contain masses so many of the most used methods are invisible to the user (and a lot of our docs is broken, e.g., in the tutorial).

### Currently version of MDAnalysis:
develop, but also published 0.17.0

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #1845

Continues #2176 
Changes made in this Pull Request:
 - Writes a sorted list of methods and properties without arguments like ``group`` or ``self``. 

I haven't addressed the duplicate citation issue. Links just go to the original `MDAnalysis.core.topologyattrs.Attrname.Method` docstring citation.

To be honest, IMO the best solution would be to just move the methods to the core classes and fail gracefully when the required topology attribute isn't there. This approach has many downsides, including:

- I sorted the properties/methods alphabetically, but all of them nevertheless appear before the *Group's *actual* properties/methods
- You must manually add `.. include:: XXX_methods_table.txt` and `.. include:: XXX_methods_docs.txt` to each docstring every time you add a new transplant target
- The Universe transplanted methods are now in a docstring that's largely about its `__init__` method and will show up in `help(Universe)`
- citations confusingly link to an identical entry on a different page
- People looking at the code now have a mismatch between code and documentation
- what happens when you have a method that requires >1 topology attribute?

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by lilyminium** [comment]
Looks like the screenshot below or have a look at these [built docs](https://lilyminium.github.io/mdanalysis/documentation_pages/core/groups.html#MDAnalysis.core.groups.Atom). I felt a little blurb was needed to explain the sudden table.

Screenshot 2019-12-20 at 5 14 55 PM

**Comment by richardjgowers** [comment]
I’m ok with moving methods into the base class. I think the whole transplanted methods thing went a little too far.

**Comment by jbarnoud** [comment]
To add to @lilyminium argument, having the transplanted method also means that the methods are less discoverable, that they are clearly not IDE friendly, and that error messages are unhelpful when switching topology format.

**Comment by jbarnoud** [comment]
> I’m ok with moving methods into the base class. I think the whole transplanted methods thing went a little too far.

I gave a go at the move in #2425. I am not done with it, but it feels already like a massive regression. The reasons @richardjgowers gave to justify the transplanted methods stand and become more obvious when undoing the change.

From #601:

> Reasons for this approach
> - Prevents the base AtomGroup class from becoming bloated with every imaginable method
> - All code related to a given Attribute lives in the same module
> - Can include extra Attributes & methods without installing MDA from source

**Comment by orbeckst** [comment]
This PR has been superseded by PR #2427 and #3007 so I am closing it.

**Pull request closed without merging**
