### PR TITLE
Fix doctest for MDAnalysis.analysis.psa

### PR DESCRIPTION
**Pull request by ooprathamm**
Part of #3925 for MDAnalysis.analysis.psa

Changes made in this Pull Request:
 - Adds missing imports in docstrings in MDAnalysis.analysis.psa and corrects outputs, so that the doctests pass for this particular file

- Solves ~19 failing tests

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by ianmkenney** [comment]
@ooprathamm Thanks for taking this on! These changes seem to resolve the doctests errors for `psa`. Could you update the CHANGELOG?

**Comment by ooprathamm** [comment]
@ianmkenney my username is already listed in the changelog :)

**Comment by ianmkenney** [comment]
@ooprathamm I tried out your fixes locally, which did remove the errors. Unfortunately the [CI tests](https://github.com/MDAnalysis/mdanalysis/actions/runs/4235440053/jobs/7359058958#step:6:3855) still show the errors due to the missing MDAnalysisTests package.

**Comment by ooprathamm** [comment]
@ianmkenney is this a issue with the MDAnalysisTests package still not installed properly in the CI environment?

**Review by hmacdope — APPROVED** [review]
LGTM!

**Comment by hmacdope** [comment]
@ianmkenney the CI seems to have sorted itself out.

**Review by ianmkenney — CHANGES_REQUESTED** [review]
This looks good, but there is an error in our CI workflow. Holding this until #4044 is resolved, at which point you will have to merge `develop` into this PR.

**Comment by orbeckst** [comment]
@ianmkenney , #4044 was merged

**Comment by ianmkenney** [comment]
@ooprathamm can you merge develop back into this PR?

**Review by ianmkenney — APPROVED** [review]
LGTM

**Comment by Syedmahmood777** [comment]
Hey, I have run the above commands to check docstring and found this:

`ModuleNotFoundError: No module named 'pybtex`

There is no pybtex in the requirements on installing MD-Analysis on the official website, so can anyone advise how should I go about solving this and contribute?

**Comment by orbeckst** [comment]
@Syedmahmood777 we typically do not continue conversations on merged PRs. Start a discussion in https://github.com/MDAnalysis/mdanalysis/discussions or ask in our Discord https://www.mdanalysis.org/#participating

**Pull request merged**
