### PR TITLE
Add Darken action to check for pep8 violations in diffs

### LINKED ISSUE #3854: pep8speaks not active?
Just from a very cursory look, I can't seem to see pep8speaks entries in most of the latest PRs here. Is it somehow deactivated?

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #3854 

I'm trying to like Black @RMeli 🙃 

Changes made in this Pull Request:
 - Darken action
 - Some action cleanup (might split stuff up in a future PR so we can have a bit more coherence)

PR Checklist
------------
 - Tests?
 - Docs?
 - CHANGELOG updated?
 - Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
There we go, so it ignores blank lines, but not 79 char issues... it's a start.

**Comment by IAlibay** [comment]
Ok looks like it's keeping track of the head branch properly, now to see if we can get it to complain on incorrect number of lines between class definitions.

**Comment by IAlibay** [comment]
Ok this one is going to be contentious @MDAnalysis/coredevs so please take the time to review this before we have complaints further down the line.

## What does this do?

* This action essentially applies `Black` and `flake8` on the diff of a PR's commit. This means it'll tell you if it thinks you're doing shady PEP8 things

## Why might it be annoying?

* Because it uses `Black`, it will have opinions on how things should be, particularly when it comes to visual indent for lists / dictionaries. Whilst generally useful, those suggestions _might not_ agree with what you think is reasonable.
* Both `black` and `flake8` actually go beyond PEP8, you might not agree with certain things...

## Do we have to listen to it?

* Because I can't just get it to just always go green and just write out a comment (there's some security issues and I couldn't circumvent them), it'll just claim to be a failed runner.
* My proposal is that we **don't treat it as the only truth**. Read the failure, see if you agree, tell contributors to fix them, or don't, as long we pass your interpretation of PEP8 it's up to you!

## What can't it do?

Currently my only observations are:
* The action won't be able to tell you off if you just spuriously add blank lines in certain places. Because it acts on the diff, it can't tell if you're adding more / less blank lines in places you shouldn't.
* Sometimes `black` will fail to identify lines going wrong, but `flake8` picks up the slack.

**Comment by IAlibay** [comment]
P.S. This replaces our reliance on the unfortunately broken but amazing pep8speaks bot :(

**Comment by jbarnoud** [comment]
Could you make some changes that would not follow pep8 so we get to see what darken looks like?

I liked pep8speak, too bad it is broken :cry:

**Comment by IAlibay** [comment]
> Could you make some changes that would not follow pep8 so we get to see what darken looks like?
> 
> I liked pep8speak, too bad it is broken 😢

:D forgive me for my sins o Python gods (sure)

**Comment by jbarnoud** [comment]
The report is a bit dry, but I can do with it. What is the line length policy?

**Comment by orbeckst** [comment]
I can live with it.

**Comment by orbeckst** [comment]
For posterity: this is what output looks like for well/badly formatted code: https://github.com/MDAnalysis/mdanalysis/actions/runs/3651330936/jobs/6168426745

**Comment by orbeckst** [comment]
@IAlibay if you need a LGTM from me, remove the demonstration code and let me know.

**Comment by IAlibay** [comment]
> @IAlibay if you need a LGTM from me, remove the demonstration code and let me know.

Should be good to go now @orbeckst

**Review by orbeckst — APPROVED** [review]
lgtm

**Comment by IAlibay** [comment]
> The report is a bit dry, but I can do with it. What is the line length policy?

88 with darken, 79 with flake8, I'll see if there's a way to make them match

**Comment by IAlibay** [comment]
blergh the `Black` release that just came out earlier today is causing trouble

**Comment by IAlibay** [comment]
> > The report is a bit dry, but I can do with it. What is the line length policy?
> 
> 88 with darken, 79 with flake8, I'll see if there's a way to make them match

@jbarnoud I've set them both to be 88 characters now.

**Review by jbarnoud — APPROVED** [review]
Lgtm

**Pull request merged**
