### PR TITLE
fixed "division by zero" bug in analysis.waterdynamics

### PR DESCRIPTION
**Pull request by cyanezstange**
Hi, I'm working with the analysis/waterdinamics.py module and I fixed a bug and added DivisionByZero exception  in SurvivalProbability class.
I also changed the CHANGELOG and AUTHORS files.

### CODE REVIEW

**Comment by richardjgowers** [comment]
Hi Carlos

Thanks for the report and thanks even more for the fix!

Would it be possible to get a bit more detail about when this bug could occur?  It looks like it happens when there are no particles in the selection zone at t=0.  Is this correct?

Thanks
Richard

**Comment by cyanezstange** [comment]
Hi Richard, thanks for the response.
Yes, this bug happens when there are no particles in the selection zone but not  specifically at t=0, 't0' is the name of the variable and it refer to a initial time on a specific selection of frames, but it can take a wide range of values.
In the calculation, the variables 'Ntau' and 'Nt' inside _getOneDeltaPoint(...) are under the condition Ntau<=Nt (Ntau >= 0, Nt >= 0), then the ratio Ntau/Nt is an indeterminate form 0/0 and is impossible to know. This value is discarded in the average performed in _getMeanOnePoint(...).

Carlos

**Comment by orbeckst** [comment]
@alejob can you please also have a look at this issue report and proposed fix, given that you're the original author of the code?

Add your comments in the source and in this PR. Assuming that everything looks good, either @richardjgowers or I can merge.

**Comment by alejob** [comment]
Hello everybody, the bug is true, and It happen for the reasons that @richardjgowers and @cyanezstange exposed (no particles in time t0, this happens in very small selection regions). The bug solution is good, because it excludes from the average the NAN value.

cc: @orbeckst

**Comment by alejob** [comment]
I add my comments in @cyanezstange's fork.

**Comment by orbeckst** [comment]
@cyanezstange also add your name to the `authors` in [package/doc/sphinx/source/conf.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/conf.py#L88) and then squash the change into this commit (so that there's a single commit with all changes).

Thank you for the contribution!

**Comment by cyanezstange** [comment]
@orbeckst All the changes you proposed were made. Thanks for all.

**Pull request merged**
