### PR TITLE
check if docs are present

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
The doc build fails. This is testing out the doc build. I want to check a little bit how exactly I broke the docs. Keeping it like that would be great since then we can actually CI test the docs.

**Comment by kain88-de** [comment]
@MDAnalysis/coredevs anyone experienced with sphinx?

Why do we get two folders on travis? See: https://travis-ci.org/MDAnalysis/mdanalysis/jobs/215688068#L1101

But on my own development machine it is only one folder.

**Comment by kain88-de** [comment]
@orbeckst To be precise. Publishing the docs on the development branch is currently broken. This is due to my recent refactoring of the travis jobs. I would like to keep building the docs with `setup.py sphinx_build` because it allows us to turn sphinx warnings into errors and have consistent docs. This PR is for trying to figure out how that can be done.

**Comment by kain88-de** [comment]
Ok this should work again. The whole debugging ls and tests commands should still be removed though. 

With work I mean I guess the deploy script works again. Not sure if using the setup command broke the docs in some other way.

**Comment by orbeckst** [comment]
I think you still need a way to only tests for docs when the docs are actually being built. For instance, the linting task [Job #3186.4](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/215697696) is also failing.

**Comment by kain88-de** [comment]
> I think you still need a way to only tests for docs when the docs are actually being built. For instance, the linting task Job #3186.4 is also failing.

That was on purpose here. I wanted to find out in which folder the docs are being build on travis. 

What I'm wondering though is why the folder has changed on  travis and not my local development machine.

**Comment by kain88-de** [comment]
Also I think this fixes the deploy script.

**Comment by kain88-de** [comment]
When I test the doc build on my laptop everything looks fine.

**Comment by kain88-de** [comment]
Looks like this change fixed the doc build. The docs on the website also look fine.

**Pull request merged**
