### PR TITLE
Fix: Pca.py doctest error

### PR DESCRIPTION
**Pull request by HeetVekariya**
Partially address #3925 

Changes made in this Pull Request:
  - Doctest for **pca.py** (package/MDAnalysis/analysis/pca.py) file contains two error (at two places: [1](https://github.com/MDAnalysis/mdanalysis/blob/2d1d6845134ec24279af6f35b1f5ddd1d77edd11/package/MDAnalysis/analysis/pca.py#L635) and [2](https://github.com/MDAnalysis/mdanalysis/blob/2d1d6845134ec24279af6f35b1f5ddd1d77edd11/package/MDAnalysis/analysis/pca.py#L813) ) due to wrong output in Expected:
    - ```0.38147609331128324``` 
    - ```0.17478244043688052``` 
 - Corrected expected output according to the generated output as below:
   - ```0.3814760933112831```
   - ```0.17478244043688054```

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4377.org.readthedocs.build/en/4377/

### CODE REVIEW

**Comment by HeetVekariya** [comment]
I will update the change log when reviewed by maintainers.

**Comment by orbeckst** [comment]
@lilyminium could please handle this PR? I think rmsip was your code, wasn't it?

**Review by lilyminium — CHANGES_REQUESTED** [review]
Thanks for opening this PR, @HeetVekariya -- however, I'm not sure that changing the output is the best solution to the failing doctest. The differences are somewhere around the ~15th decimal place, which seems to me to simply arise from precision error. IMO a more permanent solution to this issue might be to change it into a format that only prints out maybe the first 6 decimal places, using something like string formatting (with `print`) or rounding -- what do you think?

**Comment by HeetVekariya** [comment]
@lilyminium 
- At the start i am thinking about the rounding, but thought that it is meant to have upto 17 decimals. 
- But if you allow i can do round off upto 6 decimals.

**Comment by lilyminium** [comment]
Yes sure please do, rounding seems like the best solution here.

**Review by lilyminium — APPROVED** [review]
This LGTM but I'm confused why CI is failing -- restarting now.

**Comment by lilyminium** [comment]
Sorry for the delay -- thanks for fixing this @HeetVekariya! Could you please update the CHANGELOG?

**Comment by HeetVekariya** [comment]
@lilyminium sorry for late response, I have updated the change log.

**Comment by orbeckst** [comment]
@lilyminium could you please check in on this PR? You approved it a while back but it hasn't been merged. Thanks!

**Comment by lilyminium** [comment]
Thanks @HeetVekariya -- merging now!

**Comment by HeetVekariya** [comment]
Thank you for merging 🙏

**Pull request merged**
