### PR TITLE
fixes for pylint 2

### LINKED ISSUE #1992: Pylint is broken
Pylint is currently failing on travis, it seems to be picking up new errors that we previously ignored. 

I've not been able to reproduce the errors that travis gives locally, otherwise I'd just fix the line it complains about.

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #1992

### CODE REVIEW

**Comment by richardjgowers** [comment]
@MDAnalysis/coredevs can I get this merged so PRs pass again

**Comment by jbarnoud** [comment]
The lint build should not be allowed to fail anymore.

**Comment by orbeckst** [comment]
Sorry, didn't realize that we allowed it to fail somewhere https://github.com/MDAnalysis/mdanalysis/blob/5f151b48525a5d1d3d00b73855dbf6fe88960b69/.travis.yml#L79

**Comment by orbeckst** [comment]
@richardjgowers can you enable it again in a new PR – just revert e8b2b176dd77d5072eae64b62d3828c2451fc5bf

**Pull request merged**
