### PR TITLE
[fmt] setup.py and visualization

### PR DESCRIPTION
**Pull request by RMeli**
Changes made in this Pull Request:
 - Automatic formatting of `setup.py`
 - Automatic formatting of `visualisation/`

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4726.org.readthedocs.build/en/4726/

### CODE REVIEW

**Comment by RMeli** [comment]
Depends on https://github.com/MDAnalysis/mdanalysis/pulls and needs to be added to `.git-blame-ignore-revs`

**Review by marinegor — APPROVED** [review]
Looks good, sorry for the slow review!🐌

**Comment by marinegor** [comment]
> Depends on https://github.com/MDAnalysis/mdanalysis/pulls and needs to be added to `.git-blame-ignore-revs`

I didn't quite get this part

**Review by orbeckst — APPROVED** [review]
LGTM.

But please wait with merging until _after 2.8.0 release_.

I asssume you'll also create/update `.git-blame-ignore-revs` ?

**Comment by RMeli** [comment]
> I asssume you'll also create/update .git-blame-ignore-revs ?

Yes. As discussed in https://github.com/MDAnalysis/mdanalysis/pull/4725#issuecomment-2412050407, I am tagging formatting PRs with `[fmt]` and they will be squash-merged. They will be added to `.git-blame-ignore-revs` once they are squash-merged (maybe pooling a few together).

**Comment by RMeli** [comment]
Temporarily converted to draft to prevent an accidental merge before the release.

**Pull request merged**
