### PR TITLE
MAINT: fix invalid escape seqs

### PR DESCRIPTION
**Pull request by tylerjereddy**
* invalid escape sequences in `str/bytes` are deprecated
in newer versions of Python: https://bugs.python.org/issue27364

* fix the various `DeprecationWarning: invalid escape sequence \..`
warnings emitted by our full test suite, mostly by using raw strings
`r'...'` to allow use of internal `\` for strings targeted for regular expressions
and for docstrings that use `\` for diagrams and other things

* full test suite warning count drops slightly from 30,298 to 30,275 in my Python
3.8 venv

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by jbarnoud** [comment]
Maybe you could add an entry in the CHANGELOG?

**Comment by tylerjereddy** [comment]
hmm, I could, nothing user-facing though? Perhaps I could turn those warnings into errors, and then it would warrant an entry and prevent "regressions."

**Comment by orbeckst** [comment]
I like your idea of preventing regressions – please do!

**Comment by tylerjereddy** [comment]
Ok, see the second commit for the PR revisions based on feedback

**Comment by orbeckst** [comment]
Well... that's now a bottomless pit of fixing strings, and least when I try it locally... I started and will push updates but that might be a lot of work.

**Comment by tylerjereddy** [comment]
Hmm, maybe not worth too much time for now then. I wonder why I only caught cases in the test suite proper when I did it locally. Maybe the fresh rebuild in CI on top of the site.cfg change or something.

**Comment by orbeckst** [comment]
I have a fair amount done... but just ran into other minor things.

**Comment by orbeckst** [comment]
Now passes locally. Sorry, I force-pushed without too much thinking.

**Comment by orbeckst** [comment]
I think I'll want to merge a working develop into this one before merging, just to see that the CI really passes.

**Comment by orbeckst** [comment]
@jbarnoud can I please leave it to you to shepherd the PR to completion? Ping me if you need me to do anything else.

**Comment by orbeckst** [comment]
No idea why sphinx is suddenly complaining in https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/372482678 
```
Warning, treated as error:

/home/travis/build/MDAnalysis/mdanalysis/package/doc/sphinx/source/documentation_pages/core_modules.rst:36:toctree contains reference to document 'documentation_pages/core/topologyattrs' that doesn't have a title: no link will be generated
```
sigh...

**Comment by orbeckst** [comment]
Fixed the merge conflict, rebased against develop, consolidated commits (so that it can just be _merged_), and fixed the docs so that they build. 

Locally
- tests pass **================================ 17007 passed, 109 skipped, 4 xfailed, 2 xpassed, 38380 warnings in 713.78s (0:11:53) =================================**
- docs build

**Comment by orbeckst** [comment]
This is now looking good and the lower diff coverage  comes from changing strings in parts of files that haven't been tested before.

**Comment by tylerjereddy** [comment]
Thanks, this turned out to be more work than I could handle on a short timescale.

**Pull request merged**
