### PR TITLE
Make NoDataError subclass of AttributeError and add informative error messages

### LINKED ISSUE #2565: Improve missing AtomGroup property error messages
**Expected behavior**
When I try to access an `AtomGroup` property that is generally valid but the corresponding data is missing from the underlying topology/trajectory, I expect a `NoDataError` with a message stating that the data I am requesting is not available from the topology/trajectory.

**Actual behavior**
When I load a topology that doesn't contain information about, e.g., charges, and try to access that `AtomGroup` property, an `AttributeError: AtomGroup has no attribute charges` is raised.

**Code to reproduce the behavior**
``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import GRO
u = mda.Universe(GRO)
u.atoms.charges
```

**Version of MDAnalysis**
Current 0.20.1 dev branch with Python 3.6 under Fedora 31
Should be version-independent though.

**Detailed problem description**
The `AttributeError` still makes sense if one tries to access an attribute that is generally unknown to `Atom` or `AtomGroup`. Thus, one needs to distinguish between attributes which *could* be there if the respective topology/trajectory info was there, and others that generally don't exist.
Furthermore, there are *derived* attributes such as `fragindices`, which are constructed from the topology's `bond` information. Thus, the error message for such derived attributes should state the missing information from which they are derived. The same is true for methods that require certain data, so that trying to access `AtomGroup.center_of_mass()` should raise a `NoDataError` due to missing information about masses.

Some examples: in the code example given above
* `u.atoms.boogiewoogie` should raise an `AttributeError`
* `u.atoms.charges` should raise a `NoDataError` due to missing charge information
* `u.atoms.fragindices` should raise a `NoDataError` due to missing bond information
* `u.atoms.unwrap()` should raise a `NoDataError` due to missing bond information
* `u.atoms.total_charge()` should raise a `NoDataError` due to missing charge information
* ...

**Proposed solution**
1. Create a dictionary with all *known* `AtomGroup` attributes as keys and the corresponding topology/trajectory information which is required for the attribute to exists.
2. Do the same for all known `Atom` attributes.
3. In the `__getattr__()` methods of `Atom` and `AtomGroup`, check whether the requested attribute is present in the respective dictionary's keys. If (and only if) that is the case, raise a `NoDataError` with an error message clarifying the problem. Otherwise, do nothing so that an `AttributeError` is automatically raised whenever a truly unknown attribute is accessed.
4. Write tests which cover all possible outcomes.

Regarding points 1 and 2, this involves parsing the `transplants` of `AtomGroup` and probably also those of `Atom`. Thanks to @richardjgowers we know how to automate the process so that the bookkeeping is done automatically, see his [comment](https://github.com/MDAnalysis/mdanalysis/issues/2565#issuecomment-594092648) below.

### LINKED ISSUE #2635: Testing for fragment attribute
## Expected behavior ##
Checking for the `fragment` attribute 

```python
from MDAnalysisTests.core.util import UnWrapUniverse
u = UnWrapUniverse(have_molnums=False, have_bonds=False)

print(hasattr(u,"fragments"))
print(hasattr(u.atoms, "fragments"))
```

should give the following consistent output

```python
False
False
```

## Actual behavior ##

However, while the first works fine and returns `False` the second raises a `NoDataError`.

```python
/usr/local/lib/python3.7/site-packages/MDAnalysis/core/groups.py in __getattr__(self, attr)
   2222             # raise NDE(_ATTR_ERRORS[attr])
   2223             raise NoDataError("AtomGroup.{} not available; this requires Bonds"
-> 2224                               "".format(attr))
   2225         raise AttributeError("{cls} has no attribute {attr}".format(
   2226             cls=self.__class__.__name__, attr=attr))

NoDataError: AtomGroup.fragments not available; this requires Bonds
```

## Current version of MDAnalysis ##

- Which version are you using? 0.20.2-dev0
- Which version of Python: 3.7
- Which operating system? macOS

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #2635
Fixes #2565 
Mitigates https://github.com/MDAnalysis/mdanalysis/issues/2649#issuecomment-605176500

Changes made in this Pull Request:
 - added more informative error messages for topology attributes
 - made NoDataError subclass of AttributeError

```python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import GRO
>>> u = mda.Universe(GRO)
>>>
>>> u.atoms.altlocs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 2285, in __getattr__
    return super(AtomGroup, self).__getattr__(attr)
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 560, in __getattr__
    return super(GroupBase, self).__getattr__(attr)
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 385, in __getattr__
    raise AttributeError(err)
AttributeError: AtomGroup has no attribute altlocs. Did you mean altLocs?
>>>
>>> u.atoms[0].resnames
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 3701, in __getattr__
    return super(Atom, self).__getattr__(attr)
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 3576, in __getattr__
    singular=cls.singular))
AttributeError: Atom has no attribute resnames. Do you mean resname?
>>>
>>> u.atoms.unwrap()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 1643, in unwrap
    "".format(self.__class__.__name__))
MDAnalysis.exceptions.NoDataError: AtomGroup.unwrap() not available; this requires Bonds
>>>
>>> u.residues.bonds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 558, in __getattr__
    raise NoDataError(err.format(singular=cls.singular))
MDAnalysis.exceptions.NoDataError: This Universe does not contain bonds information
>>>
>>> u.atoms[0].total_charge()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 3705, in __getattr__
    return super(Atom, self).__getattr__(attr)
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 3585, in __getattr__
    return super(ComponentBase, self).__getattr__(attr)
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 373, in __getattr__
    selfcls=selfcls))
AttributeError: total_charge() is a method of AtomGroup, not Atom
```

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by richardjgowers** [comment]
Ok I'm confused by this, what did this break exactly? It seems like a good idea.

**Comment by lilyminium** [comment]
@richardjgowers Making NoDataError a subclass of AttributeError (instead of just making a new error, as in this iteration of the PR) broke because of how `__getattribute__` handles `AttributeError`s. 

A few property getters e.g. ``Atom.velocity`` raise `NoDataError`s if there is missing information. When `NoDataError` is just a `ValueError` it behaves normally and gives the user the error message. When `NoDataError` is also an `AttributeError`, `__getattribute__` sends the original key to `__getattr__`, completely ignoring the original traceback. So originally:

```python
>>> u.atoms.velocities
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 2454, in velocities
    raise_from(NoDataError("Timestep does not contain velocities"), None)
  File "<string>", line 3, in raise_from
MDAnalysis.exceptions.NoDataError: Timestep does not contain velocities
```
When NoDataError is subclass of AttributeError:

```python
>>> u.atoms.velocities
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdanalysis/package/MDAnalysis/core/groups.py", line 2226, in __getattr__
    cls=self.__class__.__name__, attr=attr))
AttributeError: AtomGroup has no attribute velocities
```

This is because currently `__getattr__` only checks a very limited number of known attributes to return a NoDataError. Since a lot of the code base relies on catching NoDataErrors rather than AttributeErrors, it broke a lot of downstream stuff like writing out files. So, it could be a workable solution if #2565 is fixed.

**Comment by zemanj** [comment]
Yeah I also think that making `NoDataError` a subclass of `AttributeError` in conjunction with what's to be done in #2565 is the way to go. FWIW, that should also unify Py27/3x behavior (IIRC `hasattr()` swallows *any* exception in `__getattr__()`  in Py27).

**Comment by lilyminium** [comment]
> (IIRC hasattr() swallows any exception in __getattr__() in Py27).

Yep that's right.

Alrighty, I'll put this on hold and add in #2565 stuff if no one fixes that by the end of the GSOC application period?

**Comment by zemanj** [comment]
> Alrighty, I'll put this on hold and add in #2565 stuff if no one fixes that by the end of the GSOC application period?

Awesome! :+1:

**Comment by lilyminium** [comment]
Sorry @IAlibay, misclick while I was trying to add the Work In Progress label...

**Comment by lilyminium** [comment]
@richardjgowers I think so; I did add some extra stuff beyond the original issue (e.g. suggesting when methods are AtomGroup vs Atom or checking for capitalisation and plurals), so just checking that that's both welcome and doesn't overly affect performance?

**Comment by richardjgowers** [comment]
From what I can tell it’s only performance heavy when things fail, and that’s to give a better error message.

**Pull request merged**
