### PR TITLE
Prerelease 2.0.0

### PR DESCRIPTION
**Pull request by IAlibay**
Towards 2.0.0

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
lgtm

**Comment by orbeckst** [comment]
(Technically speaking, merges into master do not require an approval...)

**Comment by IAlibay** [comment]
Thanks @orbeckst I'm going to squash-merge without waiting for CI given that we're going to run testpypi half a dozen times so merge CI will have come back to shout at us if there's any issues by then.

**Comment by orbeckst** [comment]
Docs build ... but the introductory parts just need to be chopped to pieces and burned.

**Comment by IAlibay** [comment]
> Docs build ... but the introductory parts just need to be chopped to pieces and burned.

Sorry I didn't catch that, what did you mean?

**Comment by orbeckst** [comment]
Sorry, was in a hurry when I wrote this.

What I meant was: I did not wait for all CI to pass but checked the docs that had already built. These looked good in the sense that version and date were 2.0.0 and today. But then I browsed the docs and was reminded that the initial chapters are just terrible and outdated and we would be better off if they weren’t there and just had a link to the fantastic User Guide. 

Nothing to be done for the 2.0.0 release but something to be done in the not too distant future.

**Pull request merged**
