### PR TITLE
Fix trz endian

### LINKED ISSUE #1424: IOError in MDAnalysis/coordinates/TRZ.py", line 242, in _read_trz_header on big-endian arches
### Expected behaviour
Testsuite passes.

### Actual behaviour
67 tests fail with:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/builddir/build/BUILD/MDAnalysis-0.16.1/MDAnalysisTests-0.16.1/MDAnalysisTests/analysis/test_hydrogenbondautocorrel.py", line 37, in setUp
    u = self.u = mda.Universe(TRZ_psf, TRZ)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/core/universe.py", line 278, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/core/universe.py", line 426, in load_new
    self.trajectory = reader(filename, **kwargs)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/coordinates/TRZ.py", line 175, in __init__
    self._read_trz_header()
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/coordinates/TRZ.py", line 242, in _read_trz_header
    raise IOError
IOError: 
```

### Code to reproduce the behaviour

Run the testsuite on a big-endian arch like ppc64 or s390x. Example failure on ppc64: https://koji.fedoraproject.org/koji/taskinfo?taskID=20061305 (see build.log).

### Current version of MDAnalysis:
0.16.1

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #1424  
Replaces PR #1425  

Changes made in this Pull Request:
 - set endianness in TRZ Reader and Writer to little endian

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
@rathann please check that you're happy with this.

**Comment by orbeckst** [comment]
To the merge master: Be careful when merging so that @rathann remains the author; I think this requires a simple merge commit instead any of the rebase variants.

You might also want to merge #1426 first into develop and then resolve a merge commit in CHANGELOG (because I had to create the new 0.17.0 section here, too).

**Comment by kain88-de** [comment]
I'm trying to squeeze this into 0.16.2

**Comment by richardjgowers** [comment]
@kain88-de I'd be pretty amazed if someone else was using this format, I think we can put it into 17.0 instead

**Comment by kain88-de** [comment]
OK

**Pull request merged**
