### PR TITLE
Remove as_Universe (Issue #2920)

### LINKED ISSUE #2920: remove universe.as_Universe
`universe.as_Universe` is not really needed
https://github.com/MDAnalysis/mdanalysis/blob/45e56e8314c278e3eb98ed7a6029b74e7435e8be/package/MDAnalysis/core/universe.py#L1327-L1328 and can be removed.

EDIT: @IAlibay found in PR #2922 that LeafletFinder is also affected and will not anymore accept a filename as input

- [ ] remove for 2.0.0
- [x] deprecate as_Universe in 1.0.1 (see PR #2798 )
- [x] deprecate filename argument for LeafletFinder in 1.0.1

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #2920

Changes made in this Pull Request:
 - Removes `as_Universe` from MDAnalysis.core.universe
 - :class:`MDAnalysis.analysis.leaflet.LeafletFinder` no longer accepts paths to files for the `universe` argument.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Review by lilyminium — DISMISSED** [review]

**Comment by lilyminium** [comment]
Looks good! Weird that there were no tests for as_Universe.

**Comment by IAlibay** [comment]
> Looks good! Weird that there were no tests for as_Universe.

Yeah it looks like it was only covered indirectly via LeafletFinder (that or I missed something and I'm going to wake up to Travis complaining 🤷‍♂️ )

**Comment by lilyminium** [comment]
```
    def test_as_Universe():

>       assert mda.as_Universe is mda.core.universe.as_Universe

E       AttributeError: module 'MDAnalysis' has no attribute 'as_Universe'
```

Oops, grepped in the wrong folder. There is a test...

**Review by lilyminium — CHANGES_REQUESTED** [review]
Please remove test :-)

**Review by lilyminium — APPROVED** [review]

**Pull request merged**
