### PR TITLE
updated changelog

### PR DESCRIPTION
**Pull request by aditi2906**
Fixes #

Changes made in this Pull Request:
 - 
Updated Changelog for contribution done to issue#3568 in the pr #3631

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
Looks good, but fix the conflicts, please.

Feel free to ping me to re-review so that this can get merged quickly.

**Review by IAlibay — CHANGES_REQUESTED** [review]
I believe you also need to add yourself to AUTHORS?

**Comment by aditi2906** [comment]
@IAlibay I had appended my name in the authors list long back during my first PR, hence I only added my name to the changelog file.

**Review by orbeckst — APPROVED** [review]

**Comment by IAlibay** [comment]
> @IAlibay I had appended my name in the authors list long back during my first PR, hence I only added my name to the changelog file.

sorry about that hadn't realised, lgtm!

**Review by IAlibay — APPROVED** [review]

**Pull request merged**
