### PR TITLE
Docs disable travis button

### PR DESCRIPTION
**Pull request by orbeckst**
The docs show the Travis status for master in the sidebar. However, the master travis CI sometimes fails and then this shows a red fail button, which is ugly and not representative of the actual state of the code. 

I have not found a way to change it to eg show dev and in any case, the master docs relate to the releases. I think the best approach is to just remove the Travis CI status button. It also focuses the reader more on the docs.

Changes made in this Pull Request:
 - disable the travis button in docs sidebar

PR Checklist
------------
 - n/a Tests?
 - [x] Docs?
 - n/a CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
@orbeckst can you remove the rmsd changes. Then this is OK

**Comment by orbeckst** [comment]
Oops, sorry, 403f9eb and  956e6a5  should have been in another commit... will remove and rebase.

**Comment by orbeckst** [comment]
Removed commits belonging to PR #1581 and force-pushed.

**Comment by orbeckst** [comment]
Hm, I still see the Travis button. Need to look into why. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
Looking at the local build of the docs, the button is not there anymore. 

It seems that the merge did not build the docs on gh-pages because the last commit that I see there (2bff4a1e091c7a44803b5d919441cdae4c41c1ae) does not reference  952012 (the merge from this PR) but 09d168c (which belonged PR #1611).

I'll have a look at Travis...

**Comment by orbeckst** [comment]
... oh, because Travis is still running https://travis-ci.org/MDAnalysis/mdanalysis/builds/264468525 we don't have the updated docs yet.

**Comment by orbeckst** [comment]
Now all good.

**Comment by kain88-de** [comment]
alternatively you can also reload without the cache using `C-S-r`. This is helpful if you have old versions of a website cached for quicker access.

**Pull request merged**
