### PR TITLE
fix TRZ file reader on big-endian architectures

### LINKED ISSUE #1424: IOError in MDAnalysis/coordinates/TRZ.py", line 242, in _read_trz_header on big-endian arches
### Expected behaviour
Testsuite passes.

### Actual behaviour
67 tests fail with:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/builddir/build/BUILD/MDAnalysis-0.16.1/MDAnalysisTests-0.16.1/MDAnalysisTests/analysis/test_hydrogenbondautocorrel.py", line 37, in setUp
    u = self.u = mda.Universe(TRZ_psf, TRZ)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/core/universe.py", line 278, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/core/universe.py", line 426, in load_new
    self.trajectory = reader(filename, **kwargs)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/coordinates/TRZ.py", line 175, in __init__
    self._read_trz_header()
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/coordinates/TRZ.py", line 242, in _read_trz_header
    raise IOError
IOError: 
```

### Code to reproduce the behaviour

Run the testsuite on a big-endian arch like ppc64 or s390x. Example failure on ppc64: https://koji.fedoraproject.org/koji/taskinfo?taskID=20061305 (see build.log).

### Current version of MDAnalysis:
0.16.1

### PR DESCRIPTION
**Pull request by rathann**
Fixes #1424 .

Changes made in this Pull Request:
 - all ints and floats should be read as little-endian from TRZ files

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
@rathann your git history seems to be a bit confused. Do you mind cleanint it up. It seems to be that you only want to add the last commit.  I recommend to use feature branches in your own repository to keep these things from happening.

**Comment by rathann** [comment]
@kain88-de Yes, sorry. I'll try, though I'm not quite sure how to do it. Feel free to reject this PR and just cherry-pick the last commit.

**Comment by kain88-de** [comment]
@rathann can you please include a CHANGELOG entry and a comment in the docs that MDAnalysis expects little endian trz files.

**Comment by orbeckst** [comment]
> Yes, sorry. I'll try, though I'm not quite sure how to do it. Feel free to reject this PR and just cherry-pick the last commit.

In general:
```
git checkout develop
git pull
git checkout -b fix-trz-endian   # create feature branch
# hack and add on your branch
# ...
git add package/MDAnalysis/coordinates/TRZ.py
git commit ...
git push -u origin fix-trz-endian 
```

and then do the PR. Typically, don't merge develop into your branch if you can avoid it because we often use squash and that does not always works well with merges.

**Comment by orbeckst** [comment]
I am replacing this PR with #1427.

**Pull request closed without merging**
