### PR TITLE
remove TimeseriesCollection

### LINKED ISSUE #186: Timeseries not implemented for gromacs
```
What steps will reproduce the problem?
1. trj=MDAnalysis.Universe(tpr_file,xtc_file
2. trj..trajectory.timeseries(short.selectAtoms("backbone"))

What is the expected output? What do you see instead?
I would like to get a timeseries object but instead I get this error"

NotImplementedError: timeseries not available for Gromacs trajectories


What version of the product are you using? On what operating system?
0.8.1

Please provide any additional information below.

I played around for a while just trying to verbatim copy the timeseries code 
from the file DCD.py but I could not get that to work. Ultimately I would like 
to have a corel functionality as is implemented for DCDs. I realize that I 
could just convert my trajectory to a dcd (from xtc or trr), but I would like a 
cleaner solution. I don't mind implementing this myself if anyone has any 
suggestions.

```

Original issue reported on code.google.com by `e.jjorda...@gmail.com` on 24 Jun 2014 at 5:47

### LINKED ISSUE #1373: Remove TimeSeries
We discussed recently to remove the TimeSeries objects from MDAnalysis. As far as I know none of the core devs is using it.  We also note that it is unlikely we will ever implement TimeSeries for any other readers besides dcd and memory and most of it's function can be replaced by the Analysis Framework.

The only part in the library that uses TimeSeries is encore. So it would be useful get some input from @wouterboomsma and @mtiberti before we go ahead with this.

As a first step I would remove timeseries from DCD during the cython transition. 
In a later step we would remove timeseries from memory reader and remove  the core TimeSeries class.

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #1373 
Fixes #186

Changes made in this Pull Request:
 - remove TimeseriesCollection

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
When would we do a 0.16.3 release possibly?

**Comment by richardjgowers** [comment]
@kain88-de do you mean 16.2 or 16.3?  We'd do a bugfix release if we got a few good fixes and 0.17 seemed a few weeks off still.

**Comment by kain88-de** [comment]
Once we start the pytest transition we won't be able to release for a couple of weeks anyway.

**Comment by kain88-de** [comment]
@richardjgowers This PR is currently a blocker for #1372. Personally it would be good if us devs use the new DCD reader for a while as on a dev version before we make a release.

**Pull request merged**
