### PR TITLE
Implementation of Parallelization to analysis.bat

### LINKED ISSUE #4663: `MDAnalysis.analysis.bat`: Implement parallelization or mark as unparallelizable
Given a newly implemented parallelization (https://docs.mdanalysis.org/dev/documentation_pages/analysis/parallelization.html), implement it for all classes in `analysis.bat` module. You may use `analysis.RMSD` in `develop` as a reference.

You need to add:

 - appropriate implementation of result aggregation for AnalysisBase subclasses in `analysis.bat` module (or explicitly limit available backends if the classes aren't parallelizable)
 - a boilerplate fixture(s) to `testsuite/analysis/conftest.py`, analogous with existing ones
 - a `client_...` fixtures to all tests using in `testsuite/MDAnalysisTests/analysis/test_bat.py`, and modify the way run() method is called

### PR DESCRIPTION
**Pull request by talagayev**
Fixes #4663 

Changes made in this Pull Request:
 - parallelization of  the class  `BAT` in `analysis.bat.py`
 - addition of parallelization tests (including fixtures in analysis/conftest.py)
 - update of CHANGELOG

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4693.org.readthedocs.build/en/4693/

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM @talagayev!

**Comment by talagayev** [comment]
> LGTM @talagayev!

Perfect :)

**Comment by hmacdope** [comment]
Just need to fix conflicts.

**Comment by talagayev** [comment]
> Just need to fix conflicts.

Done :)

**Review by orbeckst — CHANGES_REQUESTED** [review]
Please also add a versionchanged, can copy from gnm. Thanks.

**Comment by talagayev** [comment]
> Please also add a versionchanged, can copy from gnm. Thanks.

Added the versionchanged in the BAT class, will resolve now the conflicts :)

**Comment by hmacdope** [comment]
@orbeckst can you re-review here?

**Review by orbeckst — APPROVED** [review]

**Comment by orbeckst** [comment]
Thanks @talagayev !

**Comment by talagayev** [comment]
> Thanks @talagayev !

Happy to help :)

**Pull request merged**
