### PR TITLE
Added unwrap/wrap transformations

### PR DESCRIPTION
**Pull request by davidercruz**
Adds a wrap transformation based on atoms.wrap and a unwrap transformation based on @richardjgowers  's _cutil.make_whole
Replaces PR #2020 

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by jbarnoud** [comment]
There may have been a solution to save the previous PR, but this is much easier.

2 comments:
* the test for the `compound` argument does not test that the behavior is different from one value to the other;
* the linter is unhappy: <https://travis-ci.com/MDAnalysis/mdanalysis/jobs/139284717#L645>

Except for that, it looks good to me.

**Comment by orbeckst** [comment]
If there are any more changes on this branch you will need to merge or rebase against develop because #2066 was "fixed".

**Comment by orbeckst** [comment]
@jbarnoud can you please make your comments https://github.com/MDAnalysis/mdanalysis/pull/2038#issuecomment-412059572 a formal review so that the PR gets a chance to get merged?

**Comment by orbeckst** [comment]
@davidercruz (and @jbarnoud ?) could you please summarize what needs to be done to get this PR done? 

I am not looking for a promise that this gets done over the next weekend/holidays but something that will help to get the work done. This is an open source project so I understand that everyone is short on time and priorities shift but it would be a real shame if this didn't make it into MDAnalysis. It is always possible that someone else might find the energy to finish it (e.g., @ianmkenney in my group has recently been playing with the OTFT) but in this case one should make it easy for others to pick up the work, especially if one has not been able to finish things.

**Comment by richardjgowers** [comment]
@orbeckst I’m happy to try and help Ian get up to speed after Xmas

**Comment by davidercruz** [comment]
Hi all, the PR is failing due to taking too long on travis. It's probably due to the tests that use the GRO and TPR systems used in the  `test_wrap_with_compounds` in the test module. This function tests the `compound` flag for the wrap transformation, and thus requires a test system where the flags `group`, `residues`, `segments` and `fragments` are applicable.

The transformation themselves are very simple, as they act as a caller for the wrap and unwrap functions of the `Atomgroup`. I just need someone to review the code and I'll make the changes during the holidays.

Merry Christmas

**Comment by orbeckst** [comment]
@jbarnoud @richardjgowers @davidercruz any chance that this gets into 0.20.0 #2240 (as we had promised in the 0.19.x blog post)?

**Comment by orbeckst** [comment]
I merged develop into this branch and updated the CHANGELOG entry (has to go into 0.21).

**Comment by orbeckst** [comment]
I rewrote the history and rebased against develop.

*Merge* this branch (don't rebase).

**Comment by orbeckst** [comment]
So – this is finally done! Thank you @davidercruz and @jbarnoud !

(Now it just needs to be fast... but that's a different story, starting with #2376.)

**Pull request merged**
