### PR TITLE
Pre release 2.6.0

### PR DESCRIPTION
**Pull request by IAlibay**
Changes made in this Pull Request:
 - The usual stuff for a new release - we are in a code freeze as soon as this is done. 
 - Add in upper pins on NumPy so we don't have folks using 2.0 when it comes out.

PR Checklist
------------
 - [x] CHANGELOG updated?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
:books: Documentation preview :books:: https://mdanalysis--4241.org.readthedocs.build/en/4241/

### CODE REVIEW

**Comment by IAlibay** [comment]
@MDAnalysis/coredevs can I have a quick thumbs up here? 

see here for tthe relevant step in the release process: https://userguide.mdanalysis.org/dev/preparing_releases_and_hotfixes.html#getting-the-develop-branch-ready-for-a-release

**Review by orbeckst — APPROVED** [review]
lgtm 🚀

**Review by RMeli — COMMENTED** [review]
LGTM, but I guess the list of relevant files to be changed in the User Guide needs to be updated?

**Comment by IAlibay** [comment]
> LGTM, but I guess the list of relevant files to be changed in the User Guide needs to be updated?

Ah thanks for pointing it out, looks like I deleted the `meta.yaml` a couple of PRs back. I'll open a PR there.

**Pull request merged**
