### PR TITLE
Removed weakref system from Atom.universe.

### LINKED ISSUE #297: __del__ destructor for Universes?
The title says it all. @richardjgowers mentioned it'd be interesting to implement, but currently that leads to mem leaks as the garbage collector can't clean up the Universe.

See the discussion on #293.

If Universe has a __del__ I end up with two uncollectables: the Universe itself and the trajectory (which also has a __del__). I tried to find any sort of circular reference between the two, but found nothing.
Is it worth pursuing this?

### PR DESCRIPTION
**Pull request by richardjgowers**
Atoms now hold a strong/real reference to the Universe

Fixes #297

### CODE REVIEW

**Comment by kain88-de** [comment]
Could you add a test that an AtomGroup keeps the data of the current TimeStep even after the Universe has gone out of scope.

Yeah otherwise my use case works.

**Comment by kain88-de** [comment]
Can [this](https://github.com/MDAnalysis/mdanalysis/blob/495ba5d0289277f1ff86f9062766f743a0199d56/package/MDAnalysis/core/AtomGroup.py#L1049) `AttributeError` in `AtomGroup.py` still be triggered?

```python
 def __getattr__(self, name):
        try:
            return self._get_named_atom(name)
        except SelectionError:
            raise AttributeError("'{0}' object has no attribute '{1}'".format(
                    self.__class__.__name__, name))
```

This is the execption that is triggered in the current `develop` branch.

**Comment by mnmelo** [comment]
That is the generic `__getattr__` error for the selection shorthands. If you invoke it on an `AtomGroup` that doesn't have any `Atom` named as such, you don't get a `SelectionError` (which was previous behavior), you get an `AttributeError`:

```python
ag.WRONG_AT_NAME #this raises AttributeError
```

We found it to be a bad idea to raise `SelectionError` here because a lot of base code relies on `AttributeError` being raised for, well, missing attributes. In particular, pickling code check for that error when probing for a `__getstate__` function.

**Comment by mnmelo** [comment]
@richardjgowers, I found no leaks. All seems well, including `AtomGroup` picklability.
I'm hijacking your PR to add one more test to that functionality, and fix some cosmetic typos.

**Comment by richardjgowers** [comment]
The code ending up in `__getattr__` was a little confusing.  When an AtomGroup looked for a Universe, it checked the first Atom.  This Atom returned AttributeError, because it was out of scope, so the AtomGroup then went into its `__getattr__` loop.

I've changed Atom and AtomGroup so a lack of Universe raises a NoDataError rather than either AttributeError or None respectively

**Pull request merged**
