### PR TITLE
Removed python as travis language

### PR DESCRIPTION
**Pull request by richardjgowers**
PR #986 changed the language in the travis file to Python, but this makes OSX fail.  I think this is because we don't actually use a python container, because we install our own python binary with conda.  This might fix it...

### CODE REVIEW

**Comment by kain88-de** [comment]
Can you also correct the minimal install while you are tweaking the travis config.

**Comment by richardjgowers** [comment]
I'm not sure how to fix it?  You can edit this directly if you know how

**Comment by kain88-de** [comment]
Looks like we need to add some guards to the imports for analysis packages here.

**Comment by richardjgowers** [comment]
@kain88-de looks like OSX has a weird bug that we'll have to debug somewhere else.  Is this good to go on your side?

**Comment by kain88-de** [comment]
Once you remove your changes again so that travis does tribute this again as a python build it's good to go.

**Comment by richardjgowers** [comment]
It needs to be a ruby build for osx to ever work, so I need to keep it as the first step of getting osx to work

**Comment by kain88-de** [comment]
This now only changes the minimal environment.

**Pull request merged**
