### PR TITLE
Adds temporary warning on accuracy of RDKit converter

### PR DESCRIPTION
**Pull request by IAlibay**
As discussed in https://github.com/MDAnalysis/mdanalysis/pull/3044#issuecomment-900521290 this adds a warning to mention that future changes that will improve the accuracy of the RDKit converter are coming. This will allow us to accelerate the 2.0 release and put @cbouy's awesome work to 2.1.0.

PR Checklist
------------
 - Tests?
 - Docs?
 - CHANGELOG updated?
 - Issue raised/referenced?

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
[That was a freebie](https://www.youtube.com/watch?v=9ltqCJn7qkc).

**Review by cbouy — APPROVED** [review]
LGTM!
Do we also need an actual warning in the code?

**Comment by IAlibay** [comment]
> LGTM!
> Do we also need an actual warning in the code?

At least to me 90% coverage of chemical space is good enough that it's probably not worth bothering folks with endless warnings, especially given that your updated code will hopefully make it in 2.1.0 (which I hope we can release without waiting for the 6 month cycle).

That being said @orbeckst is probably a better judge of this.

**Comment by orbeckst** [comment]
I also would not bother people with the warning. Labeling the code in the docs (and CHANGELOG?) as experimental is good enough for right now.

**Comment by orbeckst** [comment]
Forget about my CHANGELOG comment... it's fine.

**Pull request merged**
