### PR TITLE
Testing coveralls..

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by mnmelo** [comment]
... no coveralls comments ... :(

**Comment by orbeckst** [comment]
I don't know why.

We could delete ourselves from coveralls and then sign up again?

**Comment by orbeckst** [comment]
Is this related to #971 ?

The actual coveralls report for this PR exists, https://coveralls.io/builds/7762976 but coveralls is not talking to GitHub.

**Comment by richardjgowers** [comment]
Yes, I'm trying to trigger a failure on the merge button.  I've changed it back to comments and **not** API... lets see if the settings panel actually makes any difference!

**Comment by mnmelo** [comment]
Regarding deleting the coveralls repo, we'd lose back coverage history, right? It'd be nice to keep it to see how long we've come.

**Comment by kain88-de** [comment]
Can we plot the history or extract the data? Also should we update the coverage disclaimer on the first README.rst?

**Comment by orbeckst** [comment]
That's the nuclear option. Maybe there's a support group or issue tracker for coveralls. Does anyone know?

Or tweet at them?

--
Oliver Beckstein
email: orbeckst@gmail.com

**Pull request closed without merging**
