### PR TITLE
Adds python_requires >= 3.6 to develop

### LINKED ISSUE #3333: [2.0.0 release] fix setup.py requires
Moving from 1.x -> 2.0, we lost the python_requires entry. We should add one back so that we can prevent folks from trying to install MDA 2.0 on py<3.6.

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #3333 

Simple one, we're just adding a python_requires back so that folks don't try to install with py3.5 or py2.7.

Changes made in this Pull Request:
 - adds back a `python_requires` to setup.py

PR Checklist
------------
 - Tests?
 - Docs?
 - CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
Does what it tries to fix. LGTM

(Good catch on missing threadpoolctl, I hope nothing else is missing)

**Comment by IAlibay** [comment]
> Does what it tries to fix. LGTM
> 
> (Good catch on missing threadpoolctl, I hope nothing else is missing)

So GSD is missing from that list, but both it and threadpoolctl are in `install_requires`, so for most cases it's fine? I'll raise an issue though.

**Comment by IAlibay** [comment]
Actually @orbeckst is `requires` just deprecated? I found this comment in your PR for #2738:

"- removed deprecated 'requires' in setup.py (see
  https://setuptools.readthedocs.io/en/latest/setuptools.html#developer-s-guide)"

But I'm not seeing what it refers to. If we can confirm it's no longer needed I'll just delete it out here.

**Comment by IAlibay** [comment]
Ok yeah, it is deprecated, see: https://setuptools.readthedocs.io/en/latest/history.html?highlight=requires#id359

I'll just remove it.

**Review by orbeckst — APPROVED** [review]
Good that you found out about ditching `requires` — I had totally forgotten against my PR against 1.0. All good here.

**Pull request merged**
