### PR TITLE
[WIP] ITP topology Writer

### PR DESCRIPTION
**Pull request by xiki-tempula**
Changes made in this Pull Request:
My project requires me to write an ITP writer. Thus, I'm thinking of creating a topology writer which will write the text-based itp file from the topology file read with ITPPraser. I haven't seen any open PR about this so I guess I will just go on and write it?

However, I'm not too sure about where the file should be. I cannot seem to find any topology writer in the folder topology.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
So an MD theological question if you'd like, does an ITP file count as a coordinates file?

**Comment by xiki-tempula** [comment]
@IAlibay I'm very confused at the moment as I can only find TopologyReaderBase within the _Topologymeta.

**Comment by richardjgowers** [comment]
We don't really do writing Topologies currently, mostly because they contain a lot more information (ie forcefields) than we currently handle.  To further @IAlibay 's theological concerns, I think this package deals with MD stuff post simulation, rather than pre.  I think maybe the best way to write a topology would be to convert to a parmed structure (via converters) and work from there.

**Comment by xiki-tempula** [comment]
@richardjgowers Thank for the clarification. I will close this PR then.

**Pull request closed without merging**
