### PR TITLE
[WIP] CI build time

### PR DESCRIPTION
**Pull request by kain88-de**
I noticed that a single process run might be faster. I'm just doing a quick check.

### CODE REVIEW

**Comment by orbeckst** [comment]
What is the outcome of this inquiry? Can you post the timings, just for future reference?

**Comment by kain88-de** [comment]
Yes I wanted to write down the results. The good news is I think we can shrink the test times by deactivating plugins. The last run without any plugins only took 12 minutes.

**Comment by orbeckst** [comment]
Really?!?!? I mean, I can see it for myself. I am just very surprised (and also happy that we can potentially speeding up tests dramatically). Do you know which plugin slows down everything?

Ideally, this should get fixed but might be a moot point anyway when we switch to pytest #884 . Perhaps for right now, only enable plugins for local testing or when merging into develop??

**Comment by kain88-de** [comment]
I will do 2 more runs to check exactly which plugins causes the most slowdown. But a further refinement of the test matrix might already help.

**Comment by orbeckst** [comment]
Judging from [scikit-beam: Testing Guidelines: Testing for open files](https://scikit-beam.github.io/scikit-beam/development/testguide.html#testing-for-open-files) it might be the "open files" plugin:
> Scikit-beam can test whether any of the unit tests inadvertently leave any files open. Since this greatly slows down the time it takes to run the tests, it is turned off by default.

**Comment by orbeckst** [comment]
Ned Batchelder's (author of nose) [tl;dw: Speedily practical large-scale tests](https://nedbatchelder.com/blog/201206/tldw_speedily_practical_largescale_tests.html), a summary of a PyCon 2012 talk by Eric Rose, contains an interesting summary of techniques to speed up tests.

**Comment by orbeckst** [comment]
Btw, maybe *open files* is not the culprit because we are already running with `--no-open-files` since PR #1198 .

**Comment by kain88-de** [comment]
> it might be the "open files" plugin:

that is not active due to bugs currently.

> contains an interesting summary of techniques to speed up tests.

I had a though this morning that we can copy the datafiles to a tmpfs on a RAM disk. A move like that could significantly speed up I/O. But that would require a large scale refactoring of the tests and how we retrieve test files in them.

**Comment by orbeckst** [comment]
If were to install the complete test package in a RAM disk then it would work automatically without rewriting anything.

**Comment by jbarnoud** [comment]
How much RAM do we have access to on travis?

**Comment by kain88-de** [comment]
We only need about 100MB to install the testsuite. I found an [article](https://www.cyberciti.biz/faq/howto-create-linux-ram-disk-filesystem/) to create a ramdisk.

**Comment by orbeckst** [comment]
I think this will require sudo and we don't have that on the container-based travis instances.

**Comment by richardjgowers** [comment]
If we make everything a fixture with entire test scope, isn't that
essentially a ramdisk?

**Pull request closed without merging**
