### PR TITLE
Read XDR offsets from trajectory if file read-in fails

### LINKED ISSUE #1893: Failing to read XDR offsets is a fatal error
Sometimes loading xdr offsets fails. 

```python
  File "/home/user/miniconda2/envs/env/lib/python2.7/site-packages/MDAnalysis/coordinates/XDR.py", line 84, in read_numpy_offsets
    return {k: v for k, v in six.iteritems(np.load(filename))}
  File "/home/user/miniconda2/envs/env/lib/python2.7/site-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file '/host/user/dir/files/.file.xtc_offsets.npz' as a pickle
```

This shouldn't cause the entire file loading process to fail.  It should be possible wrap offset loading in a try/except to regenerate the offsets if needed

### PR DESCRIPTION
**Pull request by mlnance**
Fixes #1893 

Changes made in this Pull Request:
 - Wrapped `read_numpy_offsets` in a try/except that allows for handling `IOError`
 - Added a check for if read-in failed and to `_read_offsets` instead
 - Provided user with warning if file read-in failed and defaulting to reading from trajectory
 - Added necessary tests to `test_xdr.py`
   - Add assertion to all tests that call `read_numpy_offsets` that return value is a `dict`
   - Test that an `IOError` returns `False` for `read_numpy_offsets`
   - Test that even with `IOError`, `_load_offsets` still returns expected value

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by mlnance** [comment]
@orbeckst thanks for the info on forking

This addition needs a test (and code review to ensure I added this feature properly, of course). Can anyone provide me with a relevant test file? Tagging @richardjgowers as you authored this issue originally

**Comment by mlnance** [comment]
@richardjgowers thanks for the info on forking

This addition needs a test (and code review to ensure I added this feature properly, of course). Can anyone provide me with a relevant test file?

**Comment by richardjgowers** [comment]
I think there’s two options;

You could create a bad file for a given trr file, where a bad file would be
something that np.load fails on, such as  txt file saying “hello”. Maybe a
clean way to do this is in a fixture that copies the trr to a tmp directory
then writes the silly bad file.

Or you could use mock to make np.load raise an IOError to spoof the failure
we’re hoping to observe. This is maybe a more “pure” way of doing it.

**Comment by mlnance** [comment]
Sigh, accidentally closed...

**Comment by mlnance** [comment]
@richardjgowers I believe I understand the mock procedure in theory (I've been googling and looking at how MDAnalysis uses mock to see if I can replicate it, I hadn't heard of `mock` until you mentioned it). My assumption is that I would pass a mocked path of some sort (off an offsets filename that does exist) to `_load_offsets` so that `read_numpy_offsets` can be called but will given `IOError`. I just have yet to figure out how to implement that. I'll keep researching, but if you have an any examples of where something like this has been done before in MDAnalysis testing, I'd appreciate it

**Comment by fiona-naughton** [comment]
@mlnance the idea would be to create a mock of `np.load` that raises `IOError` rather than actually loading anything, and then run `_load_offsets`. Something like https://github.com/MDAnalysis/mdanalysis/blob/e416aa7d9adb9a9c14adb0774e65162da89a0d1c/testsuite/MDAnalysisTests/analysis/test_waterdynamics.py#L89-L95 with `np.load` instead of `universe.select_atoms` and setting `side_effect` to `IOError`.

**Comment by mlnance** [comment]
@fiona-naughton thank you for the info, that was really helpful. The `mock` module is really cool, I'm glad I know about it now. I think I got the necessary tests going for what I have added. Tagging @richardjgowers

**Comment by mlnance** [comment]
I'm not sure if this PR requires an update in documentation (I'm thinking not), but I know I do need to update the CHANGELOG

**Comment by richardjgowers** [comment]
@mlnance this looks good.  Few things

- add a quick note to CHANGELOG (this is user facing, so briefly explain what you've fixed for them)
- add your github handle to CHANGELOG for 0.21
- add a quick note in the class with the change under a `.. versionchaged::` note
- add yourself to AUTHORS

**Comment by mlnance** [comment]
> just needs documenting

@richardjgowers addressed, let me know if there is anything else

**Comment by mlnance** [comment]
Thanks @richardjgowers @orbeckst @fiona-naughton for all the help/input/merging

I was wondering how I should interpret the change in the Codecov Report? Previously it said that my changes would change coverage by 0%, but after the branch-merge it is showing red for a decrease of 0.1%. However, only comments had been changed in both my last commit and the branch-merge. What exactly is the Codecov checking in this case?

**Comment by orbeckst** [comment]
Codecov is not always super-reliable and fluctuates. We ignore these small changes.

**Comment by orbeckst** [comment]
@richardjgowers will have a final look & squash-merge. Thank you @mlnance !

**Comment by mlnance** [comment]
@orbeckst thanks again! this has been a fun process so far

**Comment by richardjgowers** [comment]
Cool thanks for the fix @mlnance !

**Pull request merged**
