### PR TITLE
Reworked coordinates.base.Timestep construction

### PR DESCRIPTION
**Pull request by richardjgowers**
Got rid of the old 3 way split inside Timestep construction.  Now Timesteps are only initiated via numatoms.

Added ability to have velocities and forces to base.Timestep, making many other subclasses massively simpler. (I'm quite happy with how TRJ.Timestep looks now)

Timestep.velocities and Timestep.forces will now either return data or raise a NoDataError

Every Timestep now uses (sometimes via super) `base.Timestep.__init__` which should make updating the API for Timestep much easier #250 for @dotsdl 

TRR.Timestep has been tidied up a lot, but I think I need to add a few more tests to make sure that they're behaving exactly as we want them to.

Everything is currently passing, so I think it's ready for a review at least

### CODE REVIEW

**Comment by orbeckst** [comment]
Will look at it next week... but if anyone else wants to ok it, it's fine with me.

**Comment by orbeckst** [comment]
Summary @richardjgowers : looking very good, nice cleanup and better structure. Main things that I saw are simply documentation.

Glad that we have the unit tests + travis, otherwise this would be a nightmare....

**Comment by richardjgowers** [comment]
Hi Oliver, thanks for the review

Yeah doing this without tests would have been interesting to say the least.......

I'll finish docs and merge

**Comment by orbeckst** [comment]
Ok, just merge yourself once the docs are done.

**Pull request merged**
