### PR TITLE
MAINT: use github labeler

### PR DESCRIPTION
**Pull request by tylerjereddy**
* for simple PR labels, leverage the GitHub Actions bot
to apply labels based on filepaths that are adjusted

* docs are here:
https://github.com/marketplace/actions/labeler

* based on example upstream:
https://github.com/scipy/scipy/pull/14677

* this is only leveraging a small subset of our
labels to begin with; can be built up later to do
more if desired

Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Review by IAlibay — APPROVED** [review]
That's really cool!

Can we add maybe entries for coordinates & converters now so we don't have to add them later?

**Comment by tylerjereddy** [comment]
I added in auto-labels for `Component-Topology` and `Component-Converters`. I wasn't quite sure what to label for "coordinates" so I didn't touch that.

**Comment by IAlibay** [comment]
> I added in auto-labels for `Component-Topology` and `Component-Converters`. I wasn't quite sure what to label for "coordinates" so I didn't touch that.

How about Component-Readers?

**Comment by tylerjereddy** [comment]
> How about Component-Readers?

Ok, I've added in an auto-label for `Component-Readers` for `coordinates`, though I note that a change there could apply just as well to `Component-Writers` I think (I was trying to avoiding paths/categories where a human could label best).

**Comment by IAlibay** [comment]
> > How about Component-Readers?
> 
> Ok, I've added in an auto-label for `Component-Readers` for `coordinates`, though I note that a change there could apply just as well to `Component-Writers` I think (I was trying to avoiding paths/categories where a human could label best).

We probably should just add a new label that does both... well for now let's go for this and see if anyone minds (generally folks that will want to look at file I/O PRs don't really mind if it's reader or writer related).

**Comment by IAlibay** [comment]
Sorry @tylerjereddy completely forgot to ask you to add yourself to the changelog list for 2.1.0. I'll add you in an upcoming PR.

**Comment by tylerjereddy** [comment]
If the bot starts removing human-placed labels we can try turning `sync-labels` off (this happened upstream I think, but maybe I've been sufficiently conservative with the automation, not sure).

**Pull request merged**
