### PR TITLE
Implement ReadTheDocs theme

### LINKED ISSUE #2397: change style of docs to UserGuide style
**Is your feature request related to a problem? Please describe.**
The generated sphinx docs https://www.mdanalysis.org/docs/ are based on the alabaster style with modifications but the overall look&feel of the website is different. The styles should match better.

**Describe the solution you'd like**
@lilyminium solved this problem with the style of the UserGuide https://www.mdanalysis.org/UserGuide/ . We should use her style for the docs for a more uniform look & feel.

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #2397 

Changes made in this Pull Request:
 - switched theme to user guide theme (not MDAnalysis.org colours)

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by lilyminium** [comment]
After the second commit.

## Homepage

Screenshot 2019-11-11 at 2 21 57 PM

## Class API

Screenshot 2019-11-11 at 2 43 29 PM

Some changes to docs need to be made to display properly. e.g. here is PDBReader in ReadTheDocs:
Screenshot 2019-11-11 at 2 33 07 PM

The grey boxes are `..versionchanged`` directives. They're not displaying properly because RTD/Sphinx thinks they're in the See Also box. (This didn't display properly in alabaster either).

Screenshot 2019-11-11 at 2 34 33 PM

Other than the layout, I haven't changed the default colours of RTD. Class boxes are blue, parameters etc. are grey. 

Screenshot 2019-11-11 at 2 39 58 PM

Returns and Return type are separate, a bit weird.

Screenshot 2019-11-11 at 2 39 40 PM

## Sidebar

Screenshot 2019-11-11 at 2 59 59 PM

The orange links do not look good on lighter colours. Solutions: don't highlight them orange, or have different oranges for each background.

## Warning/important/caution boxes etc

These have been left as default colours. 

Screenshot 2019-11-11 at 3 02 29 PM

**Comment by zemanj** [comment]
IMHO this already looks much nicer than what we currently have!

> The orange links do not look good on lighter colours. Solutions: don't highlight them orange, or have different oranges for each background.

I don't have any readability issues on any of my displays.

> The grey boxes are `..versionchanged`` directives. They're not displaying properly because RTD/Sphinx thinks they're in the See Also box. (This didn't display properly in alabaster either).

This is because for some (unknown?) reason, the `.. versionadded::` or `.. versionchanged::` directives require **two** preceding blank lines. There are (many?) similar cases, e.g. [`lib.self_capped_distance()`](https://www.mdanalysis.org/docs/documentation_pages/lib/distances.html#MDAnalysis.lib.distances.self_capped_distance).

> Returns and Return type are separate, a bit weird.

A matter of taste, I'd say... would be nicer though if this conformed to the way input parameters are listed.

**Comment by lilyminium** [comment]
> I don't have any readability issues on any of my displays.

I did have a massive headache when building it, but the contrast is still a bit low with bright orange on a  coloured background. 

> This is because for some (unknown?) reason, the .. versionadded:: or .. versionchanged:: directives require two preceding blank lines. There are (many?) similar cases, e.g.

I think that's only when the boxes are defined with underlines instead of the `..` syntax. The GROReader `.. version changed` shows up fine when the note box is defined with `.. note::`

Screenshot 2019-11-11 at 9 23 26 PM

https://github.com/MDAnalysis/mdanalysis/blob/e1101089ffc7aa58be654f7d0a82840a9d5a7175/package/MDAnalysis/coordinates/GRO.py#L167-L175

**Comment by lilyminium** [comment]
More on GROWriter -- this shows up... poorly... (using `#:` for docstrings is neat)

https://github.com/MDAnalysis/mdanalysis/blob/e1101089ffc7aa58be654f7d0a82840a9d5a7175/package/MDAnalysis/coordinates/GRO.py#L292-L302

## ReadTheDocs
Screenshot 2019-11-11 at 9 29 05 PM

## Alabaster
Screenshot 2019-11-11 at 9 29 21 PM

**Comment by zemanj** [comment]
> More on GROWriter -- this shows up... poorly... (using #: for docstrings is neat)

I somehow doubt that this should show up in the docs... I'd definitely prefer a link to the GROMACS gro specs here.
Anyway, good to know that Sphinx interprets `#:` like that!

**Comment by orbeckst** [comment]
> Anyway, good to know that Sphinx interprets #: like that!

We have been using `#:` throughout to document attributes and module-level data, e.g. https://www.mdanalysis.org/docs/documentation_pages/units.html#data

I don't mind constant values showing up in the developer docs; I think the link to the GRO format is elsewhere (but could be repeated there).

**Comment by orbeckst** [comment]
The `.. versionchanged` (and any standard reST/sphinx directives) needing two lines when following numpy markup is a "known" issue, see https://github.com/MDAnalysis/mdanalysis/wiki/WritingDocumentation#numpy-style-gotchas

**Comment by orbeckst** [comment]
>>    Returns and Return type are separate, a bit weird.
> A matter of taste, I'd say... would be nicer though if this conformed to the way input parameters are listed.

Yes, but that's been like this before so I wouldn't say that this has to be changed in this PR – a nice-to-have for the future.

**Comment by orbeckst** [comment]
> Class boxes are blue, parameters etc. are grey.

Can we make the class boxes one of the standard MDA colors (orange, dark gray, black) ? – The blue does not look good in the page. Changing the blue in the class (and function?) headers to something in the scheme is my main critique – everything else is "nice to have".

I'd also prefer a different color for the Notes boxes but the blue does highlight them. (Not a big fan of the green for Hint/Important either – but I think we barely use them anyway.)

@lilyminium if you want to extend the color palette then please go for it!

**Comment by zemanj** [comment]
Sure, having hard-coded constants is certainly beneficial. The formatting just happens to look ugly as sin :wink:

**Comment by lilyminium** [comment]
Just removing the sphinx `#:` will keep `fmt` from appearing in the docs. It could be manually documented. 

Orange class boxes + (default) blue note box:
Screenshot 2019-11-12 at 11 13 29 AM


Other possible colours:

Screenshot 2019-11-12 at 11 43 23 AM

**Comment by zemanj** [comment]
> Just removing the sphinx #: will keep fmt from appearing in the docs. It could be manually documented.

I think it's more practical to keep the `#:` syntax since that references the *actual* code. This guarantees that changes cannot go undocumented.

Maybe we can do something about the unappealing formatting later.

**Comment by lilyminium** [comment]
I built this PR at [https://lilyminium.github.io/mdanalysis/](https://lilyminium.github.io/mdanalysis/) for more convenient viewing.

**Comment by orbeckst** [comment]
Great, thank you so much!

**Comment by orbeckst** [comment]
When you have settled on the color scheme (and any other identity/branding choices that you make), could you please document it (e.g., wiki page and in the conf file) so that it is easy to use it elsewhere (namely, the home page)?

**Comment by orbeckst** [comment]
The definition list in https://lilyminium.github.io/mdanalysis/documentation_pages/selections.html#simple-selections contains baby-blue highlights – I'd use the same orange as for class definitions.

**Comment by lilyminium** [comment]
> picking two complementary colors to the primary or dominant color (orange for MDA) is what is often done for website themes. (I just don't feel it looks good here.)

Fair enough, the variety of boxes seemed to warrant lots of colours but it looks like you mostly use Notes and See Also.

> See Also (eg https://lilyminium.github.io/mdanalysis/documentation_pages/analysis/align.html)
definition lists (eg https://lilyminium.github.io/mdanalysis/documentation_pages/selections.html#simple-selections)

See Also, Caution, and Important have been changed to yellow.

> functions (eg https://lilyminium.github.io/mdanalysis/documentation_pages/selections_modules.html#MDAnalysis.selections.get_writer)

Functions are orange to match classes

> GUI elements (e.g. "Selections:Singlewords" in https://lilyminium.github.io/mdanalysis/documentation_pages/selections/vmd.html)

These are now grey

> Notes (eg https://lilyminium.github.io/mdanalysis/documentation_pages/auxiliary/XVG.html) – compare to the simple gray boxes in https://www.mdanalysis.org/mdanalysis/documentation_pages/auxiliary/XVG.html

These are also grey. Warnings/errors are still red.

> The definition list in https://lilyminium.github.io/mdanalysis/documentation_pages/selections.html#simple-selections contains baby-blue highlights – I'd use the same orange as for class definitions.

I actually took the colours away here and made them bold.

**Comment by lilyminium** [comment]
Orange might actually look nicer (the original RTD theme had note boxes and class boxes the same as well, I think). Thoughts?

Screenshot 2019-11-14 at 2 45 15 PM

Screenshot 2019-11-14 at 2 44 38 PM

**Comment by zemanj** [comment]
> Orange might actually look nicer

I second that.

**Comment by orbeckst** [comment]
Ok

**Comment by orbeckst** [comment]
Very nice work @lilyminium – any last minute changes that you want to get in? Otherwise this can be merged anytime.

**Comment by orbeckst** [comment]
Btw, are you going to back-port the color changes (e.g. notes) to the UserGuide style, too?

**Comment by lilyminium** [comment]
@orbeckst I will update the UserGuide to this, yes. No last minute changes I can think of!

**Comment by orbeckst** [comment]
See https://www.mdanalysis.org/mdanalysis/ !

**Pull request merged**
