### PR TITLE
replaced atoms.coordinates() with atoms.positions (Issue #3467)

### LINKED ISSUE #3467: replace atoms.coordinates() with atoms.positions
Since 2.0, atoms does not have coordinates() anymore and only positions is supported.

- [ ] Needs to be fixed:
https://github.com/MDAnalysis/mdanalysis/blob/46c8badd8b8967dc25f8125ef87582490ab497e3/package/MDAnalysis/analysis/encore/covariance.py#L218
- [ ] Also, fix benchmarks that still use coordinates() (but this could be made another PR)

### PR DESCRIPTION
**Pull request by pranjii**
Fixes #3467 

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
* Please change: .positions is an attibute not a method.
* Please remove the changes regarding units. We want to do 1 PR addressing 1 issue to keep things simple.

I approved running the tests – sorry, that's a current security measure. Please feel free to ping me @orbeckst if something is not moving along.

**Comment by pranjii** [comment]
> * Please change: .positions is an attibute not a method.
> 
>     * Please remove the changes regarding units. We want to do 1 PR addressing 1 issue to keep things simple.
> 
> 
> I approved running the tests – sorry, that's a current security measure. Please feel free to ping me @orbeckst if something is not moving along.

ohh sorry I am still new to github and python. I messed it up.

**Comment by pranjii** [comment]
@orbeckst I mailed you my issue. It'd be great if you could help me out

**Comment by lilyminium** [comment]
@pranjii it's usually easier, faster and helps later viewers if you discuss problems here on the issue -- then all developers can pitch in and help.

**Comment by pranjii** [comment]
> @pranjii it's usually easier, faster and helps later viewers if you discuss problems here on the issue -- then all developers can pitch in and help.

As I said I am new to github so I do not know the norms and I apologise for the troubles. I was not aware of how github worked and made changes to the already committed code unaware that any changes I made to my branch will also be made in the PR. So how do I reverse these changes keeping in mind that I made a small change in the code directly through github? Should I just close my pull request?

**Comment by orbeckst** [comment]
Hi @pranjii , don't worry – you're fine!!

There was no need to delete anything. I would have asked you to 

* fix your code in your branch & push
* continue working on _this_ PR

It's totally normal that you will change and rewrite the code in the PR in response to comments. It's actually **really good** to see your code so that we can comment early.

In short: you did everything correctly!

**Comment by pranjii** [comment]
@orbeckst thank u. I have closed this PR and will change the recommend things ASAP for a new PR and guess will dive a little bit deeper into git and github

**Comment by orbeckst** [comment]
Sure. Don't worry, learning the whole pull request/review workflow takes some time. Ask us before you delete anything, we can typically give guidance. Just be aware that we might not always be able to immediately respond — we are all pretty busy an it can sometimes take a day. As @lilyminium said, we discuss all issues in public. We also follow our [Code of Conduct](https://www.mdanalysis.org/pages/conduct/) in conducting all these discussions respectfully.

**Pull request closed without merging**
