### PR TITLE
[TEST] Conda package

### PR DESCRIPTION
**Pull request by kain88-de**
This is only a test because I'm seeing strange errors in my local conda builds. I want to find out if they are reproducible on other machines.

### CODE REVIEW

**Comment by kain88-de** [comment]
OK I get reproducible the same failure on several different machines. See https://travis-ci.org/MDAnalysis/mdanalysis/jobs/216307955#L3874

The problem here is that the whole python process just stops. i don't really know what is going on or how to start debugging that.

The tests fail at [this line](https://github.com/MDAnalysis/mdanalysis/blob/90dbc149e842fb4af528b0df0526d7300aa5e5f6/testsuite/MDAnalysisTests/core/test_topologyattrs.py#L257)

**Comment by kain88-de** [comment]
OK I found the error. Our open files plugin caused the crash. Deactivating it gives us a successful build

**Comment by jbarnoud** [comment]
The open-files plugin has a bug, it either breaks the output of the plugin that captures stderr or causes a unicode error. I deactivated it in travis until I find a solution or it becomes obsolete under pytest.

**Comment by kain88-de** [comment]
Thanks for the info. Btw for some reason building a conda package with all dependencies and test only takes 20 minutes. Much faster then our normal CI build.

**Pull request closed without merging**
