### PR TITLE
Fixed the parsing of tpr files created by the 2021 version of gromacs (Issue #3810)

### LINKED ISSUE #3180: TPRParser does not support TPX version 122 from Gromacs 2021
Hi everyone,

TPR files generated by Gromacs 2021 don't work with MDAnalysis. I tried just bumping the supported version numbers, but that didn't work either.

If I can be of any help, let me know.

## Expected behavior ##

The TPR parser reads topologies from TPR file produced by Gromacs 2021

## Actual behavior ##

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henrik/.local/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 372, in __init__
    topology = _topology_from_file_like(self.filename,
  File "/home/henrik/.local/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 141, in _topology_from_file_like
    raise ValueError(
ValueError: Failed to construct topology from file tpi_run.tpr with parser <class 'MDAnalysis.topology.TPRParser.TPRParser'>.
Error: Your tpx version is 122, which this parser does not support, yet 
```

With bumping the supported versions to 122:

```
>>> import MDAnalysis as mda
>>> mda.Universe('tpi_run.tpr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/mdanalysis/package/MDAnalysis/core/universe.py", line 334, in __init__
    topology = _topology_from_file_like(self.filename,
  File "/tmp/mdanalysis/package/MDAnalysis/core/universe.py", line 120, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "/tmp/mdanalysis/package/MDAnalysis/topology/TPRParser.py", line 237, in parse
    tpr_top = tpr_utils.do_mtop(data, th.fver,
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 297, in do_mtop
    moltype = do_moltype(data, symtab, fver)
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 692, in do_moltype
    atoms_obj = do_atoms(data, symtab, fver)
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 785, in do_atoms
    atomnames = [symtab[i] for i in ndo_int(data, nr)]
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 785, in <listcomp>
    atomnames = [symtab[i] for i in ndo_int(data, nr)]
IndexError: list index out of range
``` 

## Code to reproduce the behavior ##

```python
>>> import MDAnalysis as mda
>>> mda.Universe('tpi_run.tpr')
```

## Current version of MDAnalysis ##

```bash
$ python3 -c "import MDAnalysis as mda; print(mda.__version__)"
1.0.1
$ python3 -V
Python 3.8.5
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

### PR DESCRIPTION
**Pull request by hejamu**
Fixes #3180 

Changes made in this Pull Request:

 - Added the virtual_site1 definition to the TPRParser.

- Some tests for gromacs-2021 tpr files added. (`all_bonded` and `virtual_sites`. I don't know how the `2lyz_gmx_<version>.tpr` files were created, so I couldn't create those tests)

- Changelog appended.

- tpx version 122/gen 28 added to docs. 

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by richardjgowers** [comment]
Hi @hejamu thanks for this, we'll review it soon.  Can you add yourself to package/AUTHORS too please?

**Comment by acmnpv** [comment]
Hello, just one mention from the GROMACS side. 

The change that broke things here changed some internals in `tpx_generation` as well as `tpx_version` (change was 9ecf9141da64954e5288bb4e7b2332569f364b65 in the GROMACS repository).
I don't know how this will affect MDAnalysis, but the passing tests seem to indicate it is not an issue.

**Comment by jbarnoud** [comment]
Good work with this PR! Thank you 🎉

The PR addresses the changes I identified when looking at the issue. Just 2 things:
* did you change the tip in `all_bonded` and `virtual_sites` compared to the tips for the previous versions of gromacs? If not, then it is simpler to not duplicate them.
* The 2lyz tpr files are converted generation after generation using `gmx convert-tpr`. Could you have a go? I got a segmentation fault when I did try, but it may only be due to my gromacs installation.

**Comment by hejamu** [comment]
@jbarnoud 

The `virtual_sites` version of `dummy_2021.top` includes the `[ virtual_sites1 ]` option,

```
$ diff dummy_2021.top dummy.top 
98c98
< 13      TA      1       T       T13     1       0         
---
> 13      TA      1       T       T13     1       0
103d102
< 18	TA	1	T	T18	1	0	  0
120,123d118
< [ virtual_sites1 ]
< ; Site  from        funct
< 18       1           1
< 
```

and I guessed it is nice to see how the tpr file was created.

The 'all_bonded` version of `dummy_2021.top` is identical to `dummy.top` so I can remove it.

Funny thing: I also get a segmentation fault, but extending the runtime by zero ps, it runs fine

```
$ /usr/local/gromacs/bin/gmx convert-tpr -s 2lyz_gmx_2020.tpr -o 2lyz_gmx_2021.tpr 
                   :-) GROMACS - gmx convert-tpr, 2021.1 (-:

                            (COPYRIGHT TEXT)

GROMACS:      gmx convert-tpr, version 2021.1
Executable:   /usr/local/gromacs/bin/gmx
Data prefix:  /usr/local/gromacs
Working dir:  *******/testsuite/MDAnalysisTests/data/tprs
Command line:
  gmx convert-tpr -s 2lyz_gmx_2020.tpr -o 2lyz_gmx_2021.tpr

Reading toplogy and stuff from 2lyz_gmx_2020.tpr
Reading file 2lyz_gmx_2020.tpr, VERSION 2020 (single precision)
Note: file tpx version 119, software tpx version 122
100000000 steps (200000 ps) remaining from first run.
zsh: segmentation fault  /usr/local/gromacs/bin/gmx convert-tpr -s 2lyz_gmx_2020.tpr -o 
$ /usr/local/gromacs/bin/gmx convert-tpr -s 2lyz_gmx_2020.tpr -o 2lyz_gmx_2021.tpr -extend 0
                   :-) GROMACS - gmx convert-tpr, 2021.1 (-:

                            (COPYRIGHT TEXT)

GROMACS:      gmx convert-tpr, version 2021.1
Executable:   /usr/local/gromacs/bin/gmx
Data prefix:  /usr/local/gromacs
Working dir:  ******/testsuite/MDAnalysisTests/data/tprs
Command line:
  gmx convert-tpr -s 2lyz_gmx_2020.tpr -o 2lyz_gmx_2021.tpr -extend 0

Reading toplogy and stuff from 2lyz_gmx_2020.tpr
Reading file 2lyz_gmx_2020.tpr, VERSION 2020 (single precision)
Note: file tpx version 119, software tpx version 122
Extending remaining runtime of by 0 ps (now 100000000 steps)
Writing statusfile with starting step          0 and length  100000000 steps...
                                 time      0.000 and length 200000.000 ps
```

**Comment by jbarnoud** [comment]
Great!

> The 'all_bondedversion ofdummy_2021.topis identical todummy.top` so I can remove it.

Yes please. I usually create a new ITP only when there is something new. It makes it easier to follow the differences.

> Funny thing: I also get a segmentation fault, but extending the runtime by zero ps, it runs fine

That is odd... Could you add the tests with 2lyz, then?

**Comment by hejamu** [comment]
Ok, should all be done now :)

**Review by jbarnoud — APPROVED** [review]
I am just waiting for the CI to pass. Thank you again for your contribution!

**Pull request merged**
