### PR TITLE
prelimary support for cclib supported format

### PR DESCRIPTION
**Pull request by richardjgowers**
So this is a rough draft currently, but this would add support for formats supported by [cclib](https://github.com/cclib/cclib).  In terms of licensing, cclib is BSD, so we can wrap it like this afaik?

There's a lot of new formats here:
http://cclib.github.io/#summary

I need to go through and check what we can easily add to the Topology, then more complicated data (orbital info etc) might require more thought on how to add it to a Universe.

Thoughts?

### CODE REVIEW

**Comment by orbeckst** [comment]
Interesting idea, and would expand our range to comp chem.

**Comment by richardjgowers** [comment]
Ok I've had to add two dependencies for this to work, cclib which is a library we're using to parse the formats involved and periodictable which is just tables of data (here I'm using it for atomic number to symbol), but it'd be useful elsewhere too.

@kain88-de in terms of conda packaging, is it enough to add the dependencies in setup.py if they are available on pypi?

**Comment by kain88-de** [comment]
@richardjgowers nope. We need to package it for conda-forge. This means a package for cclib and it's dependencies (openbabel, pyopenbabel and PyQuante)

**Comment by kain88-de** [comment]
and the dependencies are a bit trouble some. They aren't normal python packages.

**Comment by richardjgowers** [comment]
Yeah, I was just thinking that's going to be an annoying job to package up

**Comment by kain88-de** [comment]
Well I'm starting with PyQuante and then we see further.

**Comment by richardjgowers** [comment]
@kain88-de if it gets annoying then don't go too far.  All I'm using is the ascii parsing stuff from cclib, so it might be less effort to absorb/reimplement that code than package a bunch of weird extensiony stuff

**Comment by kain88-de** [comment]
Well it shouldn't be *too hard*. for PyQuante I specifically have to figure out the url on SourceForge and check if the package is python only. I haven't checked much for the sources of openbabel yet, but they do have some conda recipes I think I can copy.
https://github.com/openbabel/conda-openbabel

**Comment by kain88-de** [comment]
OK so PyQuante is not needed by cclib just a nice extra. The openbabel conda recipe I found doesn't work out of box and the conda error isn't a huge help. Maybe you can ask the cclib people if they can make a conda forge package them selves.

**Comment by jaimergp** [comment]
I have used `cclib` in several projects, and if I recall correctly, `openbabel` is also optional (mainly for output support, not input). Most of the parsers simply rely on `numpy` for numeric storage.

**Comment by richardjgowers** [comment]
@jaimergp hmm yeah my memory was most the parsing is pure Python too.  Maybe we can make openbabel optional in the conda packaging of it, so we can make cclib a dependency.

**Comment by jaimergp** [comment]
Would you like some help with this? I saw you already asked the `cclib` team and they basically granted approval for this to be handled externally (https://github.com/cclib/cclib/issues/493).

**Comment by richardjgowers** [comment]
@jaimergp yeah that'd be great, I think we just need to get the conda-forge packaging for the cclib stack up and running, then I can quickly rebase this branch. Feel free to give me a ping if you get stuck

**Comment by jaimergp** [comment]
@richardjgowers Perfect, I will start by creating the PR at https://github.com/conda-forge/staged-recipes and report back once that's done.

**Comment by jaimergp** [comment]
Working on https://github.com/conda-forge/staged-recipes/pull/7114.

Linux / OSX are OK, but some errors are arising in the Windows build (commands testing). I haven't been able to reproduce them, so maybe it was an issue with the CI service. Rerunning just in case.

**Comment by jaimergp** [comment]
Update: all tests are passing. It should be enough for have it merged. Now it is just a matter of time, I guess.

**Comment by orbeckst** [comment]
Given our recent focus on interoperability https://www.mdanalysis.org/2020/08/03/roadmap/ I will _not_ close the PR but remove the _close?_ label. @richardjgowers if you think one would better start anew than form this PR then close the PR yourself, please.

**Comment by hmacdope** [comment]
@richardjgowers @IAlibay @orbeckst I am just going to close (its been 2 years since last activity)

**Pull request closed without merging**
