### PR TITLE
additional PSA tests

### PR DESCRIPTION
**Pull request by orbeckst**
Changes made in this Pull Request:
- test functions that require seaborn (skip if cannot be imported)
- updated warning for plot_nearest_neighbors() to use run_pairs_analysis(neighbors=True)

PR Checklist
------------
 - [x] Tests?
 - n/a Docs?
 - n/a CHANGELOG updated?
 - n/a Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
I am confused: why does `testsuite/MDAnalysisTests/utils/test_authors.py` [FAIL on Travis CI](https://travis-ci.com/MDAnalysis/mdanalysis/jobs/139235906#L3761) (for all jobs) but passes on AppVeyor (and locally)??

Help.... @richardjgowers @jbarnoud @tylerjereddy

**Comment by tylerjereddy** [comment]
For me that failure occurs almost exclusively because I haven't recently installed the testsuite with its own `python setup.py` command. The appveyor config clearly does both--builds the package & the testsuite;  perhaps some components of the travis matrix only build the package and not the test source files?

**Comment by tylerjereddy** [comment]
The `pip install testsuite` used in travis is something I never do -- if I had to bet that might be a suitable target.

**Comment by jbarnoud** [comment]
I restored `testsuite/__init__.py` in my fork and it fixed the issue. I did not look yet at why, though.

**Comment by orbeckst** [comment]
Many thanks for your comments.

> I restored testsuite/__init__.py in my fork and it fixed the issue. I did not look yet at why, though.

Ok, I'll revert 7361a02 so that this can move along (and won't suddenly break). But this looks extremely dodgy to me and I'll raise a separate issue.

**Comment by orbeckst** [comment]
oooh, too fast... I was about to add more tests.

**Comment by orbeckst** [comment]
Sorry, should have communicated better.

**Comment by orbeckst** [comment]
Will create new PR.

**Comment by orbeckst** [comment]
Btw, it is really tedious to increase our coverage... just +0.3%?

**Comment by richardjgowers** [comment]
Ah sorry I’m trying to get stuff merged before it needs a rebase. Also
+0.3% is more like 3% of the remaining coverage to do if you want to think
of it that way.

**Pull request merged**
