### PR TITLE
Move darker information to a PR comment instead

### PR DESCRIPTION
**Pull request by IAlibay**
Hopefully this will at least temporarily clarify the way darker works and should prevent further misunderstandings.

## Changes made in this Pull Request:
 - Darker lint now always returns green.
 - Instead we use the github api (partly PyGithub, partly RESTful), so extract & post the outcomes as a comment.

## Unknowns
  - Right now I have no idea how well this will survive in the wild. It might need tweaking in a further iteration.
  - One of the things that I _think_ might be problematic is when branches come from forks. The best I can do for this is open a separate PR once this is fixed and see if everything behaves as expected.

### CODE REVIEW

**Comment by IAlibay** [comment]
test

**Comment by IAlibay** [comment]
Current issues:
- [x] Comments are not being overwritten
- [x] Because of continue-on-fail, either one thing passes or all things fail...

**Comment by IAlibay** [comment]
What happens if I double up on comments with the words "Linter Bot Results:"?

**Comment by IAlibay** [comment]
Ok this should be good to review.

See the last two entries of history of this comment for how things will be updated when there is & isn't a failure: https://github.com/MDAnalysis/mdanalysis/pull/4067#issuecomment-1469802613

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
