### PR TITLE
Run GH Actions CI for py3.6+ and keep Travis for 3.5 and 2.7

### LINKED ISSUE #2768: Release 1.0.1
A few things are accumulating for a patch-level release for 1.0, related to

- installation
- performance regressions

The point is to make 1.0.x a stable platform for anyone who needs legacy MDAnalysis for the foreseeable feature. 1.0.x should not be worse than 0.20.1.

### LINKED ISSUE #3079: Travis py2.7 stalls on install
## Expected behavior ##

Python 2.7 runs on Travis

## Actual behavior ##

It stalls on:

- https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/460433388 (cron job)
- https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/460701640
- https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/459914026

as opposed to:

- https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/456392749 a week ago
- https://travis-ci.com/github/MDAnalysis/mdanalysis/jobs/456037505 a week ago

all in the first 12 minutes where it's installing packages.

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- Which version of Python (`python -V`)?
- Which operating system?

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #3079 
Branches off #3061 to fix #2768. As elegantly suggested by @IAlibay, this PR

* ports fixes from develop to master
* Keeps GH actions for pythons 3.6-3.8
* Keeps Travis for pythons 2.7 and 3.5

In #3061 I moved Python 2.7 and 3.5 CI to GH actions. It is a bit clunky, unreadable, and potentially difficult to maintain. Given that we can hopefully just move onto 2.0 and Python 3.6+, perhaps this compromise gets things done for an intermediate 1.0.1 release while we iron out the kinks on #3061.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Review by IAlibay — COMMENTED** [review]
Might just be me looking in the wrong place, but I can't seem to be able to see the py3.5 run?

**Comment by lilyminium** [comment]
@IAlibay I can't see a successful python 3.5 in https://travis-ci.com/github/MDAnalysis/mdanalysis/builds/192419679, on master a month ago?

**Comment by IAlibay** [comment]
@lilyminium could you also port #3073 here too? (i.e. just delete the appveyor yaml file). That would save us having to open a separate PR to deal with this.

**Review by IAlibay — APPROVED** [review]
lgtm! thanks :)

Unless there's any major objections to this pseudo-port approach (i.e. having a small reliance on Travis credits for a branch that we don't often push to), then let's go with this (pinging @MDAnalysis/coredevs).

**Comment by IAlibay** [comment]
@lilyminium this is probably good to merge. However, why is RTD failing?

**Comment by lilyminium** [comment]
Thanks for the review @IAlibay! RTD is failing because #3078 isn't merged, because of #3079...

**Pull request merged**
