### PR TITLE
Fixes for analysis.contacts.ContactAnalysis1

### PR DESCRIPTION
**Pull request by orbeckst**
This PR addresses remaining comments from PR #638.

Note that the tests *will fail* until #672 is resolved. Feel free to wait with merging until #672 is done.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Confusingly, if you restore the warnings import statement at line 618 you can't actually use the warnings statement on line 603 because it is an unbound local, even though warnings is still imported at the top-level of the module. Does anyone understand why this is the case?

Looks good, but the above issue is what was confusing me before with imports in this module. Sometimes import mechanics can be pretty tricky. I'm assuming this has something to do with local names and scoping.

**Comment by richardjgowers** [comment]
@tylerjereddy that sounds strange, I always thought the stuff up top was in the namespace of every method?

So now the bug is fixed I think the tests are failing now because the Timeseries that is made has no shape/size because no frames get iterated over (I think this is what is supposed to happen with [:0] though?).

**Comment by tylerjereddy** [comment]
@richardjgowers Yeah, I don't get it! But I think it is not just my imagination. The sensible solution (top-level import only) works, so that's what really matters--I'm just curious about what kind of morbid namespace thing is going on when you put the redundant conditional import and then cause a failure.

**Comment by orbeckst** [comment]
rebased against  develop and fixed the test for the stop=0 issue.

If it passes on travis then it should be good for merging.

**Pull request merged**
