### PR TITLE
Complete release v2.1.0

### LINKED ISSUE #3446: Release 2.1.0
With the release of python 3.10, we should make a minor release that covers python 3.7 before we have to consider ditching it.

It's shorter than our proposed "maximum every 6 months" release schedule, but it wouldn't help to get this out quickly so we can move up in minimum supported python versions.

That being said - I know we agreed that we would stick with NEP29, but maybe we should be a bit lenient and do a release that spans 4 python versions when faced with these types of cases. Otherwise we'll have an MDAnalysis version out there that's not been explicitly tested against py3.10.

Thoughts @MDAnalysis/coredevs ?

The next question is, what needs to be done before the 2.1.0 release? Please raise things in the comments and I'll make a list here.

Things urgently needed:
- [x] Fix docs build (#3438)
- XTC offset reading fix maybe? (#3375) -> being pushed to 2.2.0
- [x] #3440 
- [x] OpenMM import warning (it's actually a lot more annoying a warning than I'd thought)
- [x] PEP518 (#3398)
- [ ] RDKit things? (#3044 and #3470)

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #3446

Please do review but don't merge yet. This PR ties off version 2.1.0, but we want to make sure that testpypi looks fine.

@MDAnalysis/coredevs this means that we are completely commit frozen until after this PR is completed, tags are created and the PR starting 2.2.0-dev0 is merged. Should be ~ day or so.

Changes made in this Pull Request:
 - Ties off the changelog and version numbers of the 2.1.0 release.
 - Fixes userguide dev0 link in the docs.

PR Checklist
------------
 - Tests?
 - Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
Test versions of 2.1.0 are now on testpypi, if you have spare time please pip install them and run tests (particularly if you have a macOS machine since I can't test that).

Instructions are:
```bash
# install MDA 2.1.0
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple MDAnalysis

# install MDAtests 2.1.0
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple MDAnalysisTests

# Run tests
pytest --pyargs MDAnalysisTests 2>&1 | tee mda-test-release.logs
```

Please report any failures and relevant log bits as required.

**Comment by IAlibay** [comment]
Versions to check before we merge

- [x] Windows py3.7 - failures: known OSErrors with symlink creation in HOLE2
- [x] Windows py3.10 - failures: as above
- [x] Linux py3.7
- [x] Linux py3.10
- [x] Linux py3.9 all dependencies
- [x] MacOS py3.7
- [x] MacOS py3.10


extras:

- [x] MacOS 11.6 py3.9 
- [x] MacOS 12.2 py3.9

**Comment by hmacdope** [comment]
@IAlibay I can do py3.10 and py 3.17 MacOS if that would help?

**Comment by IAlibay** [comment]
> @IAlibay I can do py3.10 and py 3.17 MacOS if that would help?

please that would be useful

**Comment by hmacdope** [comment]
@IAlibay I assume you mean 3.7 for "3.17"?

EDIT:
3.10 is done, logs on discord.

EDIT:
3.7 is done logs on discord

**Comment by IAlibay** [comment]
Things to do:

- Need to check that the maintainer yaml files need updating
- Need to run that final "all deps" test

Then we should be good to go

**Comment by IAlibay** [comment]
Ok that _should_ be everything. @richardjgowers can you review as previous / maybe still current lord of the releases?

**Review by richardjgowers — APPROVED** [review]
@IAlibay lgtm.  The only thing I sometimes did for releases was regenerate all `.c` files from their `.pyx` equivalent, but now we're depending on Cython this isn't necessary.

**Comment by IAlibay** [comment]
> @IAlibay lgtm. The only thing I sometimes did for releases was regenerate all `.c` files from their `.pyx` equivalent, but now we're depending on Cython this isn't necessary.

So Cython isn't a core dependency as far as I'm aware, maybe we need to re-discuss this.

**Comment by IAlibay** [comment]
Ok so it turns out we probably want to keep the C/C++ files somewhere on github so we have a record of them somewhere.

Current plan is to do:
1. Merge the current PR
2. Create a release tag
3. Create a feature branch from this tag  (i.e. release-2.1.0)
4. In that branch call `python setup.py sdist`, commit the C/C++ files
5. Upload the sdist generated tarballs to pypi

Thoughts @MDAnalysis/coredevs ? (@jbarnoud probably had some views on this?)

In the future the aim would be to just make Cython a core dependency hopefully?

**Comment by jbarnoud** [comment]
It might be better to tag the commit that has the C files if it is the one from which the packages will be produced. But that is really nothing but a "might".

**Comment by orbeckst** [comment]
I thought @jbarnoud 's comment made sense: branch release-2.1.0, create everything that goes into the package, then tag the package stuff (and because the tag is associated with the release on GitHub, one can also download a tarball from GH that contains "everything").

**Comment by orbeckst** [comment]
Following up from discord: Having a tag on develop is really useful for benchmarking and other diff-based operations such as bisection. Perhaps we can instead
* introduce a new tag **package-2.1.0** that gets attached to the released files
* use the **release-2.1.0** tag as before on develop to mark the feature-complete release

(Or something along these lines — the main point is that we have the freedom to introduce different tags and that we can choose them as to disrupt procedures as little as possible.)

**Review by orbeckst — APPROVED** [review]
This is good to sit on develop with an appropriate tag to mark the 0.2.1-feature complete state.

See ongoing discussion on how to tag this merge commit.

**Pull request merged**
