### PR TITLE
Trying new nosetests

### PR DESCRIPTION
**Pull request by richardjgowers**
Attempt to implement the new and improved tests ( #340 ) into Travis

### CODE REVIEW

**Comment by mnmelo** [comment]
Just noticed while the CI tests run that we'll probably want the '-v' flag in there, to have the same output as before.

**Comment by mnmelo** [comment]
Yay, it passes!
Shall we flick the `--with-memleak` switch, along with `--processes=2` and `--process-timeout=120`?

**Comment by richardjgowers** [comment]
So it worked, but it didn't pick up the `.coveragerc` file, which is mainly used for excluding files from our coverage scope.

I've moved .coveragerc into the same directory as mda_nosetests to see if this fixes it..

I was going to turn on `--with-memleak` and then `--processes` in turn so we can see if either hit the performance of the test run.  (If we don't actually have a parallel environment then `processes` will likely kill performance)

**Comment by mnmelo** [comment]
Ok, let's get coverage right first.

One thing I'd like you to try is to test the memleak tester once we get `--with-memleak` on. I added three tests that should trigger a memleak at the bottom of `test_persistence.py` but left them commented out.

**Comment by mnmelo** [comment]
It still didn't pick it up `.coveragerc`, right?

I just updated the wiki on the UnitTests. If/when you get coverage going could you please update the instruction there on how to run coverage?

**Comment by richardjgowers** [comment]
Nope.  The problem I'm having is there isn't a command line argument for specifying where to look for a .coveragerc.. I think nose-cov might have solved this.

I'll do the expected fail run once coverage is working, and I'll do the wiki too.

**Comment by mnmelo** [comment]
Could it be related to the new default behavior of `mda_nosetests`? When no test is specified, the `MDAnalysisTests` suite is tested by default (instead of the current directory, as for `nosetests`).

**Comment by richardjgowers** [comment]
It's very strange.  It's not that the coveragerc is doing nothing, it's just that it's doing something different now.  With no coveragerc we get around ~51%, on this branch we can get ~64%, and before we were getting ~83%.  (Links to various coverage reports below)

Looking at the 64% build, it's considering the same number of files (83, so it's properly excluding analysis and vis), but the coverage across the board is a lot lower.

https://coveralls.io/github/MDAnalysis/mdanalysis

https://coveralls.io/builds/3014019

**Comment by richardjgowers** [comment]
So nose/coverage doesn't think that we used `coordinates.__init__` for example... which I'm fairly sure isn't correct.

https://coveralls.io/builds/3014019/source?filename=%2Fhome%2Ftravis%2Fminiconda%2Fenvs%2Fpyenv%2Flib%2Fpython2.7%2Fsite-packages%2FMDAnalysis%2Fcoordinates%2F__init__.py

So one solution would be to make the travis build have 2 jobs:
 - `mda_nosetests` with plugins and memleak etc (without coverage)
 - "normal" run which collects coverage

With both having to pass.

**Comment by mnmelo** [comment]
Indeed. I was comparing individual coverage reports before and after the changes. The new ones make no sense, with a `def function()` reported as missed, but the corresponding `return` reported as hit.
I'll also dig in.

**Comment by richardjgowers** [comment]
It might be that your teardown of everything hides what code was used from coverage? I'm not sure how coverage works exactly...  

I think I can get the 2 job solution working, so I think that might suffice for now.

**Comment by mnmelo** [comment]
Ha, got it!
(And I admit, I totally don't understand why)

I was calling `nose.main` from our test wrapper but `nose.run_exit` should be called instead. Why this makes a difference baffles me because in `/usr/local/lib/python2.7/dist-packages/nose/core.py` `run exit` is defined as follows:
```
run_exit = main = TestProgram
```
I'll push this to `feature-newtestrun`.

**Comment by richardjgowers** [comment]
Yep no problem, I've moved my build matrix idea to a different branch off this

**Comment by richardjgowers** [comment]
Ahh, you'll want to undo my most recent commit and force a push

**Comment by mnmelo** [comment]
I guessed as much. I'll do that.

**Comment by mnmelo** [comment]
And did `.coveragerc` really need moving after all? How many commits of yours shall I clobber?

**Comment by richardjgowers** [comment]
It didn't need moving I think..

**Comment by mnmelo** [comment]
So I'll roll back to 71409701b00ad8e53220e44e4ee7b10b49beffa6, then.

**Comment by richardjgowers** [comment]
Ok, so I've got this working as 2 jobs within the build.  This also fails when I uncomment the tests which should memleak.  I'm trying out parallelism now.

**Comment by richardjgowers** [comment]
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/70264645

So using `--processes=2` makes the `--mem-leak` option much faster, but the coverage build errored.

**Comment by mnmelo** [comment]
That actually seems to be an incompatibility between nose `mulltiprocess` and `coverage` plugins:
https://github.com/nose-devs/nose/pull/820
https://github.com/nose-devs/nose/pull/841

Apparently a fix has been provided. I'm guessing having a more recent nose might work (and indeed locally I can run parallel and with coverage with no problem).

On the still-failing coverage, I'll dig deeper. Again, the nose version might be in play, since I get higher (correct?) coverage locally, with nose 1.3.7.

**Comment by mnmelo** [comment]
Ok, I admit I just increased nose's version in `.travis.yml` without knowing whether that actually makes a difference. Anyone knows if there's a fixed nose version in travis?
Anyway, coverage is still underreported and mismatching what I get locally. Very weird...

**Comment by richardjgowers** [comment]
I don't think there's a real need to have the coverage run in parallel, as long as we're safe from the max travis job time (50 mins max, we're ~25 mins)

I've opened a new PR ( #343 ) which can replace this. It does everything (memleak + parallel, coverage) it just uses 2 jobs per build.

**Comment by mnmelo** [comment]
Finally!
All passes and covers properly. She's all yours for merging, @richardjgowers.

**Comment by orbeckst** [comment]
Great work, @mnmelo  and @richardjgowers !

**Pull request merged**
