### PR TITLE
updated replace atoms.coordinates() with atoms.positions #3467

### PR DESCRIPTION
**Pull request by manishsaini6421**
Fixes #

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
@manishsaini6421 under normal circumstances we want you to continue working on _one_ PR, namely on PR #3576 . Otherwise comments get lost. They way code review works is that you push work to your repository, it shows up in the PR, we comment, you read and address our comments, push more work, until the reviewers are happy.

Please 
- close this PR
- reopen PR #3576
- make all your changes in PR #3576

Thanks.

**Comment by manishsaini6421** [comment]
Sir, how to change in same PR?

**Comment by orbeckst** [comment]
Make change in your code, add a commit, push changes to your [shiny-new-feature](https://github.com/manishsaini6421/mdanalysis/tree/shiny-new-feature) branch. Because the PR is linked to the branch, the commit will show up in the PR.

**Comment by manishsaini6421** [comment]
@orbeckst Sir ,actually my first PR folder is deleted so please consider this one.

**Comment by hmacdope** [comment]
@manishsaini6421 we would like to close one of your PRs as duplicate PRs is discouraged as per @orbeckst comment. Which one would you like to continue in?

**Comment by hmacdope** [comment]
@manishsaini6421 we are going to close this PR and continue discussion in your previous PR, as we have already reviewed in that PR.

**Comment by orbeckst** [comment]
Now that _this_ PR has been closed and PR #3576 has been reopened, you should be able to continue working on your code as before. Just keep pushing commits and they should show up in PR #3576. 

Learning to work with git and GitHub takes some time. There is a lot of help available, e.g., https://docs.github.com/en/get-started#all-docs , but doing it in practice can still be daunting. One reason why we want GSOC applicants to submit code is so that they learn about the process as it is essential for being productive during GSOC.

**Comment by manishsaini6421** [comment]
@hmacdope Sir, please review this one because PR deleted by me from github due to lack of knoledge.
please sir reopen this one and close other one.

**Comment by hmacdope** [comment]
As stated above we will continue work in the old PR as it has a full record of our reviews and so on. Sorry about the inconvenience. :)

**Pull request closed without merging**
