### PR TITLE
[WIP] Playing around with 32 bits tests

### PR DESCRIPTION
**Pull request by jbarnoud**
Use a custom version of the ci-helper that installs 32 bits miniconda (hopefully).

See discussion in #1391

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by jbarnoud** [comment]
The approach looks like it could work. For the moment I have 2 problems that need fixing:
* I encounter a error with gcc:
```
In file included from /home/travis/miniconda/envs/test/include/python2.7/Python.h:58:0,
                     from MDAnalysis/coordinates/src/dcd.c:28:
    /home/travis/miniconda/envs/test/include/python2.7/pyport.h:895:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
```
* the onda package for mmtf-python only exists for 64bits

**Comment by kain88-de** [comment]
Well there are afaik no 32bit conda-forge packages.

**Comment by jbarnoud** [comment]
> Well there are afaik no 32bit conda-forge packages.

I'd be tempted to use the version on pypi then. You built the conda package, do you have an objection?

**Comment by kain88-de** [comment]
There is a conda-forge issue about 32 bit. https://github.com/conda-forge/conda-forge.github.io/issues/163

**Comment by jbarnoud** [comment]
Youhou! It appears that my last tries on the matter succeeded! The tests now fails with errors that seems consistent with a 32 / 64 bits mismatch. I get errors with ENCORE in the lines of

```
======================================================================

ERROR: test_clustering_two_ensembles (MDAnalysisTests.analysis.test_encore.TestEncoreClustering)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-pacDAnalysisTests/analysis/test_encore.py", line 483, in test_clustering_three_ensembles_two_identical

    cluster_collection = encore.cluster([self.ens1, self.ens2, self.ens1])

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/MDAnalysis/analysis/encore/clustering/cluster.py", line 220, in cluster

    results = pc.run()

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/MDAnalysis/analysis/encore/utils.py", line 298, in run

    **self.kwargs[i])))

  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/MDAnalysis/analysis/encore/clustering/ClusteringMethod.py", line 157, in __call__

    noise=int(self.add_noise))

  File "MDAnalysis/analysis/encore/clustering/affinityprop.pyx", line 101, in MDAnalysis.analysis.encore.clustering.affinityprop.AffinityPropagation.run (MDAnalysis/analysis/encore/clustering/affinityprop.c:2206)

ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'
```

I do not get all the errors @rathann reported, though. For instance, I did not notice the ones from #1362 in the [travis log](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/244224278).

Anyway, I am going to wait for @utkbansal's #1370 to be merged before going much further here as it is going to conflict pretty much everywhere.

**Pull request closed without merging**
