### PR TITLE
Feature jmolselectionwriter

### PR DESCRIPTION
**Pull request by ivirshup**
Added `selections/jmol.py`, a reference to that under `selections/__init__.py` a test under `test_selections.py`, and updated relevant documentation in `core/AtomGroup.py`.

Sorry about the merge history! My git skills are a little limited, and this is beyond my knowledge of `git rebase -i`.

### CODE REVIEW

**Comment by richardjgowers** [comment]
Hey

Looks good.

You might be able to squash these commits all together with `git rebase -i HEAD~7`, but don't worry too much about it if it's not easy.

There's a few little things to do before I can merge:
 - add a line to CHANGELOG and your name to the 0.11.0 release
 - add your name to AUTHORS
 - create a little .rst stub in `mdanalysis/package/doc/sphinx/source/documentation_pages/selections/` (copy another one from there)
 - add jmol entries to the table and the toctree in `mdanalysis/package/doc/sphinx/source/documentation_pages/selections_modules.rst`

And then we're good to go

**Comment by orbeckst** [comment]
@ivirshup  , thanks for your contribution. Adding to @richardjgowers 's list: Please also

* add your name to [`mdanalysis/package/doc/sphinx/source/conf.py`](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/conf.py#L88) (variable `authors` on line 88); add it where it belongs alphabetically.

For squashing commits: on your branch
```
git rebase -i d1c8cc8   # will keep the first commit untouched (or use HEAD~7 to get everything)
```
Squash all doc commits and all test commits into single commits.

Then force update this branch:
```
git push --force
```
(If you feel uncomfortable doing any of this then it's also ok and we'll just take the commits that you have – a clean history is nice but code contributions are even nicer ;-) )

**Comment by ivirshup** [comment]
I've added the doc changes, but am still having trouble cleaning up the history. 
Thanks for walking me through this! Is there anything I missed?

**Comment by richardjgowers** [comment]
Just the conf.py file linked above. Don't worry about the history.

**Comment by orbeckst** [comment]
@richardjgowers , I am doing the merge. I changed something in the tests so I have to do some manual merging anyway so I'll also do the history rewriting.

**Comment by orbeckst** [comment]
I pushed a new branch mdanalysis/feature-jmolselectionwriter but I cannot generate a new PR from the branch; instead it becomes associated with this one (#356) even though that PR came from @ivirshup 's clone.

I'll just wait for travis and then do the merge from the command line.

**Comment by orbeckst** [comment]
I just merged. @ivirshup , many thanks for your contribution.

**Pull request closed without merging**
