### PR TITLE
Copy README into package

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes pypi upload issues

This is a bit of a silly one, setup.py requires README.rst to create the long format description for pypi. However the README.rst doesn't get uploaded to PyPi so you end up with a case where you can't build off it.

The only quick solution I could find was to have a copy of that README.rst within `package` that will then get uploaded.

Thoughts / quick review @MDAnalysis/coredevs we would like to push a release as soon as.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
tests are failing because of #2985

**Comment by richardjgowers** [comment]
@IAlibay you'll also have to include this in MANIFEST for it to get included in the sdist

**Comment by IAlibay** [comment]
Done. I'm still not happy with the idea of having a copy of the main readme in package. I have changed the name so as to make it less confusing in case end users look at the source on pypi.

**Review by orbeckst — APPROVED** [review]
thanks!

**Pull request merged**
