### PR TITLE
Parse atomtypes section of itp files

### LINKED ISSUE #3199: ITPParser gets confused with masses
## Expected behavior ##

MDAnalysis is capable of reading itp-style topology files in the same way gromacs does. Getting the masses of all atoms right.

## Actual behavior ##

If some masses are not defined inside the `[ atoms ]` section, the parser disregards all of them and tries guessing.

---

MDAnalysis looks for masses in the `[ atoms ]` section of the `[ moleculetype ]` section. It disregards the `[ atomtypes ]` section. That a limitation, but not a very big problem.

If one happens to have just one atom that has its mass implied from the `[ atomtypes ]` section instead of defining it directly, the parser throws out all masses and tries to guess them all, even those defined in the right spot. 

At the very least there should be a warning about discarding the masses and guessing them. When I first ran into this, I couldn't make sense of it that MDAnalysis tried to guess masses it should know.
But I think it would be elegant to only guess the masses that are not available. 
And the best case would be to infer them from the `[ atomtypes ]` section, completely mimicking gromacs.

## Code to reproduce the behavior ##

I attached a stub topology I used to test this.

``` python
$ python3 -c 'import MDAnalysis as mda; u = mda.Universe("topol.top", topology_format="itp"); print(u.atoms.atoms.masses)'#
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: AY1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: AY2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: HOY
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: K+
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY3
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY4
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY5
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY6
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY7
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY8
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: OY9
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: SY1
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: SY2
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
/home/henrik/mdanalysis/package/MDAnalysis/core/universe.py:157: UserWarning: No coordinate reader found for topol.top. Skipping this file.
  warnings.warn('No coordinate reader found for {}. Skipping '
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

....

```

## Current version of MDAnalysis ##

```
$ python3 -c "import MDAnalysis as mda; print(mda.__version__)"
2.0.0-dev0
$ python3 -V
Python 3.8.5
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

## topology ##

```
[ defaults ]
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ
  1             2               no              1.0     1.0

; ions       
[ atomtypes ]
;name   at.num  mass      charge  ptype   sigma  epsilon
K       19      39.098    1       A       0.283  0.90
NA      11      22.990    1       A       0.231  0.45
CL      17      35.450    -1      A       0.430  0.42
BR      35      10.810    -1      A       0.443  0.75

; Mica
[ atomtypes ]
;name   at.num  mass        charge          ptype       sigma           epsilon
SY1         14      28.08600    0.000000        A       0.356359487256  0.209200
AYT2        13      26.98153    0.000000        A       0.374177461619  0.209200
OY1          8      15.99940    0.000000        A       0.311814551349  0.104600
OY3          8      15.99940    0.000000        A       0.311814551349  0.104600
OY5          8      15.99940    0.000000        A       0.311814551349  0.104600
AY2         13      26.98153    0.000000        A       0.374177461619  0.209200
OY7          8      15.99940    0.000000        A       0.311814551349  0.104600
OY2          8      15.99940    0.000000        A       0.311814551349  0.104600
HOY          1      1.008000    0.000000        A       0.096662510918  0.062760
AY1         13      26.98153    0.000000        A       0.374177461619  0.209200
OY8          8      15.99940    0.000000        A       0.311814551349  0.104600
K+          19      39.09830    0.000000        A       0.338541512893  0.836800
OY6          8      15.99940    0.000000        A       0.311814551349  0.104600
AYT1        13      26.98153    0.000000        A       0.374177461619  0.209200
SY2         14      28.08600    0.000000        A       0.356359487256  0.209200
OY9          8      15.99940    0.000000        A       0.311814551349  0.104600
OY4          8      15.99940    0.000000        A       0.311814551349  0.104600

[ moleculetype ]
; molname    nrexcl
SURF    3

[ atoms ]
;   nr       type  resnr residue  atom   cgnr     charge       mass
     1        AY1      1   SURF     Al      1      1.449     26.982   ;
     2        SY1      1   SURF     Si      2      1.100     28.086   ;
     3        SY2      1   SURF     Si      3      1.100     28.086   ;
     4        HOY      1   SURF      H      4      0.200      1.008   ;
     5        OY1      1   SURF      O      5     -0.550     15.999   ;
     6        OY2      1   SURF      O      6     -0.550     15.999   ;
     7        OY3      1   SURF      O      7     -0.550     15.999   ;
     8        OY7      1   SURF      O      8     -0.758     15.999   ;
     9        OY8      1   SURF      O      9     -0.758     15.999   ;
    10        OY9      1   SURF      O     10     -0.683     15.999   ;
    11        AY1      1   SURF     Al     11      1.449     26.982   ;
    12        SY1      1   SURF     Si     12      1.100     28.086   ;
    13        SY2      1   SURF     Si     13      1.100     28.086   ;
    14        HOY      1   SURF      H     14      0.200      1.008   ;
    15        OY1      1   SURF      O     15     -0.783     15.999   ;
    16        OY2      1   SURF      O     16     -0.783     15.999   ;
    17        OY3      1   SURF      O     17     -0.550     15.999   ;
    18        OY7      1   SURF      O     18     -0.758     15.999   ;
    19        OY8      1   SURF      O     19     -0.758     15.999   ;
    20        OY9      1   SURF      O     20     -0.683     15.999   ;
    21        AY2      1   SURF     Al     21      1.448     26.982   ;
    22        AY2      1   SURF     Al     22      1.448     26.982   ;
    23        SY1      1   SURF     Si     23      1.100     28.086   ;
    24        SY2      1   SURF     Si     24      1.100     28.086   ;
    25        HOY      1   SURF      H     25      0.200      1.008   ;
    26        OY1      1   SURF      O     26     -0.783     15.999   ;
    27        OY2      1   SURF      O     27     -0.550     15.999   ;
    28        OY3      1   SURF      O     28     -0.550     15.999   ;
    29        OY4      1   SURF      O     29     -0.758     15.999   ;
    30        OY5      1   SURF      O     30     -0.758     15.999   ;
    31        OY6      1   SURF      O     31     -0.683     15.999   ;
    32        AY1      1   SURF     Al     32      1.449     26.982   ;

[ moleculetype ]
CION                1
[ atoms ]
1       K+          1       CION        K+       1      1 

[ system ]
Mica surface with specific water-salt mixture

[ molecules ]
SURF     1 ; periodic slab
CION	60
```

### PR DESCRIPTION
**Pull request by hejamu**
The info in atomtypes is written to a dict. It is then used for the masses not found in the [ atoms ] section. Masses that are still not found (missing include file could be a reason), the masses are guessed based on the guessed atomtype.

Fixes #3199

Changes made in this Pull Request:
 - The info in atomtypes is written to a dict. 
 - It is then used for the charges and masses not found in the [ atoms ] section. 
 - Masses that are still not found (missing include file could be a reason), are guessed based on the guessed atomtype.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by hejamu** [comment]
Equivalent to PR #3204

**Comment by lilyminium** [comment]
May I ask why you closed #3204? Are there any differences here?

**Comment by hejamu** [comment]
I force pushed the wrong HEAD to my branch 🙃 that closed the PR automatically...

Should be identical.

**Review by lilyminium — APPROVED** [review]

**Comment by lilyminium** [comment]
Oops, fair enough. Thank you for this addition @hejamu!

**Pull request merged**
