### PR TITLE
Removing mutable data structures and function calls as default arguments in the entire codebase

### LINKED ISSUE #4655: MAINT: a few mutable default arguments are back
Oli dealt with this 9 years ago in gh-590, but a few cases have accumulated since then. It is fairly low priority but easy to fix.

Can check locally with i.e., `ruff.toml` like this:

```
[lint]
ignore = ["E501"]
select = ["B006", "B008"]
```

`ruff check package`

Some obscure bug happened because of this in another project so I just thought of it again.

### PR DESCRIPTION
**Pull request by tanishy7777**
Fixes #4655 

Changes made in this Pull Request:
 - Removing mutable data structures and function calls as default arguments in the entire codebase and initializing/calling them inside the function instead
 - There were 12 issues found using the ruff module(select = B006, B008 and ignore=E501) which were all fixed

PR Checklist
------------
 - [x] Tests
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4834.org.readthedocs.build/en/4834/

### CODE REVIEW

**Review by RMeli — APPROVED** [review]
Thank you @tanishy7777, LGTM!

**Comment by RMeli** [comment]
Can you please fix the conflict on the CHANGELOG?

**Comment by tanishy7777** [comment]
> Can you please fix the conflict on the CHANGELOG?

Yes, I have fixed it

**Comment by RMeli** [comment]
Thanks @tanishy7777, much appreciated!

**Pull request merged**
