### PR TITLE
Update TPR parser for Gromacs 5

### LINKED ISSUE #456: upgrade TPR reader for Gromacs 5.x
The TPR reader does not read Gromacs 5.x input files but @jbarnoud started this work (as announced on the [developer list](http://developers.mdanalysis.org))

> I am updating the TPR parser to support the pbx100 format produced by gromacs 5. My current version passes the unit tests, and it can read the gromacs 5 TPR file I wanted MDAnalysis to read. The unit tests for the TPR parser test TPR files produced by versions of gromacs from 4.0 to 4.6.1; I would like to add tests for TPR files produced with more recent versions of gromacs. Ideally, I would like these TPR files to be produced using inputs as close as possible as the inputs used for the already existing tests. Yet, I do not find what input files were used. Could anybody point me toward these files?

I don't have the input files for the 2lyz or ab42 tprs but perhaps @zyxue (who wrote the TPR reader) can provide them, e.g. as an attachment to this issue?

Otherwise, try @richardjgowers 's suggestion (which seems to work for me):
```
echo System | gmx convert-tpr -s ab42_gmx_4.6.1.tpr -o ab42_gmx_5.0.5.tpr
```

### PR DESCRIPTION
**Pull request by jbarnoud**
Gromacs 5 introduces two new versions of the TPR format: pbx100 that is used by Gromacs 5.0.x and pbx103 that is used by Gromacs 5.1. This pull request updates the TPR parser to add the support of these two formats.

Gromacs 5 introduces a new type of dihedral angles described in [Bulacu2013]. These angles probably do not appear in the parsed topology. I did not test it, though.

Fix #456 

> [Bulacu2013] Improved Angle Potentials for Coarse-Grained Molecular Dynamics Simulations
> Monica Bulacu, Nicolae Goga, Wei Zhao, Giulia Rossi, Luca Monticelli, Xavier Periole, D. Peter >Tieleman, and Siewert J. Marrink
> Journal of Chemical Theory and Computation 2013 9 (8), 3282-3292
> DOI: [10.1021/ct400219n](http://pubs.acs.org/doi/abs/10.1021/ct400219n)

### CODE REVIEW

**Comment by richardjgowers** [comment]
Looks good. Minor things to add:
 - add yourself to [AUTHORS](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/AUTHORS)
 - add a line to [CHANGELOG](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/CHANGELOG)

**Comment by orbeckst** [comment]
Great, many thanks for the contribution.

@richardjgowers will merge the PR once you 

* added yourself to
  * **AUTHORS**
  * **[package/doc/sphinx/source/conf.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/doc/sphinx/source/conf.py)** (find the line with authors and insert yourself alphabetically)
* added a short summary to **CHANGELOG** (under Enhancements), referencing Issue #456

**Comment by jbarnoud** [comment]
By running further tests I realized I forgot a commit in my rebase so I rebased again with the changes of the forgotten commit, and re-pushed the branch (--force).

I also updated the author lists and the change logs. I hope I did it right.

**Comment by richardjgowers** [comment]
Awesome

**Pull request merged**
