### PR TITLE
Bump up auxiliary coverage

### PR DESCRIPTION
**Pull request by RMeli**
Start addressing #597; it would be nice to have a higher coverage (see #2410, #2453). This PR starts to bump up test coverage for `auxiliary` by testing raised exceptions.

Changes made in this Pull Request:
 - Added tests for exceptions in `auxiliary`

PR Checklist
------------
 - [x] Tests?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by RMeli** [comment]
For some reason I can't suggest a reviewer, but I think @fiona-naughton will be the most appropriate. :)

**Comment by orbeckst** [comment]
I requested @fiona-naughton for you.

**Comment by fiona-naughton** [comment]
Looks good to me! (other than maybe a few extraneous blank lines if we care about keeping the style consistent)

**Comment by RMeli** [comment]
Thanks for the comments @fiona-naughton; the blank lines are `flake8`'s fault! ;) I can revert them if preferred, but they should be conformant with PEP8.

**Comment by fiona-naughton** [comment]
Ah, fair enough - should be fine, then!

**Comment by orbeckst** [comment]
@fiona-naughton thanks.

In the future, can you please leave your reviews via the code reviews (click on files changed unless there's a button with your name on it when you've been requested)(and click approve/request changes to make it clearer that you reviewed the code and had an opinion? That's going to be the pattern for GSoC so I'd like to get everyone used to it.

**Pull request merged**
