### PR TITLE
Issue 1047 encore docs

### LINKED ISSUE #1047: encore docs are not included in online docs
### Expected behaviour

I should be able to find documentation for `MDAnalysis.analysis.encore` somewhere at http://devdocs.mdanalysis.org/
### Actual behaviour

No encore-related docs are visible.
### Currently version of MDAnalysis:
- Release:  0.16.0-dev0
- Date: October 19, 2016

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #1047 

Changes made in this Pull Request:
- include encore docs in sphinx doc tree
- updated overall references
- included and update MemoryReader docs
- added remaining ENCORE authors to AUTHORS

## PR Checklist
-  Tests? n/a
- [x] Docs?
-  CHANGELOG updated?, n/a
- [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
@mtiberti / @wouterboomsma please have a look at the encore docs. I only made sure that all files are referenced somewhere and show up with a header.

Please feel free to change as you see fit.

In `encore.similarities` I had to change the section style from single underscore to double underscore to avoid a conflict with sphinx/napoleon and the numpy doc style.

On this branch docs are not built and published so you have to do it yourself. The following works for me (I use a virtualenv):
```bash
pip install -e package/
cd package/doc/sphinx
make html
```

then browse `package/doc/html/index.html`.

**Comment by wouterboomsma** [comment]
@orbeckst Thanks for the comments. I'll try to fix this in the coming week.

**Comment by orbeckst** [comment]
@wouterboomsma if you look through what I have done and only have minor corrections then add them as comments/reviews. If this is basically ok then we just need someone like @kain88-de to say ok and merge and then you can still add more doc changes later.

If something is fundamentally wrong with what I wrote then we obviously don't want to merge this. Ultimately you or one of the other ENCORE devs are the ones who can make this call.

**Comment by wouterboomsma** [comment]
@orbeckst Thanks for putting in this work. I've found a bunch of small things with weird whitespace in the code etc. Are you sure it wouldn't be easier if I make the changes locally and then make a PR to this branch?
On a related note: this issue is related to Encore docs. But it seems that the MemoryReader is also not popping up properly - at least not where I expected to find it. Can you give me a hint on what I need to change to make it appear?

**Comment by kain88-de** [comment]
@wouterboomsma feel free make a PR against this branch.

About the MemoryReader docs. I think they need to be added [here](https://github.com/MDAnalysis/mdanalysis/tree/develop/package/doc/sphinx/source/documentation_pages/coordinates)

**Comment by orbeckst** [comment]
I added the MemoryReader docs in 5a24204416e95245bfdc18d15e266b23a6d1bdb5, including the examples discussed in
* AnalysisFromFunction example from https://github.com/MDAnalysis/MDAnalysis.github.io/pull/30#discussion_r85888977
* `transfer_to_memory()`
* how to make an in-memory trajectory of a sub-system with `Merge()` and `Universe.load_new()` from https://github.com/MDAnalysis/mdanalysis/issues/915#issuecomment-256225321

**Comment by wouterboomsma** [comment]
@orbeckst, Hehe, I just made almost exactly the same changes locally yesterday. I'll just merge them and finalise our edits. I'll submit a PR later today.

**Comment by kain88-de** [comment]
@orbeckst & @wouterboomsma are you happy with the current state now?

**Comment by wouterboomsma** [comment]
I'm happy.

**Comment by orbeckst** [comment]
added minor fix to one of the encore citation reST and fixed an error message in analysis.density, just because I couldn't be bothered to put it into a separate commit/PR....

I am happy. Once we decide on the order of the MemoryReader (afc vs fac) #1063 we just have to adapt those parts of the docs but at least they are correct as of now.

@kain88-de are you going to merge?

**Pull request merged**
