### PR TITLE
add active PRs to black ignore

### PR DESCRIPTION
**Pull request by marinegor**
Fixes #

Changes made in this Pull Request:
 - add files present in open PRs to the list of extend-exclude for black

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4815.org.readthedocs.build/en/4815/

### CODE REVIEW

**Comment by marinegor** [comment]
cc @RMeli -- as we discussed, I finally managed to automate creation of the list of files in active PRs. Not sure if it works as necessary (e.g. the comment lines in the list worry me, and I assume that everything after the first comment is not accounted for) -- could you double-check if it works for you? Or perhaps there's a better way to configure these files?

**Comment by marinegor** [comment]
The code I used to generate the lists:

```bash
#!/bin/bash

echo '' > active_files.lst
for num in $(gh pr list -L 200 | awk '{print $1}'); do
  echo Working on $num...
  echo "# ${num} $(gh pr view ${num} --json title --jq .title)" >> active_files.lst
  gh pr diff  --name-only ${num} >> active_files.lst
  echo '# ---------------------' >> active_files.lst
done

cat active_files.lst | grep -E '^(#|package/.*.py)' > active_files_package.lst
cat active_files.lst | grep -E '^(#|testuite/.*.py)' > active_files_testsuite.lst
```

**Comment by RMeli** [comment]
Thanks @marinegor, looks useful! We will have to fix CI first, and merge the `lib` formatting which is already mainly done.

**Comment by RMeli** [comment]
@marinegor I had a look at your script. I think looking at 200 PRs is a bit pessimistic. I think it might be worth including only PRs that have been updated (JSON filed: `updatedAt`) in the last few months. Maybe 2 months is enough (or even too much)? If a PR has been stale for a while, there will be likely conflicts anyways and we can help on a case-by-case basis.

**Comment by marinegor** [comment]
@RMeli 2 months it is, updated

**Comment by RMeli** [comment]
Thanks @marinegor, can you please share the script to filter by `updatedAt`? (Sorry, I'm being lazy here...)

**Comment by RMeli** [comment]
Please also fix the conflicts and exclude the files of the bits that we already formatted (`lib/` for instance).

**Comment by marinegor** [comment]
@RMeli the script:

```bash
#!/bin/bash

rm active_files.lst
for num in \
  $(gh pr list -L 200 --json number,updatedAt,createdAt,title \
  | jq '[.[] | select(.updatedAt > ("2024-10-02"))]' \
  | jq '.[] | .number');
do
  echo Working on $num...
  echo "# ${num} $(gh pr view ${num} --json title --jq .title)" >> active_files.lst
  gh pr diff  --name-only ${num} >> active_files.lst
  echo '# ---------------------' >> active_files.lst
done

cat active_files.lst | grep -E '^(#|package/.*.py)' > active_files_package.lst
cat active_files.lst | grep -E '^(#|testsuite/.*.py)' > active_files_testsuite.lst
```

and then I manually move the lists to `pyproject.toml`'s

**Comment by RMeli** [comment]
As discussed I closed https://github.com/MDAnalysis/mdanalysis/pull/4518. The situation looks much better.

PRs that still do a reasonable amount of changes are
* #4810 @RMeli 
* #4712 @marinegor 
* #4334 @hmacdope 

#4810 should be easy to fix and incorporate quickly. But I think if you can update the exclusion list, we can merge this and start formatting what is left.

**Comment by RMeli** [comment]
Please do save the `active_files_*.lst` files, so that we have the list of PRs to keep track of and we can do the formatting as soon as a PR is merged.

**Comment by RMeli** [comment]
@marinegor any chance this can be updated in the next few days? I plan to work on the reminder of the code base during Christmas break.

**Comment by marinegor** [comment]
@RMeli sure, just ping me like 48 hours in advance, top.

Also, I could add the script to the `maintainer` directory of the package, though don't really think it's a good idea -- but ping me if it is.

**Comment by RMeli** [comment]
I think about now is more and less 48 hours in advance to my holidays 😛

I think the script is very specific for this transition, so it is good to have it in the PR comments, but I don't think there is a real need to have it within the repo.

**Comment by marinegor** [comment]
@RMeli done!

I meant that perhaps it's good to not do that again if a PR gets updated, but then I just decided to update the script:

```bash
#!/bin/bash

rm active_files.lst
for num in \
  $(gh pr list -L 200 --json number,updatedAt,createdAt,title \
  | jq '[.[] | select(.updatedAt > ("2024-10-02"))]' \
  | jq '.[] | .number');
do
  echo Working on $num...
  echo "# ${num} $(gh pr view ${num} --json title --jq .title)" >> active_files.lst
  gh pr diff  --name-only ${num} >> active_files.lst
  echo '# ---------------------' >> active_files.lst
done


cat active_files.lst | sed '/#/d' | sed -e 's/\.py$/\\.py/' | sed -e 's/^\(.*\)\(\n\1\)\+$/\1/' | grep -E '^(#|package/.*.py)' | sed '1!s/^/| /' > active_files_package.lst
cat active_files.lst | sed '/#/d' | sed -e 's/\.py$/\\.py/' | sed -e 's/^\(.*\)\(\n\1\)\+$/\1/' | grep -E '^(#|testsuite/.*.py)' | sed '1!s/^/| /' > active_files_testsuite.lst
```

now the files that it outputs can be directly pasted after the `__pycache__` line in the respective `pyproject.toml` file.

**Comment by RMeli** [comment]
Thanks @marinegor, I'm going to merge this. The files are useful so that we can remove the different exclusions when PRs are merged. I'll make a note to remove them once formatting is completed.

**Review by RMeli — APPROVED** [review]

**Pull request merged**
