### PR TITLE
fix cython error on travis

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #

Changes made in this Pull Request:
 - fix block_imported tests importing cython modules

https://groups.google.com/forum/#!topic/cython-users/tQlwfcpdf0k

The tests fall for python 3.5> on travis now for unrelated changes.  I don't really know why this happens now but it seems related to the last cython update.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
@mtiberti & @wouterboomsma 

Could you have a look as well. The tests pass on my laptop. I assume they will also pass on travis. This currently blocks all other PR's since the functions cause failures of the builds due to a cython update.

**Comment by kain88-de** [comment]
@richardjgowers could you also have a look.

**Comment by mtiberti** [comment]
Hi, looks good to me. I just gave it a go on my local workstation (Python 3.5.3, Cython 0.27) and tests pass.

**Comment by kain88-de** [comment]
@mtiberti it would be nice if you can give a approve seal on github. Unless someone else does this I'm not allowed to hit the `squash and merge` button

**Pull request merged**
