### PR TITLE
fix travis file (tab -> space)

### LINKED ISSUE #2233: I broke travis
I think as part of PR #2231 I broke travis... since then I can't run Travis jobs, probably messed up .travis.yml.

Working on it...

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #2233 

Changes made in this Pull Request:
 - changed a stupid TAB to spaces (TAB was introduced in 4f8dc1723f3fdcccd0d66d1c7ac0e93620d417fe)

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
@MDAnalysis/coredevs please ok this PR so that testing can resume.

I also have to update a bunch of PRs so that they run the tests properly
- [ ] #2226
- [ ] #2221
- [ ] #2110

(It's soooooo embarrassing having to alert everyone to my own stupidity...)

**Comment by orbeckst** [comment]
Argh, the doc issue has not been fixed, see https://travis-ci.com/MDAnalysis/mdanalysis/jobs/189877496

**Comment by tylerjereddy** [comment]
I pushed a commit to (hopefully) pin sphinx to version `1.8.5`, which has been a common strategy in the last few days upstream, until a few matters can be resolved.

**Comment by orbeckst** [comment]
Thanks!!

**Pull request merged**
