### PR TITLE
Fix: groups.py doctest fixes

### PR DESCRIPTION
**Pull request by ljwoods2**
Fixes #3925 in part

Changes made in this Pull Request:
 - Fixed all failing doctests in groups.py using sphinx directives
 - Updated groups.py with Black formatting
 
Note: These tests will not pass using "pytest -v --disable-pytest-warnings --doctest-modules <file>" since I used sphinx directives to allow for concise example code. This can be changed but the documentation will become more verbose.

PR Checklist
------------
 - [X] Tests?
 - [X] Docs?
 - [x] CHANGELOG updated?
 - [X] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4374.org.readthedocs.build/en/4374/

### CODE REVIEW

**Review by IAlibay — DISMISSED** [review]
@ljwoods2 - could we ask you to revert the `black` auto formatting please? This not only makes reviews difficult but it also obscures the great work you're doing towards fixing this issue.

Auto formatting the library is an ongoing discussion, if it happens, it will be handled in a future PR.

**Comment by ljwoods2** [comment]
@IAlibay Done, I reverted a few things line-wise so I may have undone some PEP8 changes as well. In the future, should I change all the files I touch to be PEP-8 compliant, but not Black? Or do I only make the new code that I contribute PEP-8?

**Comment by RMeli** [comment]
> In the future, should I change all the files I touch to be PEP-8 compliant, but not Black? Or do I only make the new code that I contribute PEP-8?

The second one. New code should be PEP-8 compliant, but you should not fix other issues in the same file (will make review murkier). I know it's not great if you have linters on on your editor/IDE because of the large amount of errors you see, but until we decide to reformat the whole code base, this remains the best way forward for the project. If you feel strongly about this, please add your view/experience in https://github.com/MDAnalysis/mdanalysis/issues/2450.

**Comment by RMeli** [comment]
Cycling the PR to restart Codecov action.

**Review by orbeckst — CHANGES_REQUESTED** [review]
This all looks nice to me and seems to work for me locally (`make doctest`).

However, I haven't been super-involved with doctesting so I wanted to know from @hmacdope @richardjgowers @IAlibay (people involved in #3925 — other opinions welcome, too, of course!) **if using sphinx directives is ok?** In other words, are we ok with the following _not_ working: 
```
pytest -v --disable-pytest-warnings --doctest-modules
```
and _only_
```
make doctest
```
aka
```
sphinx-build -v -W -b doctest --keep-going   source ../doctest
```
being used for doc-testing?

I'll block the PR until that's clear.

**Comment by orbeckst** [comment]
FYI, this is what the _passing_ doctests look like
```
Document: documentation_pages/core/groups
-----------------------------------------
~/mdanalysis/package/MDAnalysis/topology/PDBParser.py:331: UserWarning: Element information is missing, elements attribute will not be populated. If needed these can be guessed using MDAnalysis.topology.guessers.
  warnings.warn("Element information is missing, elements attribute "
~/mdanalysis/package/MDAnalysis/core/selection.py:735: UserWarning: Your smarts-based atom selection returned the maxnumber of matches. This indicates that not allmatching atoms were selected. When callingatom_group.select_atoms(), the default valueof maxMatches is max(100, len(atom_group * 10)). To fix this, add the following argument to select_atoms: 
smarts_kwargs={maxMatches: <higher_value>}
  warnings.warn("Your smarts-based atom selection returned the max"
19 items passed all tests:
  16 tests in AtomGroup
  11 tests in AtomGroup.asunique
   7 tests in AtomGroup.select_atoms
   1 tests in AtomGroup.select_atoms.namedarguments
   1 tests in AtomGroup.select_atoms.smarts
   1 tests in AtomGroup.select_atoms.updating
  10 tests in AtomGroup.sort
  10 tests in AtomGroup.unique
  30 tests in GroupBase.center
  15 tests in GroupBase.concatenate
  12 tests in GroupBase.groupby
  18 tests in GroupBase.isunique
  12 tests in GroupBase.subtract
  12 tests in GroupBase.symmetric_difference
  12 tests in GroupBase.union
   7 tests in ResidueGroup.asunique
   7 tests in ResidueGroup.unique
   7 tests in SegmentGroup.asunique
   7 tests in SegmentGroup.unique
196 tests in 19 items.
196 passed and 0 failed.
Test passed.

```

**Review by orbeckst — APPROVED** [review]
Based on the [comments on using sphinx in doc tests from discord](https://discord.com/channels/807348386012987462/808088023957897258/1222597751255072932), using sphinx is ok so I am approving.

**Pull request merged**
