### PR TITLE
MAINT: Cython 3.x compat fix read-only

### PR DESCRIPTION
**Pull request by tylerjereddy**
* fixes the following build error with the latest Cython beta pre-release and allows the full test suite to pass (at least for me, locally) with both Cython `0.29.34` and latest beta

```
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      array_wrapper = ArrayWrapper()
      array_wrapper.set_data(<void*> data_ptr, <int*> &dim[0], dim.size, data_type)

      cdef np.ndarray ndarray = np.array(array_wrapper, copy=False)
      # Assign our object to the 'base' of the ndarray object
      ndarray.base = <PyObject*> array_wrapper
             ^
  ------------------------------------------------------------

  MDAnalysis/lib/formats/cython_util.pyx:115:11: Assignment to a read-only property
```

* `DEF` statements are deprecated in Cython 3.x as well, but I've kept this focused on the more serious error

----
:books: Documentation preview :books:: https://mdanalysis--4129.org.readthedocs.build/en/4129/

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM! thanks @tylerjereddy

**Comment by IAlibay** [comment]
How much overlap is there here with @orbeckst's PR for cython 3.0?

**Comment by orbeckst** [comment]
It looks to me as if this PR makes the necessary change in a more generic manner than what I did in PR #2989 . 

I think the only other thing I did was modify `setup.py` with
```python
 # Do not anymore use deprecated numpy API (needs Cython >=3.0)
 # in Cython http://docs.cython.org/en/latest/src/userguide/source_files_and_compilation.html#configuring-the-c-build and
 # https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#numpy-c-api
 define_macros.append(("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION"))
```

**Comment by tylerjereddy** [comment]
It looks like the other PR *requires* Cython 3.x while this one should work with the old and new series. I know some projects are aiming to support both for a while, but I have no issue if you want to focus on 3.x+ only and move the other PR forward when Cython 3.x releases in 2045.

**Review by orbeckst — CHANGES_REQUESTED** [review]
LGTM but add an entry to CHANGELOG that this is now compatible with Cython 3.0 beta

**Comment by tylerjereddy** [comment]
I made a `CHANGELOG` entry, maybe someone wants to help resolve the merge conflict that causes. I won't start ranting on merge conflicts and change logs again...

**Review by orbeckst — APPROVED** [review]

**Comment by tylerjereddy** [comment]
I squash-merged with two core dev approvals on a single line change and CI passing apart from codecov silliness.

**Pull request merged**
