### PR TITLE
[WIP] Issue 993 update citation

### PR DESCRIPTION
**Pull request by tylerjereddy**
Reference: #993 

This PR aims to update the citation information in all pertinent package / documentation files. I only found two places in the sphinx docs where changes were needed, and I did those two changes and the `README` manually.

Doing the metadata (package file headers) manually would be insane, so I drafted a [metadata citation injection and verification script / gist](https://gist.github.com/a5909f49e7c3ac3e364f097f455208e7) for the new citation.

The final output from running the above script:

``` output
Done; files changed: 172
QC check; num problematic files in full package: 0
problematic files: []
```

The WIP tag is placed on this PR because of the extremely large number of files changed in a semi-automated manner, thereby mandating a certain amount of caution / revision before merging.

For the metadata changes we might want to explicitly say to cite both papers rather than just listing both, which would just require a bit more string / file editing in the above script. May also be an argument for an extra newline in there [and / or URL info] depending on how picky you are.

### CODE REVIEW

**Comment by orbeckst** [comment]
@tylerjereddy thanks for taking this on. If you are already working on the standard header then we should have a discussion what it should like. It is certainly no appropriate anymore that Naveen, Liz and I have such a prominent position in it.

**Comment by orbeckst** [comment]
I opened #1002 for the broader discussion.

I would prefer to combine all comment header rewriting in one commit instead of two big ones. Can you script be modified to change other parts of the header as well, once we have agreed on something in #1002?

**Comment by tylerjereddy** [comment]
Yeah, that's fine, it is just string / file line parsing.

**Comment by tylerjereddy** [comment]
I've updated the branch / PR with the latest proposal in #1002, though I haven't looked into @richardjgowers suggestions of the dynamic author list.

Note that my code parsed two less files this time (now that more changes are being made and the header is being detected from the start point):
```
['package/MDAnalysis/__init__.py', 'package/MDAnalysis/analysis/nuclinfo.py']
```
I couldn't quite figure out why based on a quick look.

**Comment by richardjgowers** [comment]
I had a thought, this will create a merge conflict with every file in a PR that branched before this (notably #815 #797).  It might make more sense to rerun the script up top after those have merged.  As long as this gets done before the next release the ordering shouldn't matter too much?

**Comment by orbeckst** [comment]
I think @richardjgowers  https://github.com/MDAnalysis/mdanalysis/pull/1001#issuecomment-250152814 raises a good point: the less we mess with the two big merges the better. (It _might_ just go through without a hitch but in any case, these two big PRs will generate many new files whose headers will also have to be updated, so better do it all in one go.)

@tylerjereddy can we hold off and then you run the script once #797 and #815 are in?

**Comment by tylerjereddy** [comment]
Sounds good. I've pushed the script to [a repo](https://github.com/tylerjereddy/headerfix) because I couldn't push changes to the above anonymous gist. This is just a precaution in case the need to merge arises when I'm busy with relocation to the US ~mid-late December.

**Comment by kain88-de** [comment]
superseded by #1088

**Pull request closed without merging**
