### PR TITLE
WIP: New topology docs (#1078)

### LINKED ISSUE #1078: new topology docs
### Expected behaviour
The philosophy behind the new topology system #363 should be outlined. 
- [ ] docs
- [ ] CHANGELOG

### Actual behaviour
At the moment, PR #1077 only removed obviously outdated comments in the docs in `topology/__init__.py`. 

See also TODO in `core/topology.py` and the structure `doc/sphinx/documentation_pages/core_module.rst`.

~~Perhaps it would be worthwhile making this a proper rst file under `doc/sphinx` instead of cramming all the docs into a `__init__.py` etc (?).~~

### PR DESCRIPTION
**Pull request by dotsdl**
Fixes #1078 

Changes made in this Pull Request:
 - added new `topology.rst` doc page describing topology system
 - small edits to surrounding pages for continuity and consistency

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by richardjgowers** [comment]
The existing overview page is a nice page 1 for part 1, maybe with a quick update.

After this maybe the essentials
 * creating a Universe (and the two pillars a Universe is built on, Top and Traj) (this is what you've started here imo)
 * working with AtomGroups
 * AtomGroup selections (already there)
 * working with Residues and Segments (and also the levels of different attributes)
 * working with the trajectory (traj iteration and quirks of the one frame at a time system)
 * coordinate manipulation (introducing distance array and friends)
 * the analysis module (idea of prepackaged analysis tools, and how to write your own...)

Then past this point we're into more specific cases
 * working with bonds angles torsions
 * advanced Universe creation (everything left out of the previous Universe section to keep it light)
 * advanced Reader usage (ChainReader, auxs)
 * advanced Topology manipulation, (adding Attrs, creating new Attrs, adding/removing Res/Seg)

**Comment by dotsdl** [comment]
@richardjgowers ? I know I'm slow, but why are we merged now?

**Comment by richardjgowers** [comment]
I'm making another PR with docs, and I didn't want to cause merge conflicts

**Comment by dotsdl** [comment]
Ah gotcha. No worries, just saw it.

**Pull request merged**
