### PR TITLE
mark `analysis.atomicdistances.AtomicDistances` as not parallelizable

### LINKED ISSUE #4662: `MDAnalysis.analysis.atomicdistances`: Implement parallelization or mark as unparallelizable
Given a newly implemented parallelization (https://docs.mdanalysis.org/dev/documentation_pages/analysis/parallelization.html), implement it for all classes in `analysis.atomicdistances` module. You may use `analysis.RMSD` in `develop` as a reference.

You need to add:

 - appropriate implementation of result aggregation for AnalysisBase subclasses in `analysis.atomicdistances` module (or explicitly limit available backends if the classes aren't parallelizable)
 - a boilerplate fixture(s) to `testsuite/analysis/conftest.py`, analogous with existing ones
 - a `client_...` fixtures to all tests using in `testsuite/MDAnalysisTests/analysis/test_atomicdistances.py`, and modify the way run() method is called

### PR DESCRIPTION
**Pull request by talagayev**
Fixes #4662 

Changes made in this Pull Request:
 - `atomicdistances.AtomicDistances` explicitly marked as not parallelizable
 - Addition of tests to `test_atomicdistances.py` to assert `serial` backend

Reason why `atomicdistances.AtomicDistances` is not parallelizable: 
- Currently `Results` uses `UserDict` as input, while `atomicdistances.AtomicDistances` outputs an `numpy.ndarray`
so it would require the modification of the output or modification of `Results` to make it parallelizable

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4808.org.readthedocs.build/en/4808/

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
You're right — but the issue is really that we somehow never upgraded this analysis class to use `Results`. I am not sure how this slipped through. I raised #4819.

Even though your PR looks fine, I'd prefer to fix #4819 and then parallelize the class because from the outside it makes no sense that such a simple calculation "cannot be parallelized". This would not look good.

Until we decide what to do with #4819, this PR should be on hold.

**Comment by talagayev** [comment]
> You're right — but the issue is really that we somehow never upgraded this analysis class to use `Results`. I am not sure how this slipped through. I raised #4819.
> 
> Even though your PR looks fine, I'd prefer to fix #4819 and then parallelize the class because from the outside it makes no sense that such a simple calculation "cannot be parallelized". This would not look good.
> 
> Until we decide what to do with #4819, this PR should be on hold.

Yes that sounds reasonable, since if #4819 is adressed, than it should not be a problem to implement the parallelization here with some quick adjustments

**Comment by orbeckst** [comment]
@talagayev I am closing this PR — one way or another, we'll decide on PR #4822 how to continue.

**Comment by talagayev** [comment]
> @talagayev I am closing this PR — one way or another, we'll decide on PR #4822 how to continue.

Yes, sounds good by me :) I can just create a new PR as soon as the decision is done for PR #4822. Adding
the parallelization in #4822 would also not be a problem.

**Pull request closed without merging**
