### PR TITLE
Check for enpty coordinates in RDKit converter

### LINKED ISSUE #4813: RDKit test failure
RDKit test failures started to [show up in CI](https://github.com/MDAnalysis/mdanalysis/actions/runs/12105211274/job/33749526496?pr=4812
):
```
>               Chem.AssignStereochemistryFrom3D(mol)
E               RuntimeError: Cannot normalize a zero length vector
```

A new version of RDKit landed a couple of days ago: https://github.com/rdkit/rdkit/releases.

### PR DESCRIPTION
**Pull request by RMeli**
Fixes #4813 

Changes made in this Pull Request:
 - Embed molecule created from SMILES

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4824.org.readthedocs.build/en/4824/

### CODE REVIEW

**Comment by cbouy** [comment]
Mmmh it might be relevant to extend the `if np.isnan(ag.positions).any()` check in the `convert` method to also handle the case where all atoms have coordinates `0, 0, 0` so that we don't try to assign these coordinates (and ultimately assign stereo from these dummy coordinates) when that happens?

**Comment by RMeli** [comment]
Thanks @cbouy, good suggestion.

**Review by cbouy — APPROVED** [review]
LGTM! Thank you 🙌

**Review by IAlibay — APPROVED** [review]
lgtm thanks!

**Comment by IAlibay** [comment]
CI failure is known, going ahead with merge.

**Pull request merged**
