### PR TITLE
added hbond_autocorrel duecredit

### PR DESCRIPTION
**Pull request by richardjgowers**

### CODE REVIEW

**Comment by orbeckst** [comment]
Come to think: can you add a test to `utils/test_duecredits.py` to check that your reference is picked up?

**Comment by orbeckst** [comment]
@richardjgowers sorry I hijacked your PR with a few more duecredit changes. But I also added the tests that I asked for... feel free to merge if you're happy.

I replaced your BibTeX citation with a Doi-based one. Please change back if you don't like it.

**Comment by orbeckst** [comment]
The duecredit output now looks like
```
DueCredit Report:
- Molecular simulation analysis library / MDAnalysis (v 0.18.1-dev) [1, 2]
  - Hydrogen bonding autocorrelation time / MDAnalysis.analysis.hbonds.hbond_autocorrel (v 0.18.1-dev) [3]
  - Path Similarity Analysis algorithm and implementation / MDAnalysis.analysis.psa (v 0.18.1-dev) [4]
- Scientific tools library / numpy (v 1.14.2) [5]

2 packages cited
2 modules cited
0 functions cited

References
----------

[1] Gowers, R.J. et al., 2016. MDAnalysis: A Python package for the rapid analysis of molecular dynamics simulations. In S. Benthall & S. Rostrup, eds. Proceedings of the 15th Python in Science Conference. pp. 102–109.
[2] Michaud-Agrawal, N. et al., 2011. MDAnalysis: A toolkit for the analysis of molecular dynamics simulations. Journal of Computational Chemistry, 32(10), pp.2319–2327.
[3] Gowers, R.J. & Carbone, P., 2015. A multiscale approach to model hydrogen bonding: The case of polyamide. The Journal of Chemical Physics, 142(22), p.224907.
[4] Seyler, S.L. et al., 2015. Path Similarity Analysis: A Method for Quantifying Macromolecular Pathways E. Tajkhorshid, ed.. PLOS Computational Biology, 11(10), p.1004568.
[5] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.
```

**Comment by orbeckst** [comment]
Currently failing because apparently duecredit is not happy with certain DOIs as keys in the hole module:
- 10.1016/S0263-7855(97)00009-X
- 10.1016/S0006-3495(93)81293-1

but it is ok with 
- 10.1016/j.jmb.2013.10.024

Perhaps the parentheses??

I am using the `due.Doi()` function to create the entries.

**Comment by orbeckst** [comment]
The problem was that citekeys are *always lower case* within the `due.citations` object. Fixed and force-pushed.

**Comment by richardjgowers** [comment]
@orbeckst yep looks good to me, DOI is much easier and bibtex citations can still get exported so all good

**Comment by richardjgowers** [comment]
May as well make this PR all the citations then, I'll think of some way of grepping the repo for recommended citations..... there's definitely the waterdynamics one to add

**Comment by orbeckst** [comment]
I did all citations so far with import_module=True although in some cases we should probably decorate a function with @dcite. But this is harder to test...

There is also the tags kwarg, which I have not used. 

But overall it looks neat and we might even be able to generate our citations doc page from the duecredit output. 



--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by richardjgowers** [comment]
Ok I added the ones I could think of, not sure there's any others to include?

@kain88-de does xdrlib have a citation?

Maybe mmtf?

**Comment by kain88-de** [comment]
yes looks alright

**Pull request merged**
