### PR TITLE
fixes for mac installation using clang on older machines (travis)

### LINKED ISSUE #2180: Travis build fails on macos with python 2.7
**Expected behavior**

TravisCI can build MDAnalysis for all tested OS and python versions.

**Actual behavior**

The MacOS build on python 2.7 fails to compile. After a diff between travis's logs on python 3.6 (which succeeds) and travis's logs on python 2.7 (which fails), therelevant error seems to be:

* On failing python 2.7 (<https://travis-ci.org/MDAnalysis/mdanalysis/jobs/481760970#L2180>)

```
g++ -bundle -undefined dynamic_lookup -L/Users/travis/miniconda/envs/test/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/MDAnalysis/lib/_cutil.o -L/Users/travis/miniconda/envs/test/lib -lm -o build/lib.macosx-10.6-x86_64-2.7/MDAnalysis/lib/_cutil.so -stdlib=libc++

clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

error: command 'g++' failed with exit status 1
```

* On succeeding python 3.6 (<https://travis-ci.org/MDAnalysis/mdanalysis/jobs/481760969#L2219>)

```
g++ -bundle -undefined dynamic_lookup -L/Users/travis/miniconda/envs/test/lib -arch x86_64 -L/Users/travis/miniconda/envs/test/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/MDAnalysis/lib/_cutil.o -lm -o build/lib.macosx-10.7-x86_64-3.6/MDAnalysis/lib/_cutil.cpython-36m-darwin.so -stdlib=libc++

ld: warning: object file (build/temp.macosx-10.7-x86_64-3.6/MDAnalysis/lib/_cutil.o) was built for newer OSX version (10.9) than being linked (10.7)
```

The issue is likely related to #2162 and #2163

**Code to reproduce the behavior**

Problem occurs on travisCI builds, see links above. It would probably occur on non-travis MacOS build but I do not have a system to test it.

**Currently version of MDAnalysis**

0.19.3-dev 2bb0aa72c733793a05084dd45afcde3b8e485c02

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixes #2180 

Changes made in this Pull Request:
 - 

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by zemanj** [comment]
fingers crossed... :crossed_fingers:

**Comment by zemanj** [comment]
@richardjgowers Shouldn't that depend on the XCode / LLVM version used? Of course, one could have ci-helpers export the env variable in case it doesn't exist...

**Comment by zemanj** [comment]
@richardjgowers The OSX Python 2.7 setup worked, testsuite is running. If the OSX Python 3.6 build succeeds as well (I cancelled the other ones), should we revert the most recent change you have done in `setup.py`?

**Comment by richardjgowers** [comment]
@zemanj yeah looks like your approach worked, so maybe mine isn't needed

**Comment by richardjgowers** [comment]
@astrofrog @bsipocz we're using astropy/ci-helpers and our C++ builds failed (see #2180),  worth pushing this tweak upstream into the ci-helpers?

**Comment by bsipocz** [comment]
@richardjgowers - Sure, sounds good to me. Here is the file this can go into: https://github.com/astropy/ci-helpers/blob/master/travis/setup_conda_osx.

I'm not aware of projects within astropy to do C++, but there are way much more users for ci-helpers than astropy so I suppose this may come up for others, too. If you want to be on the super safe side make it overrideable.

**Comment by zemanj** [comment]
Just checking if we can fix it in `setup.py` alone. Otherwise, users might experience the same problems when trying to install mda on an older osx platform...

**Comment by richardjgowers** [comment]
@zemanj ok I can't review this as github says this is my PR, so you'll have to review and merge

**Pull request merged**
