### PR TITLE
add binder button

### PR DESCRIPTION
**Pull request by kain88-de**
this will allow quick interactive usage of MDAnalysis

It's kind of nice and allows using MDAnalysis with minimal effort.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
https://mybinder.org/v2/gh/MDAnalysis/binder-notebook/master

**Comment by kain88-de** [comment]
currently there is only the PCA example in a notebook. 

I currently have all the notebooks in another repository. We might as well also just push the notebooks in this repository and have binder launch from it.

I in general find this a nice idea as it allows people to give MDAnalysis a quick spin.

**Comment by kain88-de** [comment]
They can even upload their own files (I guess there is a filesize limit though) and analyze their own data.

**Comment by orbeckst** [comment]
Ok, https://github.com/MDAnalysis/binder-notebook ...

**Comment by kain88-de** [comment]
The binder would be added to the new repository. I want to play a little bit more if it might not be better to include them here. If the default link is to the master branch then there are not to frequent rebuilds and we are sure that there is a new image after every release.

**Pull request merged**
