### PR TITLE
Fix a docstring example so it can be run on copy+paste

### PR DESCRIPTION
**Pull request by mattwthompson**
Changes made in this Pull Request:

In the workshop, I came across some code snippets in docstrings that didn't quite work directly after being copied. I will add some others if I come across them again.

PR Checklist
------------
 - [ ] Tests?
 - [x] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
@mattwthompson please also add yourself to AUTHORS

**Comment by mattwthompson** [comment]
Found another little one that I encountered during the workshop

**Comment by richardjgowers** [comment]
Cool, thanks @mattwthompson !

**Comment by orbeckst** [comment]
@richardjgowers please feel free to squash-merge once CI finishes – I might be busy. Thanks.

**Pull request merged**
