### PR TITLE
xfail on h5md write nt test, more py3.6->3.7 changes

### PR DESCRIPTION
**Pull request by IAlibay**
Temporarily addresses #3406

Changes made in this Pull Request:
 - xfail on windows NT for `TestH5MDWriterWithRealTrajectory.test_write_with_drivers`
 - more py3.6 -> py3.7 changes

PR Checklist
------------
 - [x] Tests?
 - Docs?
 - CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
codecov seems to be doing it's weird "fail for no reason" thing - this _should_ be fine?

**Comment by IAlibay** [comment]
Let's just try pinning h5py (see if it's related to 3.4.0)

**Review by orbeckst — APPROVED** [review]
Please also update the setup.py metadata to remove 3.6.

Otherwise looks ok but we should have an open issue for the failures. I don't really want to have to restrict the h5py versions needlessly.

**Comment by IAlibay** [comment]
@orbeckst, which metadata? I was pretty sure I had already removed it previously but I'm probably looking at the wrong thing?

Re: issue - I'm planning to keep #3406 open (probably renamed) so that we can keep an eye on h5py and un-pin as soon as we can.

**Comment by orbeckst** [comment]
I didn’t look into setup.py when I wrote my comment (and still haven’t, sorry). I meant the Python version that is set in the PyPi metadata. If that’s already >= 3.7 then there’s nothing else to be done. I haven’t kept up with the details of NEP29 — is 2.1 going to be 3.7-3.9?

> Am 8/26/21 um 18:30 schrieb Irfan Alibay ***@***.***>:
> 
> @orbeckst, which metadata? I was pretty sure I had already removed it previously but I'm probably looking at the wrong thing?

**Comment by IAlibay** [comment]
> I meant the Python version that is set in the PyPi metadata. 

Ah ok, yeah I deleted that in the previous PR, I had just forgotten to delete out all the things here.

>  I haven’t kept up with the details of NEP29 — is 2.1 going to be 3.7-3.9?

If we were to release today, that would be the case. If we release in 6 months, we probably would be 3.8-4.0. I'm setting it to a minimum of "what would happen if we released tomorrow", and then we can progressively push the support as time goes by?

**Comment by orbeckst** [comment]
Very sensible, I agree with your approach. 

> Am 8/27/21 um 08:31 schrieb Irfan Alibay ***@***.***>:
> 
> If we were to release today, that would be the case. If we release in 6 months, we probably would be 3.8-4.0. I'm setting it to a minimum of "what would happen if we released tomorrow", and then we can progressively push the support as time goes by?

**Comment by IAlibay** [comment]
Should be everything, I'll squash-merge so we don't stall other PRs.

**Pull request merged**
