### PR TITLE
[WIP/TEST] Switching matplotlib to matplotlib-base

### LINKED ISSUE #2540: depend on matplotlib-base instead of matplotlib
PR https://github.com/conda-forge/mdanalysis-feedstock/pull/22 suggests that we should use matplotlib-base as our matplotlib dependency (instead of matplotlib).

~Is this a good idea?~ yes

- [ ] Test if it works. 
- [ ] Update our CI to use matplotlib-base instead of matplotlib.
- [ ] Update dependencies in `setup.py`.

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #2540 

Changes made in this Pull Request:
 - Switches from matplotlib to matplotlib-base in dependencies.

Couple of things need testing at this point:
 - That travis works.
 - ~~Visualization stuff (I believe these won't be covered by our tests).~~ (I was completely wrong in this, there are tests).
 - That users with matplotlib installed won't end up with the matplotlib-base package overwriting things.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
@IAlibay is this still WIP or ready?

**Comment by IAlibay** [comment]
@orbeckst sorry, I forgot to get this one finished. In light of https://github.com/MDAnalysis/mdanalysis/issues/2540#issuecomment-592567350 if I'm understanding what you're proposing, the approach here is probably to git revert the whole thing, and change one (or more) of the Travis test instances to use matplotlib-base?

**Comment by IAlibay** [comment]
Right, finally came back to this one, it looks like the main issue here (aside from my inability to type) is that matplotlib-base isn't supported by py3.5. At this point, I'm not sure if it's currently worth updating the test matrix to have a special case for py3.5. It might be worth just waiting until v1.0 is complete, and then as per https://github.com/MDAnalysis/mdanalysis/issues/2541#issuecomment-590611719 we just drop py3.5 alongside py2.7? Thoughts @orbeckst ?

**Comment by orbeckst** [comment]
Ok, then let's do this for > 1.0.

Thanks for researching the issue.

**Comment by IAlibay** [comment]
Closing this PR as there'll probably be quite a lot of changes to Travis/Appveyor/Setup when we get past 1.0. I'll re-open a new one if needed at that point.

**Pull request closed without merging**
