### PR TITLE
Move libmdanalysis to lib

### LINKED ISSUE #3912: Move libmdanalysis to lib
So something that came up in a conversation somewhere else - `libmdanalysis` is a suitably big name clash with `lib` that it has a high potential to make folks confused. Is there any way we can avoid this direct clash? Could we call it anything else or could we put `libmdanalysis` within `lib` at least?

_Originally posted by @IAlibay in https://github.com/MDAnalysis/mdanalysis/issues/3734#issuecomment-1303989000_

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #3912 

Changes made in this Pull Request:
 - Moves the `libmdanalysis` __init__.pxd file to lib.

PR Checklist
------------
 - [x] CHANGELOG updated?
 - [X] Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
Since this made it to 2.3.0, do we think the userbase was large enough that we need to semver or are we happy going ahead with the change?

Also were there any docs associated with this?

**Comment by hmacdope** [comment]
I don't think there is a need to semver, but there should be docs in the developer docs. Ill add them.

**Review by IAlibay — APPROVED** [review]
I'm just going to put this down as a "approved", but we should get those docs in somewhere.

**Review by orbeckst — APPROVED** [review]
lgtm

**Comment by hmacdope** [comment]
Cheers,  new issue raised #3921

**Pull request merged**
