### PR TITLE
conda build

### PR DESCRIPTION
**Pull request by hainm**
How to build?

- install conda
- `cd mdanalysis/package/devtools/conda-recipe`
- `conda build ./mdanalysis --py=2.7`

How to upload
- create your (`mdanalysis`) channel on annaconda
- `conda install anaconda-client` # to get binstar
- `anaconda login` # enter your username + pw
- upload: `binstar upload /home/haichit/anaconda3/conda-bld/linux-64/mdanalysis-0.13.0dev0-np19py27_0.tar.bz2`

how to install

`conda install mdanalysis -c mdanalysis`
- `-c` is to specify channel name.

The files in this PR are self-explain. Update to your need.

### CODE REVIEW

**Comment by hainm** [comment]
if you want to install your build locally

`conda install /home/haichit/anaconda3/conda-bld/linux-64/mdanalysis-0.13.0dev0-np19py27_0.tar.bz2`

(or whatever dir to the build tar file)

**Comment by hainm** [comment]
@orbeckst you (or your students) should try yourself and let me know how you like conda :P

**Comment by hainm** [comment]
- how to push from travis: http://amber-md.github.io/pytraj/latest/developer_guide.html#push-pytraj-and-libcpptraj-to-anaconda-org-after-successful-build-on-travis

**Comment by orbeckst** [comment]
Thanks!

**Comment by orbeckst** [comment]
We'll see if we can make it work for the next release. I registered https://anaconda.org/MDAnalysis/mdanalysis .

**Comment by hainm** [comment]
let me know if you get any problem. It was a bit tricky when I started a while ago (since the error log in conda and binstar was not that great).

**Comment by orbeckst** [comment]
@richardjgowers (as release manager) if you want to play with this, register an account on https://anaconda.org and I add you to the https://anaconda.org/MDAnalysis org with sufficient privileges.

**Comment by richardjgowers** [comment]
@orbeckst Ok, this is me: https://anaconda.org/richardjgowers

**Comment by orbeckst** [comment]
Ok, added you as owner.

**Comment by kain88-de** [comment]
Since we have a new policy at work to use conda for managing python packages I'll start using it myself. So I can take care of getting MDAnalysis onto conda if @orbeckst and @richardjgowers are ok with it.

**Comment by richardjgowers** [comment]
Yes please!

**Comment by kain88-de** [comment]
@orbeckst can you add me to the MDAnalysis org on anaconda with the appropriate rights. Thanks

**Comment by kain88-de** [comment]
see #751 for an update of this.

**Comment by orbeckst** [comment]
I added @kain88-de as owner to https://anaconda.org/MDAnalysis

On 1 Mar, 2016, at 13:09, kain88-de wrote:

> @orbeckst can you add me to the MDAnalysis org on anaconda with the appropriate rights. Thanks
> 
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Pull request closed without merging**
