### PR TITLE
TPR reader sets `chainID` from `molblock`

### LINKED ISSUE #3994: Set `chainID` [was: `segID`] from `molblock` in TPR parser
Hi,

I've been surprised by this renaming of the `molblock`'s moltype name, when setting the `segid` attribute:
https://github.com/MDAnalysis/mdanalysis/blob/363037a31d2eb208540c0f255d4aaf8e1944cf4b/package/MDAnalysis/topology/tpr/utils.py#L330

Given that there's a comment saying the naming is arbitrary and that gromacs sets molecule names as `Protein_chain_{chainID}`, could we perhaps replace that line with:
```
segid = molblock[14:] if molblock[:14] == "Protein_chain_" else molblock
```
So `segid`s get the chainID character, and if not, it just gets the original molecule's name (eg: ION, SOL, other custom names)?

### PR DESCRIPTION
**Pull request by pgbarletta**
Fixes #3994

Trying to revive this issue, following @orbeckst's suggestion (don't set `molblock` to `Segments`, but to `chainIDs`). As usual, I'll delete the PR and the issue if this is not deemed useful.

Changes made in this Pull Request:
 - `tpr_utils.do_mtop()` sets the `chainID` of each atom as this: `chainID = molblock[14:] if molblock[:14] == "Protein_chain_" else molblock`
 - on the testing side: `TPRAttrs`  adds `chainIDs` to the list `expected_attrs`. I didn't thought it was necessary to add more tests on top of that.

If approved I'll add 'chainID' [here](https://docs.mdanalysis.org/stable/documentation_pages/topology/TPRParser.html#development-notes).

This does not warrant an addition to the `versionchanged` heading, right?

PR Checklist
------------
 - [X] Tests?
 - [x] Docs?
 - [X] CHANGELOG updated?
 - [X] Issue raised/referenced?

## Developers certificate of origin
- [X] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
:books: Documentation preview :books:: https://mdanalysis--4281.org.readthedocs.build/en/4281/

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
I am in favor of your change, @pgbarletta.

Do the tests check that specific chainIDs were parsed?

Please also do the usual (update CHANGELOG, docs, ...). Ping me when you need me to review again.

**Comment by pgbarletta** [comment]
I added the expected chainIDs to `TestTPRGromacsVersions` ---which inherits from `TPRAttrs`---, and then added the `test_chainIDs()` function to `TPRAttrs`. Let me know if I interpreted the testing style correctly or not.

**Review by orbeckst — APPROVED** [review]
Looks good to me. I think the testing is doing the right thing. It's a bit complicated and it took me a while to see what's happening with all the inheritance. The fact that you're testing a case with two chains gives me some confidence that it works.

Sorry for the delay, I had thought I had already done this review but obviously not... in general, feel free to ping me when a week has passed!

**Comment by orbeckst** [comment]
Thanks @pgbarletta !

**Comment by orbeckst** [comment]
> This does not warrant an addition to the versionchanged heading, right?

I read through everything an decided at the very last minute that it was better to document what we are doing and added it.

**Comment by orbeckst** [comment]
We do need to update the User Guide so I raised https://github.com/MDAnalysis/UserGuide/issues/312 — could you please do that, @pgbarletta ? Thanks.

**Pull request merged**
