### PR TITLE
Reset InterRDF variables in `_prepare`, fixes #924

### LINKED ISSUE #924: InterRDF can't be run twice
### Expected behaviour

running 

```python
rdf = InterRDF(...).run()
rdf.run()
```

shouldn't change the rdf result.

### Actual behaviour

Various counters like `self.count`, `self.volume` aren't reset in a `_prepare` function.

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #924

Changes made in this Pull Request:
 - Add a `_prepare` function to InterRDF

PR Checklist
------------
 - [x] Tests?
 - ~~[ ] Docs?~~
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

This hasn't been done so far. This leads to wrong results if `run` is
called twice.

### CODE REVIEW

**Comment by kain88-de** [comment]
@richardjgowers I've assigned you since you originally developed this.

**Comment by richardjgowers** [comment]
Yep np

**Comment by richardjgowers** [comment]
LGTM

**Comment by kain88-de** [comment]
linux builds are passing

**Pull request merged**
