### PR TITLE
Start 2.3.0-dev0 🎉

### PR DESCRIPTION
**Pull request by IAlibay**
Changes made in this Pull Request:
 - Started new changelog entry set
 - Updated versions

PR Checklist
------------
 - Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - Issue raised/referenced?

### CODE REVIEW

**Comment by IAlibay** [comment]
@MDAnalysis/coredevs simple enough one to review if someone can give this a thumbs up that'd be great. You can see how it was done for 2.1.0 here if you want to compare: https://github.com/MDAnalysis/mdanalysis/pull/3400

**Review by hmacdope — APPROVED** [review]
LGTM

**Review by orbeckst — APPROVED** [review]
LGTM.

You could fix the CHANGELOG #3696 here, too.

**Comment by IAlibay** [comment]
> LGTM.
> 
> You could fix the CHANGELOG #3696 here, too.

To avoid re-running CI I'll deal with that with the deploy PR.

**Pull request merged**
