### PR TITLE
Fix versions variable in docs and re-write index.html

### LINKED ISSUE #2962: https://docs.mdanalysis.org/ gives 404
## Expected behavior ##

https://docs.mdanalysis.org shows the most recent release docs

## Actual behavior ##

I get 404 page not found.

## Code to reproduce the behavior ##
Open https://docs.mdanalysis.org in browser

```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus
```

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes #2962 

Changes made in this Pull Request:
 - Fixed getting the `$VERSION` variable
 - Added some error messages and prints to track progress

Apologies for that, I didn't add the changes I made to `.travis.yml` because I removed all the other tests and substituted my own token / url so that error slipped through when I tested it.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Review by orbeckst — APPROVED** [review]
Let’s try it.

**Comment by orbeckst** [comment]
Do we also need this for master?

**Comment by lilyminium** [comment]
Yes but it didn't work, MDAnalysis is not installed in this one. Sorry :((( it seems that ``export VERSION=$(python -c "import version; print(version.__version__)")`` was right after all.

**Comment by orbeckst** [comment]
Thank you for figuring out all the nitty-gritty — much appreciated!

https://docs.mdanalysis.org does redirect to https://docs.mdanalysis.org/1.0.0/index.html and the version switching seems to be working.

**Pull request merged**
