### PR TITLE
Fix weights deprecations

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #

Changes made in this Pull Request:
 
I noticed that psa still used the old weights. This updates all of the occurrences and I moved the removal version to 0.18.0. Maybe better to give people a little more time.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 ~- [ ] Issue raised/referenced?~

### CODE REVIEW

**Comment by orbeckst** [comment]
If this goes into 0.16.1 then I would do the deprecation for 0.17.0 – that release will have a lot of crud removed.

**Comment by kain88-de** [comment]
I thought 0.18.0 would be good to give people a little bit more time.

**Comment by orbeckst** [comment]
I don't know how many people are relying on PSA, it's certainly not the same number that rely on core features. And we tend to have a fair amount of time between releases nowadays so all taken together, I don't think that 0.17.0 is too burdensome. 


> Am May 21, 2017 um 08:12 schrieb Max Linke <notifications@github.com>:
> 
> I thought 0.18.0 would be good to give people a little bit more time.

**Comment by kain88-de** [comment]
@orbeckst sure I can also move the date back.

**Comment by kain88-de** [comment]
@orbeckst could you reivew please

**Comment by orbeckst** [comment]
p.s.: I tend to rebase against develop and force-push instead of merging develop into a pr. IIR that makes it easier to squash/merge later.

**Comment by orbeckst** [comment]
Tests all pass, just one hanging one (which I restarted).

**Comment by orbeckst** [comment]
@kain88-de please merge yourself.

**Comment by kain88-de** [comment]
> p.s.: I tend to rebase against develop and force-push instead of merging develop into a pr. IIR that makes it easier to squash/merge later.

normally me too. But the github fixup is super convenient. Github should take care of them during merges of the PR by removing these commits again. I should test this some time

**Pull request merged**
