### PR TITLE
 Importing ABCs from `collections.abc`

### LINKED ISSUE #2605: Deprecation warning from "collections" library
## Expected behavior ##
No deprecation warning

## Actual behavior ##

```python
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(v, collections.MutableMapping):
```

## Code to reproduce the behavior ##

16th cell in quick start user guide

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD
u = mda.Universe(PSF, DCD)
near_met = u.select_atoms('not resname MET and (around 2 resname MET)')
near_met.groupby(['resnames', 'names'])
```

## Current version of MDAnalysis ##

- Which version are you using? **0.20.1**
- Which version of Python? **3.7.4**
- Which operating system? **MacOS Catalina 10.15.3**

### PR DESCRIPTION
**Pull request by abhiShandy**
Fixes #2605 

Changes made in this Pull Request:
 - Importing ABCs from `collections.abc` instead of deprecated direct method in `collections.MutableMapping`

I ran `lib/test_util.py::TestFlattenDict` locally to confirm that the corresponding deprecation warning is eliminated.

PR Checklist
------------
 - [x] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by abhiShandy** [comment]
Travis CI failed since my change is not reverse compatible with Python 2.7
Should I make it reverse compatible?

**Comment by IAlibay** [comment]
@abhiShandy unfortunately MDA must support py2.7 until at least v1.0.0 (if I'm remembering the roadmap correctly). An option that would cover py2.7 through tto 3.8 would be appreciated if possible.

**Comment by lilyminium** [comment]
Do we *need* `MutableMapping`? So far as I can tell, ``flatten_dict`` is only used once in ``groups.py``, on a ``dict``.

https://github.com/MDAnalysis/mdanalysis/blob/d9a78a4eb1c3add937b34524b071e5ed185d924c/package/MDAnalysis/core/groups.py#L1726-L1745

**Comment by abhiShandy** [comment]
> Do we _need_ `MutableMapping`? So far as I can tell, `flatten_dict` is only used once in `groups.py`, on a `dict`.
> 
> https://github.com/MDAnalysis/mdanalysis/blob/d9a78a4eb1c3add937b34524b071e5ed185d924c/package/MDAnalysis/core/groups.py#L1726-L1745

Good point.
- changed it to `isinstance(v, dict)` to check if it's nested.
- Removed unnecessary `collections` from that file.

Locally, `lib/test_util` and `core/test_groups` has passes with Python 3.8

**Comment by abhiShandy** [comment]
@MDAnalysis/gsoc-mentors can someone review this?

**Comment by orbeckst** [comment]
Please ping me @orbeckst for a final review when you have addressed my review and all tests pass. Thank you for your contribution!

**Comment by abhiShandy** [comment]
@orbeckst it's ready

**Comment by orbeckst** [comment]
Thank you very much, @abhiShandy !

**Pull request merged**
