### PR TITLE
PSFParser reads and converts string-Like residue number to the leading number

### LINKED ISSUE #2053: parse charmm psf file with residue insertion codes failed
The 0.18.0 MDAnalysis failed to parse charmm psf file when the residue id is not pure digit.

Error message:

```
Traceback (most recent call last):
  File "temp.py", line 1287, in <module>
    traj = MDAnalysis.Universe(psffile, dcdfile)
  File "/opt/anaconda2/lib/python2.7/site-packages/MDAnalysis/core/universe.py", line 296, in __init__
    "Error: {2}".format(self.filename, parser, err))
ValueError: Failed to construct topology from file nowater.psf with parser <class 'MDAnalysis.topology.PSFParser.PSFParser'>.
Error: invalid literal for int() with base 10: '185A'
```

Here are a few lines from the psf file. It is quite common to have a letter in the residue id in pdb files.

> 

      4682 PROD     185      ASN      OD1      O       -0.550000       15.9990           0   0.00000     -0.301140E-02
      4683 PROD     185      ASN      ND2      NH2     -0.620000       14.0070           0   0.00000     -0.301140E-02
      4684 PROD     185      ASN      HD21     H        0.320000       1.00800           0   0.00000     -0.301140E-02
      4685 PROD     185      ASN      HD22     H        0.300000       1.00800           0   0.00000     -0.301140E-02
      4686 PROD     185      ASN      C        C        0.510000       12.0110           0   0.00000     -0.301140E-02
      4687 PROD     185      ASN      O        O       -0.510000       15.9990           0   0.00000     -0.301140E-02
      4688 PROD     185A     GLU      N        NH1     -0.470000       14.0070           0   0.00000     -0.301140E-02
      4689 PROD     185A     GLU      HN       H        0.310000       1.00800           0   0.00000     -0.301140E-02
      4690 PROD     185A     GLU      CA       CT1      0.700000E-01   12.0110           0   0.00000     -0.301140E-02
      4691 PROD     185A     GLU      HA       HB1      0.900000E-01   1.00800           0   0.00000     -0.301140E-02
      4692 PROD     185A     GLU      CB       CT2A    -0.180000       12.0110           0   0.00000     -0.301140E-02
      4693 PROD     185A     GLU      HB1      HA2      0.900000E-01   1.00800           0   0.00000     -0.301140E-02
      4694 PROD     185A     GLU      HB2      HA2      0.900000E-01   1.00800           0   0.00000     -0.301140E-02
      4695 PROD     185A     GLU      CG       CT2     -0.280000       12.0110           0   0.00000     -0.301140E-02
      4696 PROD     185A     GLU      HG1      HA2      0.900000E-01   1.00800           0   0.00000     -0.301140E-02

### PR DESCRIPTION
**Pull request by yuxuanzhuang**
Fixes #2053 #4189 

Changes made in this Pull Request:
 - Updated PSFParser to convert string-like residue numbers to their leading number. If the conversion fails, the residue number defaults to 0.

In CHARMM PSF, residue identifiers (resids) can be any string, as discussed in https://github.com/MDAnalysis/mdanalysis/issues/2053#issuecomment-1984023249. Tools like CHARMM-GUI and psfgen often modify resids by including insertion codes from PDB files or converting large resids to hexadecimal numbers for placement in the resid block.

We should support reading it and this update aligns with the approach used by VMD for reading the leading number (atoi as in C) from string-like resids.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4582.org.readthedocs.build/en/4582/

### CODE REVIEW

**Review by hmacdope — CHANGES_REQUESTED** [review]
This looks good to me @yuxuanzhuang. Thanks!  Would you be able to just add a quick test that the resids of the form `14F` etc are able to be read from the test file?

**Comment by orbeckst** [comment]
@hmacdope please look after this PR! Thank you!

(As always, if it gets too much please say something an un-assign yourself.)

**Review by hmacdope — APPROVED** [review]
Looks good to me now @yuxuanzhuang! Thanks!

**Comment by d-beltran** [comment]
Hey @yuxuanzhuang,

Is the insertion code saved?
I don't find how to read it in the residue instance.

Thank you!

**Pull request merged**
