### PR TITLE
Compatibility with Zarr Trajectory format

### PR DESCRIPTION
**Pull request by ljwoods2**
Changes made in this Pull Request:
 - Modified the ChainedReader's _format_hint to not catch Zarr groups

This is just one way I am proposing to allow future compatibility with the zarrtraj format (https://github.com/Becksteinlab/zarrtraj) that I'm developing in Oliver's lab (and potentially GSOC). Since the zarrtraj format is still in the prototyping phase, there is no urgency to merge this or an alternate solution and I'm open to different ways of approaching it.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

## Developers certificate of origin
- [x] I certify that this contribution is covered by the LGPLv2.1+ license as defined in our [LICENSE](https://github.com/MDAnalysis/mdanalysis/blob/develop/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

----
📚 Documentation preview 📚: https://mdanalysis--4557.org.readthedocs.build/en/4557/

### CODE REVIEW

**Comment by hmacdope** [comment]
@ljwoods2 as I think you know, this will have to be held, until the zarrtraj stuff is more mature. Is there a general case though that this PR solves? E.G chainreader cannot handle objects that are not  XX or YY?

**Comment by ljwoods2** [comment]
@hmacdope Yes, Oliver mentioned this issue: https://github.com/MDAnalysis/mdanalysis/issues/2884. I can come up with a better solution which in general allows object-based trajectory formats being passed in to not be caught by the ChainReader _format_hint

**Comment by ljwoods2** [comment]
Maybe it's as simple as iterating through all _format_hint() methods except for chainreader before checking chainreader

**Comment by orbeckst** [comment]
@ljwoods2 instead of "WIP" in the title you can also "convert to draft" to make the state extra clear (and really properly tagged in GH instead using a convention). It also has the advantage that you then only need a click (instead of a title change) when you're ready.

**Comment by ljwoods2** [comment]
Closing this because zarrtraj accepts filename strings instead of zarr.Group objects now, so no change to format_hint is needed

**Pull request closed without merging**
