### PR TITLE
Issues/#2490 migration

### LINKED ISSUE #2490: MDAnalysis/migration
Is the `MDAnalysis/migration` sub-package still useful or should it be removed for release 1.0? 

It contains some (failing) tests and the only occurrence in the code is in the main `__init__.py` where `ten2eleven` is imported (`from .migration.ten2eleven import ten2eleven`). The documentation of `ten2eleven` is the following:

```text
Convert MDAnalysis 0.10.0 scripts to 0.11.0

    Usage:
       ten2eleven('myscript.py')
```

### PR DESCRIPTION
**Pull request by RMeli**
Fixes #2490

Changes made in this Pull Request:
 - Removed `MDAnalysis.migration`

PR Checklist
------------
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by RMeli** [comment]
Test failures are caused by `seaborn`, see #2495 .

**Comment by orbeckst** [comment]
Can you rebase once the seaborn fix is in so that we merge with green CI? thanks 

(Ping me for the merge please)

**Comment by RMeli** [comment]
Sure, will do!

**Comment by RMeli** [comment]
CI looks good now @orbeckst .

**Pull request merged**
