### PR TITLE
Deprecation warnings now only appear once per deprecated feature

### PR DESCRIPTION
**Pull request by richardjgowers**
Should stop us getting spammed to death with deprecation warnings.

### CODE REVIEW

**Comment by kain88-de** [comment]
I think you can delete the line. Warning only once is the default.

**Comment by richardjgowers** [comment]
Dep warnings are ignored by default

**Comment by dotsdl** [comment]
Looks good to me.

**Comment by dotsdl** [comment]
@orbeckst do you think we should be louder, or is one deprecation warning for each unique instance enough?

**Comment by orbeckst** [comment]
Once is the norm, I think, and anything else annoys the hell out of people. I am ok with once.

**Pull request merged**
